// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/units.hpp>
#include <note/target.hpp>

namespace note::api {








/// The `card.power` API is used to configure a connected Mojo device or to
/// manually request power consumption readings in firmware.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct CardPower {

    struct Get {
        static constexpr string_view notecard_request = "card.power";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::ReadOnly;
        static constexpr Skus skus{ Rat::Cell | Rat::WiFi | Rat::Ntn };

        Notecard* nc_ = nullptr;

        /// How often, in minutes, Notecard should log power consumption in a
        /// `_log.qo` Note. The default value is `720` (12 hours).
        struct minutes_t : Field<note::Minutes> {
            using Field<note::Minutes>::Field;
            using Field<note::Minutes>::operator=;
            CardPower::Get& operator()(note::Minutes v);
        } minutes{};
        /// Set to `true` to reset the power consumption counters back to 0.
        struct reset_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardPower::Get& operator()(bool v);
        } reset{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (k_ == "reset") return note::dyn_field_for(reset);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        /// Response containing power consumption readings and environmental
        /// data from the Notecard.
        struct Response {
            /// The cumulative number of milliamp hours (mAh) consumed. You can
            /// reset this number with this request's `reset` argument.
            double milliampHours{};
            /// The temperature from Notecard's onboard sensor in degrees
            /// centigrade, including the calibration offset.
            double temperature{};
            /// The current voltage.
            double voltage{};

            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.milliampHours = reader_->get_double("milliamp_hours");
                rsp.temperature = reader_->get_double("temperature");
                rsp.voltage = reader_->get_double("voltage");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                rsp.milliampHours = reader_.get_double("milliamp_hours");
                rsp.temperature = reader_.get_double("temperature");
                rsp.voltage = reader_.get_double("voltage");
                return rsp;
            }

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are string_views into the JSON buffer; caller must
            // ensure the buffer outlives the Response (or intern strings after).
            struct Sink : ::note::JsonSink {
                Response& rsp;
                explicit Sink(Response& r) : rsp(r) {}
                void on_number(::note::string_view key, ::note::string_view raw) override {
                    if (key == "milliamp_hours") { rsp.milliampHours = ::note::parse_double(raw); return; }
                    if (key == "temperature") { rsp.temperature = ::note::parse_double(raw); return; }
                    if (key == "voltage") { rsp.voltage = ::note::parse_double(raw); return; }
                }
            };

            void intern_strings(::note::StringPool&) {}

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            if (reset) b.add("reset", *reset);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    /// The `card.power` API is used to configure a connected Mojo device or to
    /// manually request power consumption readings in firmware.
    ///
    /// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
    struct Set {
        static constexpr string_view notecard_request = "card.power";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Idempotent;
        static constexpr Skus skus{ Rat::Cell | Rat::WiFi | Rat::Ntn };

        Notecard* nc_ = nullptr;

        /// How often, in minutes, Notecard should log power consumption in a
        /// `_log.qo` Note. The default value is `720` (12 hours).
        struct minutes_t : Field<note::Minutes> {
            using Field<note::Minutes>::Field;
            using Field<note::Minutes>::operator=;
            CardPower::Set& operator()(note::Minutes v);
        } minutes{};
        /// Set to `true` to reset the power consumption counters back to 0.
        struct reset_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardPower::Set& operator()(bool v);
        } reset{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (k_ == "reset") return note::dyn_field_for(reset);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        /// Response containing power consumption readings and environmental
        /// data from the Notecard.
        struct Response {
            /// The cumulative number of milliamp hours (mAh) consumed. You can
            /// reset this number with this request's `reset` argument.
            double milliampHours{};
            /// The temperature from Notecard's onboard sensor in degrees
            /// centigrade, including the calibration offset.
            double temperature{};
            /// The current voltage.
            double voltage{};

            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.milliampHours = reader_->get_double("milliamp_hours");
                rsp.temperature = reader_->get_double("temperature");
                rsp.voltage = reader_->get_double("voltage");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                rsp.milliampHours = reader_.get_double("milliamp_hours");
                rsp.temperature = reader_.get_double("temperature");
                rsp.voltage = reader_.get_double("voltage");
                return rsp;
            }

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are string_views into the JSON buffer; caller must
            // ensure the buffer outlives the Response (or intern strings after).
            struct Sink : ::note::JsonSink {
                Response& rsp;
                explicit Sink(Response& r) : rsp(r) {}
                void on_number(::note::string_view key, ::note::string_view raw) override {
                    if (key == "milliamp_hours") { rsp.milliampHours = ::note::parse_double(raw); return; }
                    if (key == "temperature") { rsp.temperature = ::note::parse_double(raw); return; }
                    if (key == "voltage") { rsp.voltage = ::note::parse_double(raw); return; }
                }
            };

            void intern_strings(::note::StringPool&) {}

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            if (reset) b.add("reset", *reset);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    /// The `card.power` API is used to configure a connected Mojo device or to
    /// manually request power consumption readings in firmware.
    ///
    /// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
    struct Delete {
        static constexpr string_view notecard_request = "card.power";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Destructive;
        static constexpr Skus skus{ Rat::Cell | Rat::WiFi | Rat::Ntn };

        Notecard* nc_ = nullptr;

        /// How often, in minutes, Notecard should log power consumption in a
        /// `_log.qo` Note. The default value is `720` (12 hours).
        struct minutes_t : Field<note::Minutes> {
            using Field<note::Minutes>::Field;
            using Field<note::Minutes>::operator=;
            CardPower::Delete& operator()(note::Minutes v);
        } minutes{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        /// Response containing power consumption readings and environmental
        /// data from the Notecard.
        struct Response {
            /// The cumulative number of milliamp hours (mAh) consumed. You can
            /// reset this number with this request's `reset` argument.
            double milliampHours{};
            /// The temperature from Notecard's onboard sensor in degrees
            /// centigrade, including the calibration offset.
            double temperature{};
            /// The current voltage.
            double voltage{};

            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.milliampHours = reader_->get_double("milliamp_hours");
                rsp.temperature = reader_->get_double("temperature");
                rsp.voltage = reader_->get_double("voltage");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                rsp.milliampHours = reader_.get_double("milliamp_hours");
                rsp.temperature = reader_.get_double("temperature");
                rsp.voltage = reader_.get_double("voltage");
                return rsp;
            }

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are string_views into the JSON buffer; caller must
            // ensure the buffer outlives the Response (or intern strings after).
            struct Sink : ::note::JsonSink {
                Response& rsp;
                explicit Sink(Response& r) : rsp(r) {}
                void on_number(::note::string_view key, ::note::string_view raw) override {
                    if (key == "milliamp_hours") { rsp.milliampHours = ::note::parse_double(raw); return; }
                    if (key == "temperature") { rsp.temperature = ::note::parse_double(raw); return; }
                    if (key == "voltage") { rsp.voltage = ::note::parse_double(raw); return; }
                }
            };

            void intern_strings(::note::StringPool&) {}

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            b.add("reset", true);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };
};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardPower::Get& CardPower::Get::minutes_t::operator()(note::Minutes v) {
    Field<note::Minutes>::operator=(v);
    return *reinterpret_cast<CardPower::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardPower::Get, minutes));
}
inline CardPower::Get& CardPower::Get::reset_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardPower::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardPower::Get, reset));
}
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardPower::Set& CardPower::Set::minutes_t::operator()(note::Minutes v) {
    Field<note::Minutes>::operator=(v);
    return *reinterpret_cast<CardPower::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardPower::Set, minutes));
}
inline CardPower::Set& CardPower::Set::reset_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardPower::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardPower::Set, reset));
}
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardPower::Delete& CardPower::Delete::minutes_t::operator()(note::Minutes v) {
    Field<note::Minutes>::operator=(v);
    return *reinterpret_cast<CardPower::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardPower::Delete, minutes));
}
#pragma GCC diagnostic pop


} // namespace note::api
