#!/usr/bin/env bash
# Re-create test_units_*/ include-shim files from groups.tsv.
#
# Run after editing groups.tsv to rebalance which portable test files
# go in which PIO test group. Idempotent — drops stale entries under
# test_units_*/ that aren't in the manifest, then writes/replaces all
# entries from the manifest. Files at test/ top-level (main.cpp,
# test_custom_runner.py, this script) and test_fixtures/ are untouched.
#
# Each entry is a thin .cpp file containing a single `#include` of the
# real test source at tests/<file>. This keeps Windows checkouts happy
# (no symlinks — Arduino Library Manager rejects them) while keeping
# the real test sources in one place at tests/.
#
# Usage:  ./sync_groups.sh

set -euo pipefail
cd "$(dirname "$0")"

MANIFEST=groups.tsv

# Clean stale entries under test_units_*/ — anything not in the manifest.
for dir in test_units_*/; do
    [ -d "$dir" ] || continue
    for f in "$dir"*.cpp; do
        [ -e "$f" ] || continue
        base=$(basename "$f")
        group=${dir%/}
        group=${group#test_}  # strip "test_" prefix; e.g. "test_units_a" -> "units_a"
        if ! awk -v g="$group" -v b="$base" '$1==g && $2==b {found=1} END {exit !found}' "$MANIFEST"; then
            rm -f "$f"
        fi
    done
done

# Create include-shim .cpp files per manifest.
declare -A seen_groups=()
while IFS=$'\t' read -r group file; do
    case "$group" in ''|';'*) continue ;; esac  # skip blank/comment lines
    seen_groups[$group]=1
    mkdir -p "test_$group"
    # Overwrite (removes any pre-existing symlink) and write the include shim.
    rm -f "test_$group/$file"
    printf '// Auto-generated by sync_groups.sh — do not edit.\n// Include-shim: the real test lives at tests/%s.\n#include "../../../../%s"\n' "$file" "$file" > "test_$group/$file"
done < "$MANIFEST"

# Report.
echo "Synced include-shim files for groups: ${!seen_groups[*]}"
for group in "${!seen_groups[@]}"; do
    n=$(ls -1 "test_$group/"*.cpp 2>/dev/null | wc -l | tr -d ' ')
    echo "  test_$group/: $n files"
done
