// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/target.hpp>

namespace note::api {







/// Can be used to override the Notecard's I2C address from its default of
/// `0x17` and change behaviors of the onboard LED and USB port.
struct CardIo {
    static constexpr string_view notecard_request = "card.io";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr Skus skus{};

    Notecard* nc_ = nullptr;

    /// The alternate address to use for I2C communication.
    struct i2c_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        CardIo& operator()(int32_t v);
    } i2c{};
    /// Used to control the Notecard's IO behavior, including USB port, LED, I2C
    /// master, NTN fallback.
    // mode: -1 | -usb | usb | +usb | +busy | -busy | i2c-master-disable | i2c-master-enable | +fallback | -fallback
    struct mode_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        CardIo& operator()(note::string_view v);
    } mode{};

    // Valid values for 'mode':
    //   "-1" — Send `-1` to [reset](https://dev.blues.io/notecard/notecard-walkthrou...
    //   "-usb" — Set to `"-usb"` to disable the Notecard's USB port. Re-enable the USB...
    //   "usb" — Re-enable the Notecard's USB port after it has been disabled with `"-usb"`.
    //   "+usb" — Re-enable the Notecard's USB port after it has been disabled with `"-usb"`.
    //   "+busy" — If set to `"+busy"`, the Notecard's LED will be on when the Notecard ...
    //   "-busy" — Resets `"+busy"` to its default, making the onboard LED blink only du...
    //   "i2c-master-disable" — Disables Notecard acting as an I2C master. Re-enable by using `"i2c-m...
    //   "i2c-master-enable" — Re-enables the Notecard to act as an I2C master after it has been dis...
    //   "+fallback" — Setting `"+fallback"` while Notecard is paired with a Starnote device...
    //   "-fallback" — Resets `"+fallback"` to its default state, ensuring fallback mode is ...
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMode(const char* v) {
        note::string_view sv{v};
        if (sv != "-1" && sv != "-usb" && sv != "usb" && sv != "+usb" && sv != "+busy" && sv != "-busy" && sv != "i2c-master-disable" && sv != "i2c-master-enable" && sv != "+fallback" && sv != "-fallback")
            throw "card.io: invalid value for 'mode'";
        return sv;
    }
#endif

    template<typename T>
    auto& extra(note::string_view key, T value) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {key, note::DynValue{value}};
        return *this;
    }
    auto& extra(note::string_view key, const char* value) {
        return extra(key, note::string_view{value});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "i2c") return note::dyn_field_for(i2c);
        if (k_ == "mode") return note::dyn_field_for(mode);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    using Response = void;

    void build(JsonBuilder& b) const {
        if (i2c) b.add("i2c", *i2c);
        if (mode) b.add("mode", *mode);
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardIo& CardIo::i2c_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardIo*>(
        reinterpret_cast<char*>(this) - offsetof(CardIo, i2c));
}
inline CardIo& CardIo::mode_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardIo*>(
        reinterpret_cast<char*>(this) - offsetof(CardIo, mode));
}
#pragma GCC diagnostic pop


} // namespace note::api
