// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {

struct CardSleep {
    static constexpr string_view notecard_request = "card.sleep";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;

    Notecard* nc_ = nullptr;

    // mode: accel | -accel
    Field<note::string_view> mode{};
    Field<bool> off{};
    Field<bool> on{};
    Field<int32_t> seconds{};

    static consteval note::string_view validated_mode(const char* v) {
        note::string_view sv{v};
        if (sv != "accel" && sv != "-accel")
            throw "card.sleep: invalid value for 'mode'";
        return sv;
    }
#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_mode(this auto&& self, note::string_view v) { self.mode = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_mode(note::string_view v) { mode = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_off(this auto&& self, bool v) { self.off = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_off(bool v) { off = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_on(this auto&& self, bool v) { self.on = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_on(bool v) { on = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_seconds(this auto&& self, int32_t v) { self.seconds = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_seconds(int32_t v) { seconds = v; return *this; }
#endif

    struct Response {
        note::string_view mode{};
        bool off{};
        bool on{};
        int32_t seconds{};

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.mode = reader_->get_string("mode");
            rsp.off = reader_->get_bool("off");
            rsp.on = reader_->get_bool("on");
            rsp.seconds = reader_->get_int("seconds");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

    private:
        std::unique_ptr<JsonReader> reader_;
    };

    void build(JsonBuilder& b) const {
        if (mode) b.add("mode", *mode);
        if (off) b.add("off", *off);
        if (on) b.add("on", *on);
        if (seconds) b.add("seconds", *seconds);
    }

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

} // namespace note::api
