// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/target.hpp>

namespace note::api {







/// View the last known network state, or customize the behavior of the modem.
/// Note: Be careful when using this mode with hardware not on hand as a mistake
/// may cause loss of network and Notehub access.
struct CardWireless {
    static constexpr string_view notecard_request = "card.wireless";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr Skus skus{ Rat::Cell | Rat::WiFi | Rat::Ntn };

    Notecard* nc_ = nullptr;

    /// Access Point Name (APN) when using an external SIM. Use `"-"` to reset
    /// to the Notecard default APN.
    struct apn_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        CardWireless& operator()(note::string_view v);
    } apn{};
    /// When using the `method` argument with `"dual-primary-secondary"` or
    /// `"dual-secondary-primary"`, this is the number of hours after which the
    /// Notecard will attempt to switch back to the preferred SIM.
    struct hours_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        CardWireless& operator()(int32_t v);
    } hours{};
    /// Used when configuring a Notecard to failover to a different SIM.
    // method: - | dual-primary-secondary | dual-secondary-primary | primary | secondary
    struct method_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        CardWireless& operator()(note::string_view v);
    } method{};
    /// Network scan mode. Must be one of:
    // mode: - | auto | m | nb | gprs
    struct mode_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        CardWireless& operator()(note::string_view v);
    } mode{};

    // Valid values for 'method':
    //   "-" — Resets the Notecard to the default method.
    //   "dual-primary-secondary" — Will attempt to register with the internal SIM first, then failover t...
    //   "dual-secondary-primary" — Will attempt to register with the external SIM first, then failover t...
    //   "primary" — Will exclusively use the internal SIM.
    //   "secondary" — Will exclusively use the external SIM.
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMethod(const char* v) {
        note::string_view sv{v};
        if (sv != "-" && sv != "dual-primary-secondary" && sv != "dual-secondary-primary" && sv != "primary" && sv != "secondary")
            throw "card.wireless: invalid value for 'method'";
        return sv;
    }
#endif
    // Valid values for 'mode':
    //   "-" — Reset to the default mode.
    //   "auto" — Perform automatic band scan mode (this is the default mode).
    //   "m" — Restrict the modem to Cat-M1 (applies exclusively to Narrowband Notec...
    //   "nb" — Restrict the modem to Cat-NB1 (applies exclusively to Narrowband Note...
    //   "gprs" — Restrict the modem to EGPRS (applies exclusively to Narrowband Noteca...
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMode(const char* v) {
        note::string_view sv{v};
        if (sv != "-" && sv != "auto" && sv != "m" && sv != "nb" && sv != "gprs")
            throw "card.wireless: invalid value for 'mode'";
        return sv;
    }
#endif

    template<typename T>
    auto& extra(note::string_view key, T value) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {key, note::DynValue{value}};
        return *this;
    }
    auto& extra(note::string_view key, const char* value) {
        return extra(key, note::string_view{value});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "apn") return note::dyn_field_for(apn);
        if (k_ == "hours") return note::dyn_field_for(hours);
        if (k_ == "method") return note::dyn_field_for(method);
        if (k_ == "mode") return note::dyn_field_for(mode);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    /// Response containing wireless connection status, signal quality
    /// information, and detailed modem/network data from the Notecard.
    struct Response {
        /// Number of bars of signal quality.
        int32_t count{};
        /// The current status of the wireless connection and modem.
        note::string_view status{};

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.count = reader_->get_int("count");
            rsp.status = reader_->get_string("status");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            rsp.count = reader_.get_int("count");
            rsp.status = reader_.get_string("status");
            return rsp;
        }

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are string_views into the JSON buffer; caller must
        // ensure the buffer outlives the Response (or intern strings after).
        struct Sink : ::note::JsonSink {
            Response& rsp;
            explicit Sink(Response& r) : rsp(r) {}
            void on_string(::note::string_view key, ::note::string_view val) override {
                if (key == "status") { rsp.status = val; return; }
            }
            void on_number(::note::string_view key, ::note::string_view raw) override {
                if (key == "count") { rsp.count = ::note::parse_int(raw); return; }
            }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!status.empty()) status = pool.intern(status);
        }

    private:
        std::unique_ptr<JsonReader> reader_;
    };

    void build(JsonBuilder& b) const {
        if (apn) b.add("apn", *apn);
        if (hours) b.add("hours", *hours);
        if (method) b.add("method", *method);
        if (mode) b.add("mode", *mode);
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardWireless& CardWireless::apn_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardWireless*>(
        reinterpret_cast<char*>(this) - offsetof(CardWireless, apn));
}
inline CardWireless& CardWireless::hours_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWireless*>(
        reinterpret_cast<char*>(this) - offsetof(CardWireless, hours));
}
inline CardWireless& CardWireless::method_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardWireless*>(
        reinterpret_cast<char*>(this) - offsetof(CardWireless, method));
}
inline CardWireless& CardWireless::mode_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardWireless*>(
        reinterpret_cast<char*>(this) - offsetof(CardWireless, mode));
}
#pragma GCC diagnostic pop


} // namespace note::api
