// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {







struct CardMotionMode {
    static constexpr string_view notecard_request = "card.motion.mode";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;

    Notecard* nc_ = nullptr;

    /// If `motion` is > 0, a [card.motion](/api-reference/notecard-api/card-
    /// requests#card-motion) request will return a `"mode"` of `"moving"` or
    /// `"stopped"`. The `motion` value is the threshold for how many motion
    /// events in a single bucket will trigger a motion status change.
    ///
    /// Learn how to configure this feature [in this guide](/guides-and-
    /// tutorials/notecard-guides/asset-tracking-with-gps/#wake-host-or-send-
    /// note-on-motion-status-change).
    struct motion_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        CardMotionMode& operator()(int32_t v);
    } motion{};
    /// Period for each bucket of movements to be accumulated when `minutes` is
    /// used with `card.motion`.
    struct seconds_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        CardMotionMode& operator()(int32_t v);
    } seconds{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 3, 1) || !defined(NOTE_API_STRICT)
    /// Used to set the accelerometer sample rate. The default sample rate of
    /// 1.6Hz could miss short-duration accelerations (e.g. bumps and jolts),
    /// and free fall detection may not work reliably with short falls. The
    /// penalty for increasing the sample rate to 25Hz is increased current
    /// consumption by ~1.5uA relative to the default `-1` setting.
    ///
    /// @since firmware 3.3.1
    // sensitivity: -1 | 0 | 1 | 2 | 3 | 4 | 5
#if NOTE_API_VERSION < NOTE_VERSION(3, 3, 1)
    [[deprecated("requires firmware >= 3.3.1")]]
#endif
    struct sensitivity_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        CardMotionMode& operator()(int32_t v);
    } sensitivity{};
#endif
    /// `true` to enable the Notecard accelerometer and start motion tracking.
    struct start_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        CardMotionMode& operator()(bool v);
    } start{};
    /// `true` to disable the Notecard accelerometer and stop motion tracking.
    struct stop_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        CardMotionMode& operator()(bool v);
    } stop{};

#if NOTE_API_VERSION >= NOTE_VERSION(3, 3, 1) || !defined(NOTE_API_STRICT)
    // consteval: only callable at compile time
    static consteval note::string_view validatedSensitivity(const char* v) {
        note::string_view sv{v};
        if (sv != "-1" && sv != "0" && sv != "1" && sv != "2" && sv != "3" && sv != "4" && sv != "5")
            throw "card.motion.mode: invalid value for 'sensitivity'";
        return sv;
    }
#endif

    template<typename T>
    auto& extra(note::string_view key, T value) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {key, note::DynValue{value}};
        return *this;
    }
    auto& extra(note::string_view key, const char* value) {
        return extra(key, note::string_view{value});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "motion") return note::dyn_field_for(motion);
        if (k_ == "seconds") return note::dyn_field_for(seconds);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 3, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "sensitivity") return note::dyn_field_for(sensitivity);
#endif
        if (k_ == "start") return note::dyn_field_for(start);
        if (k_ == "stop") return note::dyn_field_for(stop);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    struct Response {

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            (void)reader_;
            return {};
        }
    };

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    void build(JsonBuilder& b) const {
        if (motion) b.add("motion", *motion);
        if (seconds) b.add("seconds", *seconds);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 3, 1) || !defined(NOTE_API_STRICT)
        if (sensitivity) b.add("sensitivity", *sensitivity);
#endif
        if (start) b.add("start", *start);
        if (stop) b.add("stop", *stop);
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }
#pragma GCC diagnostic pop

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline CardMotionMode& CardMotionMode::motion_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardMotionMode*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionMode, motion));
}
inline CardMotionMode& CardMotionMode::seconds_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardMotionMode*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionMode, seconds));
}
#if NOTE_API_VERSION >= NOTE_VERSION(3, 3, 1) || !defined(NOTE_API_STRICT)
inline CardMotionMode& CardMotionMode::sensitivity_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardMotionMode*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionMode, sensitivity));
}
#endif
inline CardMotionMode& CardMotionMode::start_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardMotionMode*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionMode, start));
}
inline CardMotionMode& CardMotionMode::stop_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardMotionMode*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionMode, stop));
}
#pragma GCC diagnostic pop


} // namespace note::api
