// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {

struct CardTemp {

    struct Query {
        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::ReadOnly;

        Notecard* nc_ = nullptr;

        Field<int32_t> minutes{};
        Field<note::string_view> status{};
        Field<bool> stop{};
        Field<bool> sync{};

#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_minutes(this auto&& self, int32_t v) { self.minutes = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_minutes(int32_t v) { minutes = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_status(this auto&& self, note::string_view v) { self.status = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_status(note::string_view v) { status = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_stop(this auto&& self, bool v) { self.stop = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_stop(bool v) { stop = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_sync(this auto&& self, bool v) { self.sync = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_sync(bool v) { sync = v; return *this; }
#endif

        struct Response {
            double calibration{};
            double humidity{};
            double pressure{};
            double temperature{};
            bool usb{};
            double value{};
            double voltage{};

            static Response parse(const JsonReader& r) {
                Response rsp;
                rsp.calibration = r.get_double("calibration");
                rsp.humidity = r.get_double("humidity");
                rsp.pressure = r.get_double("pressure");
                rsp.temperature = r.get_double("temperature");
                rsp.usb = r.get_bool("usb");
                rsp.value = r.get_double("value");
                rsp.voltage = r.get_double("voltage");
                return rsp;
            }
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            if (status) b.add("status", *status);
            if (stop) b.add("stop", *stop);
            if (sync) b.add("sync", *sync);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    struct Set {
        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Idempotent;

        Notecard* nc_ = nullptr;

        Field<int32_t> minutes{};
        Field<note::string_view> status{};
        Field<bool> stop{};
        Field<bool> sync{};

#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_minutes(this auto&& self, int32_t v) { self.minutes = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_minutes(int32_t v) { minutes = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_status(this auto&& self, note::string_view v) { self.status = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_status(note::string_view v) { status = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_stop(this auto&& self, bool v) { self.stop = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_stop(bool v) { stop = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_sync(this auto&& self, bool v) { self.sync = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_sync(bool v) { sync = v; return *this; }
#endif

        struct Response {
            double calibration{};
            double humidity{};
            double pressure{};
            double temperature{};
            bool usb{};
            double value{};
            double voltage{};

            static Response parse(const JsonReader& r) {
                Response rsp;
                rsp.calibration = r.get_double("calibration");
                rsp.humidity = r.get_double("humidity");
                rsp.pressure = r.get_double("pressure");
                rsp.temperature = r.get_double("temperature");
                rsp.usb = r.get_bool("usb");
                rsp.value = r.get_double("value");
                rsp.voltage = r.get_double("voltage");
                return rsp;
            }
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            if (status) b.add("status", *status);
            if (stop) b.add("stop", *stop);
            if (sync) b.add("sync", *sync);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    struct Delete {
        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Destructive;

        Notecard* nc_ = nullptr;

        Field<int32_t> minutes{};
        Field<note::string_view> status{};
        Field<bool> sync{};

#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_minutes(this auto&& self, int32_t v) { self.minutes = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_minutes(int32_t v) { minutes = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_status(this auto&& self, note::string_view v) { self.status = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_status(note::string_view v) { status = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
        auto&& set_sync(this auto&& self, bool v) { self.sync = v; return std::forward<decltype(self)>(self); }
#else
        auto& set_sync(bool v) { sync = v; return *this; }
#endif

        struct Response {
            double calibration{};
            double humidity{};
            double pressure{};
            double temperature{};
            bool usb{};
            double value{};
            double voltage{};

            static Response parse(const JsonReader& r) {
                Response rsp;
                rsp.calibration = r.get_double("calibration");
                rsp.humidity = r.get_double("humidity");
                rsp.pressure = r.get_double("pressure");
                rsp.temperature = r.get_double("temperature");
                rsp.usb = r.get_bool("usb");
                rsp.value = r.get_double("value");
                rsp.voltage = r.get_double("voltage");
                return rsp;
            }
        };

        void build(JsonBuilder& b) const {
            if (minutes) b.add("minutes", *minutes);
            if (status) b.add("status", *status);
            b.add("stop", true);
            if (sync) b.add("sync", *sync);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };
};

} // namespace note::api
