// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {







struct CardWirelessPenalty {

    struct Get {
        static constexpr string_view notecard_request = "card.wireless.penalty";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::ReadOnly;

        Notecard* nc_ = nullptr;

        /// The number of minutes to add to successive retries. Used with the
        /// `set` argument to override the Network Registration Failure Penalty
        /// Box defaults.
        struct add_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Get& operator()(int32_t v);
        } add{};
        /// The maximum number of minutes that a device can be in a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct max_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Get& operator()(int32_t v);
        } max{};
        /// The number of minutes of the first retry interval of a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct min_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Get& operator()(int32_t v);
        } min{};
        /// The rate at which the penalty box time multiplier is increased over
        /// successive retries. Used with the `set` argument to override the
        /// Network Registration Failure Penalty Box defaults.
        struct rate_t : Field<double> {
            using Field<double>::Field;
            using Field<double>::operator=;
            CardWirelessPenalty::Get& operator()(double v);
        } rate{};
        /// Set to `true` to remove the Notecard from certain types of penalty
        /// boxes.
        struct reset_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardWirelessPenalty::Get& operator()(bool v);
        } reset{};
        /// Set to `true` to override the default settings of the [Network
        /// Registration Failure Penalty Box](/support/understanding-notecard-
        /// penalty-boxes/#network-registration-failure).
        struct set_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardWirelessPenalty::Get& operator()(bool v);
        } set{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "add") return note::dyn_field_for(add);
            if (k_ == "max") return note::dyn_field_for(max);
            if (k_ == "min") return note::dyn_field_for(min);
            if (k_ == "rate") return note::dyn_field_for(rate);
            if (k_ == "reset") return note::dyn_field_for(reset);
            if (k_ == "set") return note::dyn_field_for(set);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        struct Response {
            /// The number of consecutive network registration failures.
            int32_t count{};
            /// The time since the first network registration failure.
            int32_t minutes{};
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), the number of seconds until the
            /// penalty condition ends.
            ///
            /// @since firmware 4.1.1
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
            [[deprecated("requires firmware >= 4.1.1")]]
#endif
            int32_t seconds{};
#endif
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), this field provides the associated
            /// [Error and Status Codes](/support/notecard-error-and-status-
            /// codes/).
            note::string_view status{};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.count = reader_->get_int("count");
                rsp.minutes = reader_->get_int("minutes");
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
                rsp.seconds = reader_->get_int("seconds");
#endif
                rsp.status = reader_->get_string("status");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }
#pragma GCC diagnostic pop

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (add) b.add("add", *add);
            if (max) b.add("max", *max);
            if (min) b.add("min", *min);
            if (rate) b.add("rate", *rate);
            if (reset) b.add("reset", *reset);
            if (set) b.add("set", *set);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    struct Set {
        static constexpr string_view notecard_request = "card.wireless.penalty";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Idempotent;

        Notecard* nc_ = nullptr;

        /// The number of minutes to add to successive retries. Used with the
        /// `set` argument to override the Network Registration Failure Penalty
        /// Box defaults.
        struct add_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Set& operator()(int32_t v);
        } add{};
        /// The maximum number of minutes that a device can be in a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct max_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Set& operator()(int32_t v);
        } max{};
        /// The number of minutes of the first retry interval of a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct min_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Set& operator()(int32_t v);
        } min{};
        /// The rate at which the penalty box time multiplier is increased over
        /// successive retries. Used with the `set` argument to override the
        /// Network Registration Failure Penalty Box defaults.
        struct rate_t : Field<double> {
            using Field<double>::Field;
            using Field<double>::operator=;
            CardWirelessPenalty::Set& operator()(double v);
        } rate{};
        /// Set to `true` to remove the Notecard from certain types of penalty
        /// boxes.
        struct reset_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardWirelessPenalty::Set& operator()(bool v);
        } reset{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "add") return note::dyn_field_for(add);
            if (k_ == "max") return note::dyn_field_for(max);
            if (k_ == "min") return note::dyn_field_for(min);
            if (k_ == "rate") return note::dyn_field_for(rate);
            if (k_ == "reset") return note::dyn_field_for(reset);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        struct Response {
            /// The number of consecutive network registration failures.
            int32_t count{};
            /// The time since the first network registration failure.
            int32_t minutes{};
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), the number of seconds until the
            /// penalty condition ends.
            ///
            /// @since firmware 4.1.1
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
            [[deprecated("requires firmware >= 4.1.1")]]
#endif
            int32_t seconds{};
#endif
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), this field provides the associated
            /// [Error and Status Codes](/support/notecard-error-and-status-
            /// codes/).
            note::string_view status{};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.count = reader_->get_int("count");
                rsp.minutes = reader_->get_int("minutes");
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
                rsp.seconds = reader_->get_int("seconds");
#endif
                rsp.status = reader_->get_string("status");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }
#pragma GCC diagnostic pop

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (add) b.add("add", *add);
            if (max) b.add("max", *max);
            if (min) b.add("min", *min);
            if (rate) b.add("rate", *rate);
            if (reset) b.add("reset", *reset);
            b.add("set", true);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };

    struct Delete {
        static constexpr string_view notecard_request = "card.wireless.penalty";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Destructive;

        Notecard* nc_ = nullptr;

        /// The number of minutes to add to successive retries. Used with the
        /// `set` argument to override the Network Registration Failure Penalty
        /// Box defaults.
        struct add_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Delete& operator()(int32_t v);
        } add{};
        /// The maximum number of minutes that a device can be in a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct max_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Delete& operator()(int32_t v);
        } max{};
        /// The number of minutes of the first retry interval of a Network
        /// Registration Failure Penalty Box. Used with the `set` argument to
        /// override the Network Registration Failure Penalty Box defaults.
        struct min_t : Field<int32_t> {
            using Field<int32_t>::Field;
            using Field<int32_t>::operator=;
            CardWirelessPenalty::Delete& operator()(int32_t v);
        } min{};
        /// The rate at which the penalty box time multiplier is increased over
        /// successive retries. Used with the `set` argument to override the
        /// Network Registration Failure Penalty Box defaults.
        struct rate_t : Field<double> {
            using Field<double>::Field;
            using Field<double>::operator=;
            CardWirelessPenalty::Delete& operator()(double v);
        } rate{};
        /// Set to `true` to override the default settings of the [Network
        /// Registration Failure Penalty Box](/support/understanding-notecard-
        /// penalty-boxes/#network-registration-failure).
        struct set_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            CardWirelessPenalty::Delete& operator()(bool v);
        } set{};


        template<typename T>
        auto& extra(note::string_view key, T value) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {key, note::DynValue{value}};
            return *this;
        }
        auto& extra(note::string_view key, const char* value) {
            return extra(key, note::string_view{value});
        }

        note::DynField operator[](note::string_view k_) {
            if (k_ == "add") return note::dyn_field_for(add);
            if (k_ == "max") return note::dyn_field_for(max);
            if (k_ == "min") return note::dyn_field_for(min);
            if (k_ == "rate") return note::dyn_field_for(rate);
            if (k_ == "set") return note::dyn_field_for(set);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;

        struct Response {
            /// The number of consecutive network registration failures.
            int32_t count{};
            /// The time since the first network registration failure.
            int32_t minutes{};
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), the number of seconds until the
            /// penalty condition ends.
            ///
            /// @since firmware 4.1.1
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
            [[deprecated("requires firmware >= 4.1.1")]]
#endif
            int32_t seconds{};
#endif
            /// If the Notecard is in a [Penalty Box](/support/understanding-
            /// notecard-penalty-boxes/), this field provides the associated
            /// [Error and Status Codes](/support/notecard-error-and-status-
            /// codes/).
            note::string_view status{};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                rsp.count = reader_->get_int("count");
                rsp.minutes = reader_->get_int("minutes");
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
                rsp.seconds = reader_->get_int("seconds");
#endif
                rsp.status = reader_->get_string("status");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }
#pragma GCC diagnostic pop

        private:
            std::unique_ptr<JsonReader> reader_;
        };

        void build(JsonBuilder& b) const {
            if (add) b.add("add", *add);
            if (max) b.add("max", *max);
            if (min) b.add("min", *min);
            if (rate) b.add("rate", *rate);
            b.add("reset", true);
            if (set) b.add("set", *set);
            for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
                std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                           extras_[i_].value);
        }

        auto execute() const { return nc_->execute(*this); }
        auto execute(Notecard& nc) const { return nc.execute(*this); }
        Result<void> command() const { return nc_->command_typed(*this); }
        Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

    };
};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::add_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, add));
}
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::max_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, max));
}
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::min_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, min));
}
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::rate_t::operator()(double v) {
    Field<double>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, rate));
}
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::reset_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, reset));
}
inline CardWirelessPenalty::Get& CardWirelessPenalty::Get::set_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Get*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Get, set));
}
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardWirelessPenalty::Set& CardWirelessPenalty::Set::add_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Set, add));
}
inline CardWirelessPenalty::Set& CardWirelessPenalty::Set::max_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Set, max));
}
inline CardWirelessPenalty::Set& CardWirelessPenalty::Set::min_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Set, min));
}
inline CardWirelessPenalty::Set& CardWirelessPenalty::Set::rate_t::operator()(double v) {
    Field<double>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Set, rate));
}
inline CardWirelessPenalty::Set& CardWirelessPenalty::Set::reset_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Set*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Set, reset));
}
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardWirelessPenalty::Delete& CardWirelessPenalty::Delete::add_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Delete, add));
}
inline CardWirelessPenalty::Delete& CardWirelessPenalty::Delete::max_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Delete, max));
}
inline CardWirelessPenalty::Delete& CardWirelessPenalty::Delete::min_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Delete, min));
}
inline CardWirelessPenalty::Delete& CardWirelessPenalty::Delete::rate_t::operator()(double v) {
    Field<double>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Delete, rate));
}
inline CardWirelessPenalty::Delete& CardWirelessPenalty::Delete::set_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardWirelessPenalty::Delete*>(
        reinterpret_cast<char*>(this) - offsetof(CardWirelessPenalty::Delete, set));
}
#pragma GCC diagnostic pop


} // namespace note::api
