// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {

struct FileChanges {
    static constexpr string_view notecard_request = "file.changes";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;

    Notecard* nc_ = nullptr;

    Field<note::string_view> files{};
    Field<note::string_view> tracker{};

#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_files(this auto&& self, note::string_view v) { self.files = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_files(note::string_view v) { files = v; return *this; }
#endif
#if __cpp_explicit_this_parameter >= 202110L
    auto&& set_tracker(this auto&& self, note::string_view v) { self.tracker = v; return std::forward<decltype(self)>(self); }
#else
    auto& set_tracker(note::string_view v) { tracker = v; return *this; }
#endif

    struct Response {
        int32_t changes{};
        bool pending{};
        int32_t total{};

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.changes = reader_->get_int("changes");
            rsp.pending = reader_->get_bool("pending");
            rsp.total = reader_->get_int("total");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

    private:
        std::unique_ptr<JsonReader> reader_;
    };

    void build(JsonBuilder& b) const {
        if (files) b.add("files", *files);
        if (tracker) b.add("tracker", *tracker);
    }

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

} // namespace note::api
