// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/body.hpp>
#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/units.hpp>
#include <note/target.hpp>

namespace note::api {








/// Receive a Signal (a near-real-time Note) from Notehub.
///
/// This request checks for an inbound signal from Notehub. If it finds a
/// signal, this request returns the signal's body and deletes the signal. If
/// there are multiple signals to receive, this request reads and deletes
/// signals in FIFO (first in first out) order.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct HubSignal {
    static constexpr string_view notecard_request = "hub.signal";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::NonIdempotent;
    static constexpr Skus skus{ Rat::Cell | Rat::WiFi | Rat::Ntn };

    Notecard* nc_ = nullptr;

#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
    /// The number of seconds to wait before timing out the request.
    ///
    /// @since{5.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(5, 1, 1)
    [[deprecated("requires firmware >= 5.1.1")]]
#endif
    struct seconds_t : Field<note::Seconds> {
        using Field<note::Seconds>::Field;
        using Field<note::Seconds>::operator=;
        HubSignal& operator()(note::Seconds v);
    } seconds{};
#endif


    template<typename T>
    auto& extra(note::string_view key, T value) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {key, note::DynValue{value}};
        return *this;
    }
    auto& extra(note::string_view key, const char* value) {
        return extra(key, note::string_view{value});
    }

    note::DynField operator[](note::string_view k_) {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "seconds") return note::dyn_field_for(seconds);
#endif
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    /// Response containing a received signal from Notehub.
    struct Response {
        /// `true` if the Notecard is connected to Notehub.
        note::ResponseField<bool> connected{};
        /// The number of queued signals remaining.
        note::ResponseField<int32_t> signals{};

        const JsonReader* body() const { return body_.get(); }

        template<typename T>
        T bodyAs() const {
            if (body_) return parse_body_<T>(*body_);
            return T{};
        }

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.connected = reader_->get_bool("connected");
            rsp.signals = reader_->get_int("signals");
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            rsp.connected = reader_.get_bool("connected");
            rsp.signals = reader_.get_int("signals");
            rsp.body_ = reader_.get_object("body");
            return rsp;
        }

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are string_views into the JSON buffer; caller must
        // ensure the buffer outlives the Response (or intern strings after).
        struct Sink : ::note::JsonSink {
            Response& rsp;
            explicit Sink(Response& r) : rsp(r) {}
            void on_bool(::note::string_view key, bool val) override {
                if (key == "connected") { rsp.connected = val; return; }
            }
            void on_number(::note::string_view key, ::note::string_view raw) override {
                if (key == "signals") { rsp.signals = ::note::parse_int(raw); return; }
            }
        };

        void intern_strings(::note::StringPool&) {}

    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;

        template<typename T>
        static T parse_body_(const JsonReader& r) {
            if constexpr (detail::has_note_fields_trait<T>::value) {
                return ::note::parse<T>(r);
            }
#if __cplusplus >= 202002L
            else if constexpr (detail::ReflectableAggregate<T>) {
                return ::note::parse<T>(r);
            }
#endif
            else {
                (void)r;
                return T{};
            }
        }
    };

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    void build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (seconds) b.add("seconds", *seconds);
#endif
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }
#pragma GCC diagnostic pop

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
inline HubSignal& HubSignal::seconds_t::operator()(note::Seconds v) {
    Field<note::Seconds>::operator=(v);
    return *reinterpret_cast<HubSignal*>(
        reinterpret_cast<char*>(this) - offsetof(HubSignal, seconds));
}
#endif
#pragma GCC diagnostic pop


} // namespace note::api
