// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/body.hpp>
#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/notecard.hpp>
#include <note/safety.hpp>
#include <note/types.hpp>

namespace note::api {







struct HubSignal {
    static constexpr string_view notecard_request = "hub.signal";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::NonIdempotent;

    Notecard* nc_ = nullptr;

#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
    /// The number of seconds to wait before timing out the request.
    ///
    /// @since firmware 5.1.1
#if NOTE_API_VERSION < NOTE_VERSION(5, 1, 1)
    [[deprecated("requires firmware >= 5.1.1")]]
#endif
    struct seconds_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        HubSignal& operator()(int32_t v);
    } seconds{};
#endif


    template<typename T>
    auto& extra(note::string_view key, T value) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {key, note::DynValue{value}};
        return *this;
    }
    auto& extra(note::string_view key, const char* value) {
        return extra(key, note::string_view{value});
    }

    note::DynField operator[](note::string_view k_) {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "seconds") return note::dyn_field_for(seconds);
#endif
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    struct Response {
        /// `true` if the Notecard is connected to Notehub.
        bool connected{};
        /// The number of queued signals remaining.
        int32_t signals{};

        const JsonReader* body() const { return body_.get(); }

        template<typename T>
        T bodyAs() const {
            if (body_) return parse_body_<T>(*body_);
            return T{};
        }

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.connected = reader_->get_bool("connected");
            rsp.signals = reader_->get_int("signals");
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;

        template<typename T>
        static T parse_body_(const JsonReader& r) {
            if constexpr (detail::has_note_body_trait<T>::value) {
                return ::note::parse<T>(r);
            }
#if __cplusplus >= 202002L
            else if constexpr (detail::ReflectableAggregate<T>) {
                return ::note::parse<T>(r);
            }
#endif
            else {
                (void)r;
                return T{};
            }
        }
    };

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    void build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (seconds) b.add("seconds", *seconds);
#endif
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }
#pragma GCC diagnostic pop

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
inline HubSignal& HubSignal::seconds_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<HubSignal*>(
        reinterpret_cast<char*>(this) - offsetof(HubSignal, seconds));
}
#endif
#pragma GCC diagnostic pop


} // namespace note::api
