// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/body.hpp>
#include <note/dyn_field.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/notecard.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/target.hpp>

namespace note::api {








/// Performs a simple HTTP or HTTPS `POST` request against an external endpoint,
/// and returns the response to the Notecard.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct WebPost {
    static constexpr string_view notecard_request = "web.post";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::NonIdempotent;
    static constexpr Skus skus = Skus::from(Product::Cell, Product::CellWifi, Product::Skylo, Product::WiFi);

    struct BinaryBuffer {
        static constexpr Direction direction = Direction::Send;
    };

    Notecard* nc_ = nullptr;

#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
    /// If `true`, the Notecard performs the web request asynchronously, and
    /// returns control to the host without waiting for a response from Notehub.
    /// This argument only applies when the Notecard is in `continuous` mode and
    /// currently online.
    ///
    /// @since{5.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(5, 1, 1)
    [[deprecated("requires firmware >= 5.1.1")]]
#endif
    struct async_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        WebPost& operator()(bool v);
    } async{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
    /// If `true`, the Notecard will send all the data in the binary buffer to
    /// the specified proxy route in Notehub.
    ///
    /// Learn more in this guide on Sending and Receiving Large Binary Objects.
    ///
    /// @since{5.3.1}
#if NOTE_API_VERSION < NOTE_VERSION(5, 3, 1)
    [[deprecated("requires firmware >= 5.3.1")]]
#endif
    struct binary_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        WebPost& operator()(bool v);
    } binary{};
#endif
    /// The JSON body to send with the request.
    struct body_t : BodyValue {
        using BodyValue::BodyValue;
        WebPost& operator()(BodyValue v);
#if __cplusplus >= 202002L
        template<typename T> requires detail::BodySchema<T>
        WebPost& operator()(const T& v);
#endif
    } body{};
    /// The MIME type of the body or payload of the response. Default is
    /// `application/json`.
    struct content_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } content{};
    /// The name of a local-only Database Notefile (.dbx) where the response
    /// will be stored when the web request is executed as a queued web
    /// transaction (e.g. if the request is made when Notecard is not in
    /// continuous mode and not online). If `file` is not specified, queued web
    /// transaction responses are discarded. This argument is not used when the
    /// Notecard is in `continuous` mode and online, as responses in that case
    /// are returned directly to the host.
    struct file_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } file{};
    /// The maximum size of the response from the remote server, in bytes.
    /// Useful if a memory-constrained host wants to limit the response size.
    struct max_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        WebPost& operator()(int32_t v);
    } max{};
    /// A web URL endpoint relative to the host configured in the Proxy Route.
    /// URL parameters may be added to this argument as well (e.g.
    /// `/addReading?id=1`).
    struct name_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } name{};
    /// The unique Note ID within the local-only Database Notefile (.dbx)
    /// specified by the `file` argument (see above). Used with queued web
    /// transactions to identify a specific Note where the response will be
    /// stored.
    struct noteId_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } noteId{};
    /// When sending payload fragments, the number of bytes of the binary
    /// payload to offset from 0 when reassembling on the Notehub once all
    /// fragments have been received.
    struct offset_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        WebPost& operator()(int32_t v);
    } offset{};
    /// A base64-encoded binary payload. A `web.post` may have either a `body`
    /// or a `payload`, but may NOT have both. Be aware that Notehub will decode
    /// the payload as it is delivered to the endpoint.
    ///
    /// Learn more about sending large binary objects with the Notecard.
    struct payload_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } payload{};
    /// Alias for a Proxy Route in Notehub.
    struct route_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } route{};
    /// If specified, overrides the default 90 second timeout.
    struct seconds_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        WebPost& operator()(int32_t v);
    } seconds{};
    /// A 32-character hex-encoded MD5 sum of the payload or payload fragment.
    /// Used by Notehub to perform verification upon receipt.
    struct status_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        WebPost& operator()(note::string_view v);
    } status{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 2, 1) || !defined(NOTE_API_STRICT)
    /// When using the `application/octet-stream` content type, you may send
    /// large payloads to Notehub in fragments spanning several `web.post`
    /// requests by using `offset` (see above) and `total`. The `total` field
    /// indicates the total size, in bytes (10MB max), of the payload across all
    /// fragments.
    ///
    /// @since{3.2.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 2, 1)
    [[deprecated("requires firmware >= 3.2.1")]]
#endif
    struct total_t : Field<int32_t> {
        using Field<int32_t>::Field;
        using Field<int32_t>::operator=;
        WebPost& operator()(int32_t v);
    } total{};
#endif
    /// `true` to request verification from Notehub once the payload or payload
    /// fragment is received. Automatically set to `true` when `status` is
    /// supplied.
    struct verify_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        WebPost& operator()(bool v);
    } verify{};


    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "async") return note::dyn_field_for(async);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "binary") return note::dyn_field_for(binary);
#endif
        if (k_ == "content") return note::dyn_field_for(content);
        if (k_ == "file") return note::dyn_field_for(file);
        if (k_ == "max") return note::dyn_field_for(max);
        if (k_ == "name") return note::dyn_field_for(name);
        if (k_ == "note") return note::dyn_field_for(noteId);
        if (k_ == "offset") return note::dyn_field_for(offset);
        if (k_ == "payload") return note::dyn_field_for(payload);
        if (k_ == "route") return note::dyn_field_for(route);
        if (k_ == "seconds") return note::dyn_field_for(seconds);
        if (k_ == "status") return note::dyn_field_for(status);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 2, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "total") return note::dyn_field_for(total);
#endif
        if (k_ == "verify") return note::dyn_field_for(verify);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;

    /// Response containing the result of an HTTP or HTTPS POST request to an
    /// external endpoint.
    struct Response {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
        /// If the web transaction returns a binary payload, `cobs` is the size
        /// of the COBS-encoded payload (in bytes).
        ///
        /// @since{5.3.1}
#if NOTE_API_VERSION < NOTE_VERSION(5, 3, 1)
        [[deprecated("requires firmware >= 5.3.1")]]
#endif
        note::ResponseField<int32_t> cobs{};
#endif
        /// If the web transaction returns a binary payload, `length` is the
        /// size of the unencoded payload (in bytes).
        note::ResponseField<int32_t> length{};
        /// A base64-encoded binary payload from the external service, if any.
        /// The maximum response size from the service is 8192 bytes.
        note::ResponseField<note::string_view> payload{};
        /// The HTTP Status Code.
        note::ResponseField<int32_t> result{};
        /// If a `payload` is returned in the response, this is a 32-character
        /// hex-encoded MD5 sum of the payload or payload fragment. Useful for
        /// the host to check for any I2C/UART corruption.
        note::ResponseField<note::string_view> status{};

        const JsonReader* body() const { return body_.get(); }

        template<typename T>
        T bodyAs() const {
            if (body_) return parse_body_<T>(*body_);
            return T{};
        }

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
            rsp.cobs = reader_->get_int("cobs");
#endif
            rsp.length = reader_->get_int("length");
            rsp.payload = reader_->get_string("payload");
            rsp.result = reader_->get_int("result");
            rsp.status = reader_->get_string("status");
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }
#pragma GCC diagnostic pop

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        static Response parse(const JsonReader& reader_) {
            Response rsp;
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
            rsp.cobs = reader_.get_int("cobs");
#endif
            rsp.length = reader_.get_int("length");
            rsp.payload = reader_.get_string("payload");
            rsp.result = reader_.get_int("result");
            rsp.status = reader_.get_string("status");
            rsp.body_ = reader_.get_object("body");
            return rsp;
        }
#pragma GCC diagnostic pop

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are string_views into the JSON buffer; caller must
        // ensure the buffer outlives the Response (or intern strings after).
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        struct Sink : ::note::JsonSink {
            Response& rsp;
            explicit Sink(Response& r) : rsp(r) {}
            void on_string(::note::string_view k_, ::note::string_view v_) override {
                if (k_ == "payload") { rsp.payload = v_; return; }
                if (k_ == "status") { rsp.status = v_; return; }
            }
            void on_number(::note::string_view k_, ::note::string_view raw_) override {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
                if (k_ == "cobs") { rsp.cobs = ::note::parse_int(raw_); return; }
#endif
                if (k_ == "length") { rsp.length = ::note::parse_int(raw_); return; }
                if (k_ == "result") { rsp.result = ::note::parse_int(raw_); return; }
            }
        };
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        void intern_strings(::note::StringPool& pool) {
            if (!payload.empty()) payload = pool.intern(payload);
            if (!status.empty()) status = pool.intern(status);
        }
#pragma GCC diagnostic pop

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"cobs\":");
            n += note::detail::print_json_value(p, cobs.value());
#endif
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"length\":");
            n += note::detail::print_json_value(p, length.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"payload\":");
            n += note::detail::print_json_value(p, payload.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"result\":");
            n += note::detail::print_json_value(p, result.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"status\":");
            n += note::detail::print_json_value(p, status.value());
            n += p.print("}");
            return n;
        }
#endif

    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;

        template<typename T>
        static T parse_body_(const JsonReader& r) {
            if constexpr (detail::has_note_fields_trait<T>::value) {
                return ::note::parse<T>(r);
            }
#if __cplusplus >= 202002L
            else if constexpr (detail::ReflectableAggregate<T>) {
                return ::note::parse<T>(r);
            }
#endif
            else {
                (void)r;
                return T{};
            }
        }
    };

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
    void build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (async) b.add("async", *async);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
        if (binary) b.add("binary", *binary);
#endif
        body.write_to(b);
        if (content) b.add("content", *content);
        if (file) b.add("file", *file);
        if (max) b.add("max", *max);
        if (name) b.add("name", *name);
        if (noteId) b.add("note", *noteId);
        if (offset) b.add("offset", *offset);
        if (payload) b.add("payload", *payload);
        if (route) b.add("route", *route);
        if (seconds) b.add("seconds", *seconds);
        if (status) b.add("status", *status);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 2, 1) || !defined(NOTE_API_STRICT)
        if (total) b.add("total", *total);
#endif
        if (verify) b.add("verify", *verify);
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
    }
#pragma GCC diagnostic pop

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
        if (async) {
            n += p.print(",\"async\":");
            n += note::detail::print_json_value(p, *async);
        }
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
        if (binary) {
            n += p.print(",\"binary\":");
            n += note::detail::print_json_value(p, *binary);
        }
#endif
        if (content) {
            n += p.print(",\"content\":");
            n += note::detail::print_json_value(p, *content);
        }
        if (file) {
            n += p.print(",\"file\":");
            n += note::detail::print_json_value(p, *file);
        }
        if (max) {
            n += p.print(",\"max\":");
            n += note::detail::print_json_value(p, *max);
        }
        if (name) {
            n += p.print(",\"name\":");
            n += note::detail::print_json_value(p, *name);
        }
        if (noteId) {
            n += p.print(",\"note\":");
            n += note::detail::print_json_value(p, *noteId);
        }
        if (offset) {
            n += p.print(",\"offset\":");
            n += note::detail::print_json_value(p, *offset);
        }
        if (payload) {
            n += p.print(",\"payload\":");
            n += note::detail::print_json_value(p, *payload);
        }
        if (route) {
            n += p.print(",\"route\":");
            n += note::detail::print_json_value(p, *route);
        }
        if (seconds) {
            n += p.print(",\"seconds\":");
            n += note::detail::print_json_value(p, *seconds);
        }
        if (status) {
            n += p.print(",\"status\":");
            n += note::detail::print_json_value(p, *status);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 2, 1) || !defined(NOTE_API_STRICT)
        if (total) {
            n += p.print(",\"total\":");
            n += note::detail::print_json_value(p, *total);
        }
#endif
        if (verify) {
            n += p.print(",\"verify\":");
            n += note::detail::print_json_value(p, *verify);
        }
        n += p.print("}");
        return n;
    }
#endif

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if NOTE_API_VERSION >= NOTE_VERSION(5, 1, 1) || !defined(NOTE_API_STRICT)
inline WebPost& WebPost::async_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, async));
}
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(5, 3, 1) || !defined(NOTE_API_STRICT)
inline WebPost& WebPost::binary_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, binary));
}
#endif
inline WebPost& WebPost::body_t::operator()(BodyValue v) {
    BodyValue::operator=(std::move(v));
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, body));
}
#if __cplusplus >= 202002L
template<typename T> requires detail::BodySchema<T>
inline WebPost& WebPost::body_t::operator()(const T& v) {
    BodyValue::operator=(make_schema_body(v));
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, body));
}
#endif
inline WebPost& WebPost::content_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, content));
}
inline WebPost& WebPost::file_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, file));
}
inline WebPost& WebPost::max_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, max));
}
inline WebPost& WebPost::name_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, name));
}
inline WebPost& WebPost::noteId_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, noteId));
}
inline WebPost& WebPost::offset_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, offset));
}
inline WebPost& WebPost::payload_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, payload));
}
inline WebPost& WebPost::route_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, route));
}
inline WebPost& WebPost::seconds_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, seconds));
}
inline WebPost& WebPost::status_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, status));
}
#if NOTE_API_VERSION >= NOTE_VERSION(3, 2, 1) || !defined(NOTE_API_STRICT)
inline WebPost& WebPost::total_t::operator()(int32_t v) {
    Field<int32_t>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, total));
}
#endif
inline WebPost& WebPost::verify_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<WebPost*>(
        reinterpret_cast<char*>(this) - offsetof(WebPost, verify));
}
#pragma GCC diagnostic pop


} // namespace note::api
