// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Obtain a single random 32 bit unsigned integer modulo or `count` number of
/// bytes of random data from the Notecard hardware random number generator.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct CardRandom {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "card.random";
        static constexpr char count[] NOTE_FLASH_ATTR = "count";
        static constexpr char mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char rsp_count[] NOTE_FLASH_ATTR = "count";
        static constexpr char rsp_payload[] NOTE_FLASH_ATTR = "payload";
    };

    static constexpr string_view notecard_request = "card.random";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;
    static constexpr RadiosSupport radios = RadiosSupport::from(Radios::Cell, Radios::CellWifi, Radios::Skylo, Radios::WiFi);
    static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// If the `mode` argument is excluded from the request, the Notecard uses
    /// this as an upper-limit parameter and returns a random unsigned 32 bit
    /// integer between zero and the value provided.
    ///
    /// If `"mode":"payload"` is used, this argument sets the number of random
    /// bytes of data to return in a base64-encoded buffer from the Notecard.
    struct count_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// If the `mode` argument is excluded from the request, the Notecard
        /// uses this as an upper-limit parameter and returns a random unsigned
        /// 32 bit integer between zero and the value provided.
        ///
        /// If `"mode":"payload"` is used, this argument sets the number of
        /// random bytes of data to return in a base64-encoded buffer from the
        /// Notecard.
        CardRandom& operator()(note::json_int_t v);
    } count{};
    /// Accepts a single value `"payload"` and, if specified, uses the `count`
    /// value to determine the number of bytes of random data to generate and
    /// return to the host.
    struct mode_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// Accepts a single value `"payload"` and, if specified, uses the
        /// `count` value to determine the number of bytes of random data to
        /// generate and return to the host.
        CardRandom& operator()(note::string_view v);
    } mode{};


#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "count") return note::dyn_field_for(count);
        if (k_ == "mode") return note::dyn_field_for(mode);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response containing random number or random data generated by the
    /// Notecard's hardware random number generator.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(257) +
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

        /// A random number generated by the Notecard's onboard hardware random
        /// number generator.
        note::ResponseField<note::json_int_t> count{};
        /// If using `"mode":"payload"`, a base64-encoded string with random
        /// values, the length of which is specified by the `count` argument.
        note::ResponseField<note::string_view> payload{};

#if !NOTE_NO_JSON_TREE
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            if (reader_->has("count")) rsp.count = reader_->get_int("count");
            if (reader_->has("payload")) rsp.payload = reader_->get_string("payload");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            if (reader_.has("count")) rsp.count = reader_.get_int("count");
            if (reader_.has("payload")) rsp.payload = reader_.get_string("payload");
            return rsp;
        }
#endif // !NOTE_NO_JSON_TREE

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
            }
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_payload) == k_) { rsp.payload = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                if (note::flash(keys_::rsp_count) == k_) { rsp.count = ::note::parse_int(raw_); return; }
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, ::note::json_int_t v_) {
                if (note::flash(keys_::rsp_count) == k_) { rsp.count = v_; return; }
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!payload.empty()) payload = pool.intern(payload);
        }

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"count\":");
            n += note::detail::print_json_value(p, count.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"payload\":");
            n += note::detail::print_json_value(p, payload.value());
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_JSON_TREE
    private:
        std::unique_ptr<JsonReader> reader_;
#endif
    };

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<Response> — boolean-convertible to true on success;
    /// dereference (or use member-of-pointer ->) to read response fields,
    /// or call .error() to inspect the ErrorInfo on failure.
    ApiResult<Response> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const CardRandom&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (count) {
            n += p.print(",\"count\":");
            n += note::detail::print_json_value(p, *count);
        }
        if (mode) {
            n += p.print(",\"mode\":");
            n += note::detail::print_json_value(p, *mode);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardRandom& CardRandom::count_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardRandom*>(
        reinterpret_cast<char*>(this) - offsetof(CardRandom, count));
}
inline CardRandom& CardRandom::mode_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardRandom*>(
        reinterpret_cast<char*>(this) - offsetof(CardRandom, mode));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::CardRandom> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::CardRandom::keys_::rsp_count, static_cast<uint16_t>(offsetof(::note::api::CardRandom::Response, count)), ::note::FieldType::Int},
        {::note::api::CardRandom::keys_::rsp_payload, static_cast<uint16_t>(offsetof(::note::api::CardRandom::Response, payload)), ::note::FieldType::String},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::CardRandom::keys_::count, static_cast<uint16_t>(offsetof(::note::api::CardRandom, count)), ::note::ReqFieldType::Int},
            {::note::api::CardRandom::keys_::mode, static_cast<uint16_t>(offsetof(::note::api::CardRandom, mode)), ::note::ReqFieldType::String},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void CardRandom::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<CardRandom>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename CardRandom::Response> CardRandom::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<CardRandom>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> CardRandom::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<CardRandom>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
