// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Used along with the card.aux API to turn connected LEDs on/off, to enable a
/// specific color on an RGB LED, or to manage a single connected NeoPixel.
///
/// Monochromatic LEDs must be wired according to the instructions provided in
/// the guide on Using Monitor Mode. Please note that the use of monochromatic
/// LEDs is not supported by Notecard for LoRa.
///
/// RGB LEDs must be wired according to the instructions provided in the guide
/// on Using RGB-Monitor Mode. Please note that the use of RGB LEDs is not
/// supported by Notecard for LoRa.
///
/// NeoPixels must be wired according to the instructions provided in the guide
/// on Using Neo-Monitor Mode.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct CardLed {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "card.led";
        static constexpr char mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char off[] NOTE_FLASH_ATTR = "off";
        static constexpr char on[] NOTE_FLASH_ATTR = "on";
    };

    static constexpr string_view notecard_request = "card.led";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios{};
    static constexpr Firmware min_firmware = Firmware{3, 5, 1};

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif


    /// Used to specify the color of the LED to turn on or off.
    ///
    /// Note: Notecard LoRa does not support monochromatic LED or RGB modes,
    /// only NeoPixels.
    // mode: red | green | yellow | blue | cyan | magenta | orange | white | gray
    struct mode_t : Field<note::string_view> {
#if __cplusplus >= 202002L && !defined(__clang__)
        constexpr mode_t() = default;
        template<std::size_t N>
        consteval mode_t(const char (&s)[N])
            : Field<note::string_view>(note::string_view(s, N - 1)) {
            note::string_view sv(s, N - 1);
            if (sv != "red" && sv != "green" && sv != "yellow" && sv != "blue" && sv != "cyan" && sv != "magenta" && sv != "orange" && sv != "white" && sv != "gray")
                throw "card.led: invalid value for 'mode'";
        }
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, mode_t>)
        constexpr mode_t(U&& v) : Field<note::string_view>(note::string_view(std::forward<U>(v))) {}
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, mode_t>)
        mode_t& operator=(U&& v) {
            Field<note::string_view>::operator=(note::string_view(std::forward<U>(v)));
            return *this;
        }
        mode_t& operator=(std::nullopt_t) { Field<note::string_view>::reset(); return *this; }
        mode_t(const mode_t&) = default;
        mode_t& operator=(const mode_t&) = default;
        mode_t(mode_t&&) = default;
        mode_t& operator=(mode_t&&) = default;
#else
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
#endif
        static constexpr note::string_view red{"red"};
        static constexpr note::string_view green{"green"};
        static constexpr note::string_view yellow{"yellow"};
        static constexpr note::string_view blue{"blue"};
        static constexpr note::string_view cyan{"cyan"};
        static constexpr note::string_view magenta{"magenta"};
        static constexpr note::string_view orange{"orange"};
        static constexpr note::string_view white{"white"};
        static constexpr note::string_view gray{"gray"};
        /// Used to specify the color of the LED to turn on or off.
        ///
        /// Note: Notecard LoRa does not support monochromatic LED or RGB modes,
        /// only NeoPixels.
        CardLed& operator()(note::string_view v);
    } mode{};
    /// Set to `true` to turn the specified LED or NeoPixel off.
    struct off_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to turn the specified LED or NeoPixel off.
        CardLed& operator()(bool v);
    } off{};
    /// Set to `true` to turn the specified LED or NeoPixel on.
    struct on_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to turn the specified LED or NeoPixel on.
        CardLed& operator()(bool v);
    } on{};

    // Valid values for 'mode':
    //   "red" — Supports **LED**, **RGB**, & **NeoPixel**
    //   "green" — Supports **LED**, **RGB**, & **NeoPixel**
    //   "yellow" — Supports **LED**, **RGB**, & **NeoPixel**
    //   "blue" — Supports **RGB** & **NeoPixel**
    //   "cyan" — Supports **RGB** & **NeoPixel**
    //   "magenta" — Supports **RGB** & **NeoPixel**
    //   "orange" — Supports **NeoPixel**
    //   "white" — Supports **RGB** & **NeoPixel**
    //   "gray" — Supports **NeoPixel**
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMode(const char* v) {
        note::string_view sv{v};
        if (sv != "red" && sv != "green" && sv != "yellow" && sv != "blue" && sv != "cyan" && sv != "magenta" && sv != "orange" && sv != "white" && sv != "gray")
            throw "card.led: invalid value for 'mode'";
        return sv;
    }
#endif

    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
    auto& turnOn() { on = true; return *this; }
    auto& turnOff() { off = true; return *this; }
    auto& turnOn(bool v_) { if (v_) on = true; else off = true; return *this; }
#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "mode") return note::dyn_field_for(mode);
        if (k_ == "off") return note::dyn_field_for(off);
        if (k_ == "on") return note::dyn_field_for(on);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

#if NOTE_SINGLETON
    private:
    /// Singleton void execute — shared thunk, no per-type instantiation.
    static inline Result<void>(*execute_void_fn_)(void*, ::note::string_view, BuildFn, void*, ::note::detail::NcErrorCapture&, ::note::Safety);
    public:
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<void> — boolean-convertible to true on success;
    /// call .error() to inspect the ErrorInfo on failure.
    ApiResult<void> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        ::note::detail::NcErrorCapture nc_err_;
        auto rv_ = execute_void_fn_(nc_, notecard_request, fn_, &build_, nc_err_, safety);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<void>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        return ApiResult<void>{};
    }
    private:
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
    public:
#else
    ApiResult<Response>(*execute_fn_)(void*, const CardLed&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (mode) {
            n += p.print(",\"mode\":");
            n += note::detail::print_json_value(p, *mode);
        }
        if (off) {
            n += p.print(",\"off\":");
            n += note::detail::print_json_value(p, *off);
        }
        if (on) {
            n += p.print(",\"on\":");
            n += note::detail::print_json_value(p, *on);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardLed& CardLed::mode_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardLed*>(
        reinterpret_cast<char*>(this) - offsetof(CardLed, mode));
}
inline CardLed& CardLed::off_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardLed*>(
        reinterpret_cast<char*>(this) - offsetof(CardLed, off));
}
inline CardLed& CardLed::on_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardLed*>(
        reinterpret_cast<char*>(this) - offsetof(CardLed, on));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::CardLed> {
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::CardLed::keys_::mode, static_cast<uint16_t>(offsetof(::note::api::CardLed, mode)), ::note::ReqFieldType::String},
            {::note::api::CardLed::keys_::off, static_cast<uint16_t>(offsetof(::note::api::CardLed, off)), ::note::ReqFieldType::Bool},
            {::note::api::CardLed::keys_::on, static_cast<uint16_t>(offsetof(::note::api::CardLed, on)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
};
} // namespace note::detail
namespace note::api {

inline void CardLed::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<CardLed>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}



} // namespace note::api
