// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/response_release.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Get the current temperature from the Notecard's onboard calibrated
/// temperature sensor.
///
/// When using a Notecard Cellular or Notecard Cell+WiFi, if you connect a
/// BME280 sensor on the I2C bus the Notecard will add `temperature`,
/// `pressure`, and `humidity` fields to the response. If you connect an ENS210
/// sensor on the I2C bus the Notecard will add `temperature` and `pressure`
/// fields to the response.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct CardTemp {

    struct Read {
        struct keys_ {
            static constexpr char req[] NOTE_FLASH_ATTR = "card.temp";
            static constexpr char minutes[] NOTE_FLASH_ATTR = "minutes";
            static constexpr char status[] NOTE_FLASH_ATTR = "status";
            static constexpr char stop[] NOTE_FLASH_ATTR = "stop";
            static constexpr char sync[] NOTE_FLASH_ATTR = "sync";
            static constexpr char rsp_calibration[] NOTE_FLASH_ATTR = "calibration";
            static constexpr char rsp_humidity[] NOTE_FLASH_ATTR = "humidity";
            static constexpr char rsp_pressure[] NOTE_FLASH_ATTR = "pressure";
            static constexpr char rsp_temperature[] NOTE_FLASH_ATTR = "temperature";
            static constexpr char rsp_value[] NOTE_FLASH_ATTR = "value";
            static constexpr char rsp_voltage[] NOTE_FLASH_ATTR = "voltage";
            static constexpr char rsp_usb[] NOTE_FLASH_ATTR = "usb";
        };

        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::ReadOnly;
        static constexpr RadiosSupport radios{};
        static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
        void* nc_ = nullptr;
#endif


        /// If specified, creates a templated `_temp.qo` file that gathers
        /// Notecard temperature value at the specified minutes interval. When
        /// using card.aux track mode, the sensor temperature, pressure, and
        /// humidity is also included with each Note.
        struct minutes_t : Field<note::json_int_t> {
            using Field<note::json_int_t>::Field;
            using Field<note::json_int_t>::operator=;
            /// If specified, creates a templated `_temp.qo` file that gathers
            /// Notecard temperature value at the specified minutes interval.
            /// When using card.aux track mode, the sensor temperature,
            /// pressure, and humidity is also included with each Note.
            CardTemp::Read& operator()(note::json_int_t v);
        } minutes{};
        /// Overrides `minutes` with a voltage-variable value. For example:
        /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync Behavior
        /// for more information on configuring these values.
        struct status_t : Field<note::string_view> {
            using Field<note::string_view>::Field;
            using Field<note::string_view>::operator=;
            /// Overrides `minutes` with a voltage-variable value. For example:
            /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync
            /// Behavior for more information on configuring these values.
            CardTemp::Read& operator()(note::string_view v);
        } status{};
        /// If set to `true`, the Notecard will stop logging the temperature
        /// value at the interval specified with the `minutes` parameter (see
        /// above).
        struct stop_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            /// If set to `true`, the Notecard will stop logging the temperature
            /// value at the interval specified with the `minutes` parameter
            /// (see above).
            CardTemp::Read& operator()(bool v);
        } stop{};
        /// If set to `true`, the Notecard will immediately sync any pending
        /// `_temp.qo` Notes created with the `minutes` parameter (see above).
        struct sync_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            /// If set to `true`, the Notecard will immediately sync any pending
            /// `_temp.qo` Notes created with the `minutes` parameter (see
            /// above).
            CardTemp::Read& operator()(bool v);
        } sync{};


    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
        auto& stopLogging() { stop = true; return *this; }
        auto& stopLogging(bool v_) { stop = v_; return *this; }
#if NOTE_EXTRAS
        /// Add an arbitrary key/value pair to the request, beyond the typed fields
        /// declared above. Useful for fields the schema doesn't yet model.
        /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
        template<typename T>
        auto& extra(note::string_view k_, T v_) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {k_, note::DynValue{v_}};
            return *this;
        }
        /// String-literal overload of extra().
        auto& extra(note::string_view k_, const char* v_) {
            return extra(k_, note::string_view{v_});
        }

        /// Index-style access to fields by wire name. Returns a DynField proxy
        /// usable for assignment; unknown keys are added as extras (subject to
        /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (k_ == "status") return note::dyn_field_for(status);
            if (k_ == "stop") return note::dyn_field_for(stop);
            if (k_ == "sync") return note::dyn_field_for(sync);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

        /// Response containing temperature readings from the Notecard's onboard
        /// sensor and any connected I2C sensors.
        struct Response {
            /// Compile-time arena budget for this response type.
            static constexpr size_t max_arena_size =
                ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

            /// The calibration differential, in degrees centigrade, applied to
            /// the Notecard's onboard temperature sensor. This per-device
            /// offset is added to the raw sensor reading to produce `value`.
            note::ResponseField<double> calibration{};
            /// If the Notecard finds a BME280 sensor on the I2C bus, this field
            /// will be set to the humidity percentage value from the connected
            /// sensor.
            note::ResponseField<double> humidity{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the atmospheric pressure value from
            /// the connected sensor in Pascals.
            note::ResponseField<double> pressure{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the temperature value from the
            /// connected sensor in degrees centigrade.
            note::ResponseField<double> temperature{};
            /// The current temperature from the Notecard's onboard sensor in
            /// degrees centigrade, including the calibration offset.
            note::ResponseField<double> value{};
            /// The current voltage.
            note::ResponseField<double> voltage{};
            /// `true` if the Notecard is connected to USB power.
            note::ResponseField<bool> usb{};


#if !NOTE_NO_JSON_TREE
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                if (reader_->has("calibration")) rsp.calibration = reader_->get_double("calibration");
                if (reader_->has("humidity")) rsp.humidity = reader_->get_double("humidity");
                if (reader_->has("pressure")) rsp.pressure = reader_->get_double("pressure");
                if (reader_->has("temperature")) rsp.temperature = reader_->get_double("temperature");
                if (reader_->has("value")) rsp.value = reader_->get_double("value");
                if (reader_->has("voltage")) rsp.voltage = reader_->get_double("voltage");
                if (reader_->has("usb")) rsp.usb = reader_->get_bool("usb");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                if (reader_.has("calibration")) rsp.calibration = reader_.get_double("calibration");
                if (reader_.has("humidity")) rsp.humidity = reader_.get_double("humidity");
                if (reader_.has("pressure")) rsp.pressure = reader_.get_double("pressure");
                if (reader_.has("temperature")) rsp.temperature = reader_.get_double("temperature");
                if (reader_.has("value")) rsp.value = reader_.get_double("value");
                if (reader_.has("voltage")) rsp.voltage = reader_.get_double("voltage");
                if (reader_.has("usb")) rsp.usb = reader_.get_bool("usb");
                return rsp;
            }
#endif // !NOTE_NO_JSON_TREE

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are interned into the StringPool immediately, so
            // string_views survive after the parser's scratch buffer is reused.
            struct Sink : ::note::DefaultSink {
                Response& rsp;
                ::note::StringPool& pool_;
                Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
                }
                NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                    if (note::flash(keys_::rsp_usb) == k_) { rsp.usb = v_; return; }
                }
                NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = ::note::parse_double(raw_); return; }
                }
                NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = v_; return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = v_; return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = v_; return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = v_; return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = v_; return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = v_; return; }
                }
                NOTE_SINK_NOINLINE void reset() {
                    rsp = Response{};
                }
            };

            void intern_strings(::note::StringPool&) {}

#ifdef ARDUINO
            /// Arduino Printable: prints response fields to Serial or any Print stream.
            size_t printTo(Print& p) const {
                size_t n = p.print("{");
                bool first_ = true;
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"calibration\":");
                n += note::detail::print_json_value(p, calibration.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"humidity\":");
                n += note::detail::print_json_value(p, humidity.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"pressure\":");
                n += note::detail::print_json_value(p, pressure.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"temperature\":");
                n += note::detail::print_json_value(p, temperature.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"value\":");
                n += note::detail::print_json_value(p, value.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"voltage\":");
                n += note::detail::print_json_value(p, voltage.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"usb\":");
                n += note::detail::print_json_value(p, usb.value());
                n += p.print("}");
                return n;
            }
#endif

#if !NOTE_NO_JSON_TREE
        private:
            std::unique_ptr<JsonReader> reader_;
#endif
        };

#if NOTE_SINGLETON
        /// Send this request to the Notecard and wait for a response.
        /// Returns an ApiResult<Response> — boolean-convertible to true on success;
        /// dereference (or use member-of-pointer ->) to read response fields,
        /// or call .error() to inspect the ErrorInfo on failure.
        ApiResult<Response> execute() const;
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const;
#else
        ApiResult<Response>(*execute_fn_)(void*, const CardTemp::Read&) = nullptr;
        Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
        /// Send this request to the Notecard and wait for a response.
        auto execute() const { return execute_fn_(nc_, *this); }
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const {
            auto build_ = [&](JsonBuilder& b_) {
                b_.add("cmd", notecard_request);
                this->build(b_);
            };
            BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
                (*static_cast<decltype(build_)*>(p_))(b_);
            };
            return send_fn_(nc_, fn_, &build_);
        }
#endif

        private:
        void build(JsonBuilder& b) const;
        public:


#ifdef ARDUINO
        /// Arduino Printable: prints the JSON request to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{\"req\":\"");
            n += p.print(notecard_request.data());
            n += p.print("\"");
            if (minutes) {
                n += p.print(",\"minutes\":");
                n += note::detail::print_json_value(p, *minutes);
            }
            if (status) {
                n += p.print(",\"status\":");
                n += note::detail::print_json_value(p, *status);
            }
            if (stop) {
                n += p.print(",\"stop\":");
                n += note::detail::print_json_value(p, *stop);
            }
            if (sync) {
                n += p.print(",\"sync\":");
                n += note::detail::print_json_value(p, *sync);
            }
            n += p.print("}");
            return n;
        }
#endif

        private:
        friend class ::note::Notecard;
        template<typename, typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
        template<typename> friend class ::note::Api;
#else
        template<typename, typename> friend class ::note::Api;
#endif
        friend struct ::note::test::JsonbWireProbe;
        public:

    };
    using Get = Read;  // legacy alias

    /// Get the current temperature from the Notecard's onboard calibrated
    /// temperature sensor.
    ///
    /// When using a Notecard Cellular or Notecard Cell+WiFi, if you connect a
    /// BME280 sensor on the I2C bus the Notecard will add `temperature`,
    /// `pressure`, and `humidity` fields to the response. If you connect an
    /// ENS210 sensor on the I2C bus the Notecard will add `temperature` and
    /// `pressure` fields to the response.
    ///
    /// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
    struct Configure {
        struct keys_ {
            static constexpr char req[] NOTE_FLASH_ATTR = "card.temp";
            static constexpr char minutes[] NOTE_FLASH_ATTR = "minutes";
            static constexpr char status[] NOTE_FLASH_ATTR = "status";
            static constexpr char stop[] NOTE_FLASH_ATTR = "stop";
            static constexpr char sync[] NOTE_FLASH_ATTR = "sync";
            static constexpr char rsp_calibration[] NOTE_FLASH_ATTR = "calibration";
            static constexpr char rsp_humidity[] NOTE_FLASH_ATTR = "humidity";
            static constexpr char rsp_pressure[] NOTE_FLASH_ATTR = "pressure";
            static constexpr char rsp_temperature[] NOTE_FLASH_ATTR = "temperature";
            static constexpr char rsp_value[] NOTE_FLASH_ATTR = "value";
            static constexpr char rsp_voltage[] NOTE_FLASH_ATTR = "voltage";
            static constexpr char rsp_usb[] NOTE_FLASH_ATTR = "usb";
        };

        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Idempotent;
        static constexpr RadiosSupport radios{};
        static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
        void* nc_ = nullptr;
#endif


        /// If specified, creates a templated `_temp.qo` file that gathers
        /// Notecard temperature value at the specified minutes interval. When
        /// using card.aux track mode, the sensor temperature, pressure, and
        /// humidity is also included with each Note.
        struct minutes_t : Field<note::json_int_t> {
            using Field<note::json_int_t>::Field;
            using Field<note::json_int_t>::operator=;
            /// If specified, creates a templated `_temp.qo` file that gathers
            /// Notecard temperature value at the specified minutes interval.
            /// When using card.aux track mode, the sensor temperature,
            /// pressure, and humidity is also included with each Note.
            CardTemp::Configure& operator()(note::json_int_t v);
        } minutes{};
        /// Overrides `minutes` with a voltage-variable value. For example:
        /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync Behavior
        /// for more information on configuring these values.
        struct status_t : Field<note::string_view> {
            using Field<note::string_view>::Field;
            using Field<note::string_view>::operator=;
            /// Overrides `minutes` with a voltage-variable value. For example:
            /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync
            /// Behavior for more information on configuring these values.
            CardTemp::Configure& operator()(note::string_view v);
        } status{};
        /// If set to `true`, the Notecard will stop logging the temperature
        /// value at the interval specified with the `minutes` parameter (see
        /// above).
        struct stop_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            /// If set to `true`, the Notecard will stop logging the temperature
            /// value at the interval specified with the `minutes` parameter
            /// (see above).
            CardTemp::Configure& operator()(bool v);
        } stop{};
        /// If set to `true`, the Notecard will immediately sync any pending
        /// `_temp.qo` Notes created with the `minutes` parameter (see above).
        struct sync_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            /// If set to `true`, the Notecard will immediately sync any pending
            /// `_temp.qo` Notes created with the `minutes` parameter (see
            /// above).
            CardTemp::Configure& operator()(bool v);
        } sync{};


    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
        auto& stopLogging() { stop = true; return *this; }
        auto& stopLogging(bool v_) { stop = v_; return *this; }
#if NOTE_EXTRAS
        /// Add an arbitrary key/value pair to the request, beyond the typed fields
        /// declared above. Useful for fields the schema doesn't yet model.
        /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
        template<typename T>
        auto& extra(note::string_view k_, T v_) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {k_, note::DynValue{v_}};
            return *this;
        }
        /// String-literal overload of extra().
        auto& extra(note::string_view k_, const char* v_) {
            return extra(k_, note::string_view{v_});
        }

        /// Index-style access to fields by wire name. Returns a DynField proxy
        /// usable for assignment; unknown keys are added as extras (subject to
        /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (k_ == "status") return note::dyn_field_for(status);
            if (k_ == "stop") return note::dyn_field_for(stop);
            if (k_ == "sync") return note::dyn_field_for(sync);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

        /// Response containing temperature readings from the Notecard's onboard
        /// sensor and any connected I2C sensors.
        struct Response {
            /// Compile-time arena budget for this response type.
            static constexpr size_t max_arena_size =
                ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

            /// The calibration differential, in degrees centigrade, applied to
            /// the Notecard's onboard temperature sensor. This per-device
            /// offset is added to the raw sensor reading to produce `value`.
            note::ResponseField<double> calibration{};
            /// If the Notecard finds a BME280 sensor on the I2C bus, this field
            /// will be set to the humidity percentage value from the connected
            /// sensor.
            note::ResponseField<double> humidity{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the atmospheric pressure value from
            /// the connected sensor in Pascals.
            note::ResponseField<double> pressure{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the temperature value from the
            /// connected sensor in degrees centigrade.
            note::ResponseField<double> temperature{};
            /// The current temperature from the Notecard's onboard sensor in
            /// degrees centigrade, including the calibration offset.
            note::ResponseField<double> value{};
            /// The current voltage.
            note::ResponseField<double> voltage{};
            /// `true` if the Notecard is connected to USB power.
            note::ResponseField<bool> usb{};


#if !NOTE_NO_JSON_TREE
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                if (reader_->has("calibration")) rsp.calibration = reader_->get_double("calibration");
                if (reader_->has("humidity")) rsp.humidity = reader_->get_double("humidity");
                if (reader_->has("pressure")) rsp.pressure = reader_->get_double("pressure");
                if (reader_->has("temperature")) rsp.temperature = reader_->get_double("temperature");
                if (reader_->has("value")) rsp.value = reader_->get_double("value");
                if (reader_->has("voltage")) rsp.voltage = reader_->get_double("voltage");
                if (reader_->has("usb")) rsp.usb = reader_->get_bool("usb");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                if (reader_.has("calibration")) rsp.calibration = reader_.get_double("calibration");
                if (reader_.has("humidity")) rsp.humidity = reader_.get_double("humidity");
                if (reader_.has("pressure")) rsp.pressure = reader_.get_double("pressure");
                if (reader_.has("temperature")) rsp.temperature = reader_.get_double("temperature");
                if (reader_.has("value")) rsp.value = reader_.get_double("value");
                if (reader_.has("voltage")) rsp.voltage = reader_.get_double("voltage");
                if (reader_.has("usb")) rsp.usb = reader_.get_bool("usb");
                return rsp;
            }
#endif // !NOTE_NO_JSON_TREE

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are interned into the StringPool immediately, so
            // string_views survive after the parser's scratch buffer is reused.
            struct Sink : ::note::DefaultSink {
                Response& rsp;
                ::note::StringPool& pool_;
                Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
                }
                NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                    if (note::flash(keys_::rsp_usb) == k_) { rsp.usb = v_; return; }
                }
                NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = ::note::parse_double(raw_); return; }
                }
                NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = v_; return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = v_; return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = v_; return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = v_; return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = v_; return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = v_; return; }
                }
                NOTE_SINK_NOINLINE void reset() {
                    rsp = Response{};
                }
            };

            void intern_strings(::note::StringPool&) {}

#ifdef ARDUINO
            /// Arduino Printable: prints response fields to Serial or any Print stream.
            size_t printTo(Print& p) const {
                size_t n = p.print("{");
                bool first_ = true;
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"calibration\":");
                n += note::detail::print_json_value(p, calibration.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"humidity\":");
                n += note::detail::print_json_value(p, humidity.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"pressure\":");
                n += note::detail::print_json_value(p, pressure.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"temperature\":");
                n += note::detail::print_json_value(p, temperature.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"value\":");
                n += note::detail::print_json_value(p, value.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"voltage\":");
                n += note::detail::print_json_value(p, voltage.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"usb\":");
                n += note::detail::print_json_value(p, usb.value());
                n += p.print("}");
                return n;
            }
#endif

#if !NOTE_NO_JSON_TREE
        private:
            std::unique_ptr<JsonReader> reader_;
#endif
        };

#if NOTE_SINGLETON
        /// Send this request to the Notecard and wait for a response.
        /// Returns an ApiResult<Response> — boolean-convertible to true on success;
        /// dereference (or use member-of-pointer ->) to read response fields,
        /// or call .error() to inspect the ErrorInfo on failure.
        ApiResult<Response> execute() const;
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const;
#else
        ApiResult<Response>(*execute_fn_)(void*, const CardTemp::Configure&) = nullptr;
        Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
        /// Send this request to the Notecard and wait for a response.
        auto execute() const { return execute_fn_(nc_, *this); }
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const {
            auto build_ = [&](JsonBuilder& b_) {
                b_.add("cmd", notecard_request);
                this->build(b_);
            };
            BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
                (*static_cast<decltype(build_)*>(p_))(b_);
            };
            return send_fn_(nc_, fn_, &build_);
        }
#endif

        private:
        void build(JsonBuilder& b) const;
        public:


#ifdef ARDUINO
        /// Arduino Printable: prints the JSON request to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{\"req\":\"");
            n += p.print(notecard_request.data());
            n += p.print("\"");
            if (minutes) {
                n += p.print(",\"minutes\":");
                n += note::detail::print_json_value(p, *minutes);
            }
            if (status) {
                n += p.print(",\"status\":");
                n += note::detail::print_json_value(p, *status);
            }
            if (stop) {
                n += p.print(",\"stop\":");
                n += note::detail::print_json_value(p, *stop);
            }
            if (sync) {
                n += p.print(",\"sync\":");
                n += note::detail::print_json_value(p, *sync);
            }
            n += p.print("}");
            return n;
        }
#endif

        private:
        friend class ::note::Notecard;
        template<typename, typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
        template<typename> friend class ::note::Api;
#else
        template<typename, typename> friend class ::note::Api;
#endif
        friend struct ::note::test::JsonbWireProbe;
        public:

    };
    using Set = Configure;  // legacy alias

    /// Get the current temperature from the Notecard's onboard calibrated
    /// temperature sensor.
    ///
    /// When using a Notecard Cellular or Notecard Cell+WiFi, if you connect a
    /// BME280 sensor on the I2C bus the Notecard will add `temperature`,
    /// `pressure`, and `humidity` fields to the response. If you connect an
    /// ENS210 sensor on the I2C bus the Notecard will add `temperature` and
    /// `pressure` fields to the response.
    ///
    /// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
    struct Stop {
        struct keys_ {
            static constexpr char req[] NOTE_FLASH_ATTR = "card.temp";
            static constexpr char minutes[] NOTE_FLASH_ATTR = "minutes";
            static constexpr char status[] NOTE_FLASH_ATTR = "status";
            static constexpr char stop[] NOTE_FLASH_ATTR = "stop";
            static constexpr char sync[] NOTE_FLASH_ATTR = "sync";
            static constexpr char rsp_calibration[] NOTE_FLASH_ATTR = "calibration";
            static constexpr char rsp_humidity[] NOTE_FLASH_ATTR = "humidity";
            static constexpr char rsp_pressure[] NOTE_FLASH_ATTR = "pressure";
            static constexpr char rsp_temperature[] NOTE_FLASH_ATTR = "temperature";
            static constexpr char rsp_value[] NOTE_FLASH_ATTR = "value";
            static constexpr char rsp_voltage[] NOTE_FLASH_ATTR = "voltage";
            static constexpr char rsp_usb[] NOTE_FLASH_ATTR = "usb";
        };

        static constexpr string_view notecard_request = "card.temp";
        static constexpr bool supports_cmd = true;
        static constexpr Safety safety = Safety::Destructive;
        static constexpr RadiosSupport radios{};
        static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
        void* nc_ = nullptr;
#endif


        /// If specified, creates a templated `_temp.qo` file that gathers
        /// Notecard temperature value at the specified minutes interval. When
        /// using card.aux track mode, the sensor temperature, pressure, and
        /// humidity is also included with each Note.
        struct minutes_t : Field<note::json_int_t> {
            using Field<note::json_int_t>::Field;
            using Field<note::json_int_t>::operator=;
            /// If specified, creates a templated `_temp.qo` file that gathers
            /// Notecard temperature value at the specified minutes interval.
            /// When using card.aux track mode, the sensor temperature,
            /// pressure, and humidity is also included with each Note.
            CardTemp::Stop& operator()(note::json_int_t v);
        } minutes{};
        /// Overrides `minutes` with a voltage-variable value. For example:
        /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync Behavior
        /// for more information on configuring these values.
        struct status_t : Field<note::string_view> {
            using Field<note::string_view>::Field;
            using Field<note::string_view>::operator=;
            /// Overrides `minutes` with a voltage-variable value. For example:
            /// `"usb:15;high:30;normal:60;720"`. See Voltage-Variable Sync
            /// Behavior for more information on configuring these values.
            CardTemp::Stop& operator()(note::string_view v);
        } status{};
        /// If set to `true`, the Notecard will immediately sync any pending
        /// `_temp.qo` Notes created with the `minutes` parameter (see above).
        struct sync_t : Field<bool> {
            using Field<bool>::Field;
            using Field<bool>::operator=;
            /// If set to `true`, the Notecard will immediately sync any pending
            /// `_temp.qo` Notes created with the `minutes` parameter (see
            /// above).
            CardTemp::Stop& operator()(bool v);
        } sync{};


#if NOTE_EXTRAS
        /// Add an arbitrary key/value pair to the request, beyond the typed fields
        /// declared above. Useful for fields the schema doesn't yet model.
        /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
        template<typename T>
        auto& extra(note::string_view k_, T v_) {
            if (extras_count_ < NOTE_EXTRAS_MAX)
                extras_[extras_count_++] = {k_, note::DynValue{v_}};
            return *this;
        }
        /// String-literal overload of extra().
        auto& extra(note::string_view k_, const char* v_) {
            return extra(k_, note::string_view{v_});
        }

        /// Index-style access to fields by wire name. Returns a DynField proxy
        /// usable for assignment; unknown keys are added as extras (subject to
        /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
        note::DynField operator[](note::string_view k_) {
            if (k_ == "minutes") return note::dyn_field_for(minutes);
            if (k_ == "status") return note::dyn_field_for(status);
            if (k_ == "sync") return note::dyn_field_for(sync);
            if (extras_count_ < NOTE_EXTRAS_MAX) {
                auto& slot = extras_[extras_count_++];
                slot.key = k_;
                return note::dyn_field_for(slot.value);
            }
            return {};
        }

        std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
        uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

        /// Response containing temperature readings from the Notecard's onboard
        /// sensor and any connected I2C sensors.
        struct Response {
            /// Compile-time arena budget for this response type.
            static constexpr size_t max_arena_size =
                ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

            /// The calibration differential, in degrees centigrade, applied to
            /// the Notecard's onboard temperature sensor. This per-device
            /// offset is added to the raw sensor reading to produce `value`.
            note::ResponseField<double> calibration{};
            /// If the Notecard finds a BME280 sensor on the I2C bus, this field
            /// will be set to the humidity percentage value from the connected
            /// sensor.
            note::ResponseField<double> humidity{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the atmospheric pressure value from
            /// the connected sensor in Pascals.
            note::ResponseField<double> pressure{};
            /// If the Notecard finds a BME280 or ENS210 sensor on the I2C bus,
            /// this field will be set to the temperature value from the
            /// connected sensor in degrees centigrade.
            note::ResponseField<double> temperature{};
            /// The current temperature from the Notecard's onboard sensor in
            /// degrees centigrade, including the calibration offset.
            note::ResponseField<double> value{};
            /// The current voltage.
            note::ResponseField<double> voltage{};
            /// `true` if the Notecard is connected to USB power.
            note::ResponseField<bool> usb{};


#if !NOTE_NO_JSON_TREE
            static Response parse(std::unique_ptr<JsonReader> reader_) {
                Response rsp;
                if (reader_->has("calibration")) rsp.calibration = reader_->get_double("calibration");
                if (reader_->has("humidity")) rsp.humidity = reader_->get_double("humidity");
                if (reader_->has("pressure")) rsp.pressure = reader_->get_double("pressure");
                if (reader_->has("temperature")) rsp.temperature = reader_->get_double("temperature");
                if (reader_->has("value")) rsp.value = reader_->get_double("value");
                if (reader_->has("voltage")) rsp.voltage = reader_->get_double("voltage");
                if (reader_->has("usb")) rsp.usb = reader_->get_bool("usb");
                rsp.reader_ = std::move(reader_);
                return rsp;
            }

            // Non-owning parse: string_views point into the reader's data.
            // The reader (and its underlying JSON buffer) must outlive the Response,
            // or the caller must consume all string fields before the reader is reused.
            static Response parse(const JsonReader& reader_) {
                Response rsp;
                if (reader_.has("calibration")) rsp.calibration = reader_.get_double("calibration");
                if (reader_.has("humidity")) rsp.humidity = reader_.get_double("humidity");
                if (reader_.has("pressure")) rsp.pressure = reader_.get_double("pressure");
                if (reader_.has("temperature")) rsp.temperature = reader_.get_double("temperature");
                if (reader_.has("value")) rsp.value = reader_.get_double("value");
                if (reader_.has("voltage")) rsp.voltage = reader_.get_double("voltage");
                if (reader_.has("usb")) rsp.usb = reader_.get_bool("usb");
                return rsp;
            }
#endif // !NOTE_NO_JSON_TREE

            // SAX sink — zero-allocation streaming parse into Response fields.
            // String fields are interned into the StringPool immediately, so
            // string_views survive after the parser's scratch buffer is reused.
            struct Sink : ::note::DefaultSink {
                Response& rsp;
                ::note::StringPool& pool_;
                Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
                }
                NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                    if (note::flash(keys_::rsp_usb) == k_) { rsp.usb = v_; return; }
                }
                NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = ::note::parse_double(raw_); return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = ::note::parse_double(raw_); return; }
                }
                NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                    if (note::flash(keys_::rsp_calibration) == k_) { rsp.calibration = v_; return; }
                    if (note::flash(keys_::rsp_humidity) == k_) { rsp.humidity = v_; return; }
                    if (note::flash(keys_::rsp_pressure) == k_) { rsp.pressure = v_; return; }
                    if (note::flash(keys_::rsp_temperature) == k_) { rsp.temperature = v_; return; }
                    if (note::flash(keys_::rsp_value) == k_) { rsp.value = v_; return; }
                    if (note::flash(keys_::rsp_voltage) == k_) { rsp.voltage = v_; return; }
                }
                NOTE_SINK_NOINLINE void reset() {
                    rsp = Response{};
                }
            };

            void intern_strings(::note::StringPool&) {}

#ifdef ARDUINO
            /// Arduino Printable: prints response fields to Serial or any Print stream.
            size_t printTo(Print& p) const {
                size_t n = p.print("{");
                bool first_ = true;
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"calibration\":");
                n += note::detail::print_json_value(p, calibration.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"humidity\":");
                n += note::detail::print_json_value(p, humidity.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"pressure\":");
                n += note::detail::print_json_value(p, pressure.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"temperature\":");
                n += note::detail::print_json_value(p, temperature.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"value\":");
                n += note::detail::print_json_value(p, value.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"voltage\":");
                n += note::detail::print_json_value(p, voltage.value());
                if (!first_) n += p.print(",");
                first_ = false;
                n += p.print("\"usb\":");
                n += note::detail::print_json_value(p, usb.value());
                n += p.print("}");
                return n;
            }
#endif

#if !NOTE_NO_JSON_TREE
        private:
            std::unique_ptr<JsonReader> reader_;
#endif
        };

#if NOTE_SINGLETON
        /// Send this request to the Notecard and wait for a response.
        /// Returns an ApiResult<Response> — boolean-convertible to true on success;
        /// dereference (or use member-of-pointer ->) to read response fields,
        /// or call .error() to inspect the ErrorInfo on failure.
        ApiResult<Response> execute() const;
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const;
#else
        ApiResult<Response>(*execute_fn_)(void*, const CardTemp::Stop&) = nullptr;
        Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
        /// Send this request to the Notecard and wait for a response.
        auto execute() const { return execute_fn_(nc_, *this); }
        /// Send this request as a fire-and-forget command (cmd) — the Notecard
        /// processes it without sending a response. Lower power and bandwidth
        /// than execute() when you don't need the result.
        Result<void> command() const {
            auto build_ = [&](JsonBuilder& b_) {
                b_.add("cmd", notecard_request);
                this->build(b_);
            };
            BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
                (*static_cast<decltype(build_)*>(p_))(b_);
            };
            return send_fn_(nc_, fn_, &build_);
        }
#endif

        private:
        void build(JsonBuilder& b) const;
        public:


#ifdef ARDUINO
        /// Arduino Printable: prints the JSON request to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{\"req\":\"");
            n += p.print(notecard_request.data());
            n += p.print("\"");
            if (minutes) {
                n += p.print(",\"minutes\":");
                n += note::detail::print_json_value(p, *minutes);
            }
            if (status) {
                n += p.print(",\"status\":");
                n += note::detail::print_json_value(p, *status);
            }
            if (sync) {
                n += p.print(",\"sync\":");
                n += note::detail::print_json_value(p, *sync);
            }
            n += p.print("}");
            return n;
        }
#endif

        private:
        friend class ::note::Notecard;
        template<typename, typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
        template<typename> friend class ::note::Api;
#else
        template<typename, typename> friend class ::note::Api;
#endif
        friend struct ::note::test::JsonbWireProbe;
        public:

    };
    using Delete = Stop;  // legacy alias
};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardTemp::Read& CardTemp::Read::minutes_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardTemp::Read*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Read, minutes));
}
inline CardTemp::Read& CardTemp::Read::status_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardTemp::Read*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Read, status));
}
inline CardTemp::Read& CardTemp::Read::stop_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardTemp::Read*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Read, stop));
}
inline CardTemp::Read& CardTemp::Read::sync_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardTemp::Read*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Read, sync));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::CardTemp::Read> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::CardTemp::Read::keys_::rsp_calibration, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, calibration)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_humidity, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, humidity)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_pressure, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, pressure)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_temperature, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, temperature)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_value, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, value)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_voltage, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, voltage)), ::note::FieldType::Double},
        {::note::api::CardTemp::Read::keys_::rsp_usb, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read::Response, usb)), ::note::FieldType::Bool},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::CardTemp::Read::keys_::minutes, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read, minutes)), ::note::ReqFieldType::Int},
            {::note::api::CardTemp::Read::keys_::status, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read, status)), ::note::ReqFieldType::String},
            {::note::api::CardTemp::Read::keys_::stop, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read, stop)), ::note::ReqFieldType::Bool},
            {::note::api::CardTemp::Read::keys_::sync, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Read, sync)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void CardTemp::Read::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<CardTemp::Read>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename CardTemp::Read::Response> CardTemp::Read::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<CardTemp::Read>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> CardTemp::Read::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<CardTemp::Read>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardTemp::Configure& CardTemp::Configure::minutes_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardTemp::Configure*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Configure, minutes));
}
inline CardTemp::Configure& CardTemp::Configure::status_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardTemp::Configure*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Configure, status));
}
inline CardTemp::Configure& CardTemp::Configure::stop_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardTemp::Configure*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Configure, stop));
}
inline CardTemp::Configure& CardTemp::Configure::sync_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardTemp::Configure*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Configure, sync));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::CardTemp::Configure> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::CardTemp::Configure::keys_::rsp_calibration, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, calibration)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_humidity, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, humidity)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_pressure, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, pressure)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_temperature, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, temperature)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_value, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, value)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_voltage, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, voltage)), ::note::FieldType::Double},
        {::note::api::CardTemp::Configure::keys_::rsp_usb, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure::Response, usb)), ::note::FieldType::Bool},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::CardTemp::Configure::keys_::minutes, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure, minutes)), ::note::ReqFieldType::Int},
            {::note::api::CardTemp::Configure::keys_::status, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure, status)), ::note::ReqFieldType::String},
            {::note::api::CardTemp::Configure::keys_::stop, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure, stop)), ::note::ReqFieldType::Bool},
            {::note::api::CardTemp::Configure::keys_::sync, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Configure, sync)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void CardTemp::Configure::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<CardTemp::Configure>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename CardTemp::Configure::Response> CardTemp::Configure::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<CardTemp::Configure>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> CardTemp::Configure::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<CardTemp::Configure>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardTemp::Stop& CardTemp::Stop::minutes_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardTemp::Stop*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Stop, minutes));
}
inline CardTemp::Stop& CardTemp::Stop::status_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardTemp::Stop*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Stop, status));
}
inline CardTemp::Stop& CardTemp::Stop::sync_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardTemp::Stop*>(
        reinterpret_cast<char*>(this) - offsetof(CardTemp::Stop, sync));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::CardTemp::Stop> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::CardTemp::Stop::keys_::rsp_calibration, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, calibration)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_humidity, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, humidity)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_pressure, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, pressure)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_temperature, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, temperature)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_value, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, value)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_voltage, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, voltage)), ::note::FieldType::Double},
        {::note::api::CardTemp::Stop::keys_::rsp_usb, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop::Response, usb)), ::note::FieldType::Bool},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::CardTemp::Stop::keys_::minutes, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop, minutes)), ::note::ReqFieldType::Int},
            {::note::api::CardTemp::Stop::keys_::status, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop, status)), ::note::ReqFieldType::String},
            {::note::api::CardTemp::Stop::keys_::sync, static_cast<uint16_t>(offsetof(::note::api::CardTemp::Stop, sync)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void CardTemp::Stop::build(JsonBuilder& b) const {
    note::add_flash(b, note::flash(keys_::stop), true);
    using meta_ = ::note::detail::request_traits<CardTemp::Stop>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename CardTemp::Stop::Response> CardTemp::Stop::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<CardTemp::Stop>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> CardTemp::Stop::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<CardTemp::Stop>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
