// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Configures automatic capture of Notecard accelerometer motion in a Notefile.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct CardMotionTrack {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "card.motion.track";
        static constexpr char count[] NOTE_FLASH_ATTR = "count";
        static constexpr char file[] NOTE_FLASH_ATTR = "file";
        static constexpr char minutes[] NOTE_FLASH_ATTR = "minutes";
        static constexpr char now[] NOTE_FLASH_ATTR = "now";
        static constexpr char start[] NOTE_FLASH_ATTR = "start";
        static constexpr char stop[] NOTE_FLASH_ATTR = "stop";
        static constexpr char threshold[] NOTE_FLASH_ATTR = "threshold";
    };

    static constexpr string_view notecard_request = "card.motion.track";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios = RadiosSupport::from(Radios::Cell, Radios::CellWifi, Radios::Skylo, Radios::WiFi);
    static constexpr Firmware min_firmware{};

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif


    /// The number of most recent motion buckets to examine.
    struct count_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// The number of most recent motion buckets to examine.
        CardMotionTrack& operator()(note::json_int_t v);
    } count{};
    /// The Notefile to use for motion capture Notes. See the `_motion.qo`
    /// Notefile's documentation for details on the format of the data captured.
    struct file_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// The Notefile to use for motion capture Notes. See the `_motion.qo`
        /// Notefile's documentation for details on the format of the data
        /// captured.
        CardMotionTrack& operator()(note::string_view v);
    } file{};
    /// The maximum period to capture Notes in the Notefile.
    struct minutes_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// The maximum period to capture Notes in the Notefile.
        CardMotionTrack& operator()(note::json_int_t v);
    } minutes{};
    /// Set to `true` to trigger the immediate creation of a `_motion.qo` event
    /// if the orientation of the Notecard changes (overriding the `minutes`
    /// setting).
    struct now_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to trigger the immediate creation of a `_motion.qo`
        /// event if the orientation of the Notecard changes (overriding the
        /// `minutes` setting).
        CardMotionTrack& operator()(bool v);
    } now{};
    /// `true` to start motion capture.
    struct start_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` to start motion capture.
        CardMotionTrack& operator()(bool v);
    } start{};
    /// `true` to stop motion capture.
    struct stop_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` to stop motion capture.
        CardMotionTrack& operator()(bool v);
    } stop{};
    /// The number of buckets that must indicate motion in order to capture.
    struct threshold_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// The number of buckets that must indicate motion in order to capture.
        CardMotionTrack& operator()(note::json_int_t v);
    } threshold{};


    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
    auto& enable() { start = true; return *this; }
    auto& disable() { stop = true; return *this; }
    auto& enable(bool v_) { if (v_) start = true; else stop = true; return *this; }
#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "count") return note::dyn_field_for(count);
        if (k_ == "file") return note::dyn_field_for(file);
        if (k_ == "minutes") return note::dyn_field_for(minutes);
        if (k_ == "now") return note::dyn_field_for(now);
        if (k_ == "start") return note::dyn_field_for(start);
        if (k_ == "stop") return note::dyn_field_for(stop);
        if (k_ == "threshold") return note::dyn_field_for(threshold);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

#if NOTE_SINGLETON
    private:
    /// Singleton void execute — shared thunk, no per-type instantiation.
    static inline Result<void>(*execute_void_fn_)(void*, ::note::string_view, BuildFn, void*, ::note::detail::NcErrorCapture&, ::note::Safety);
    public:
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<void> — boolean-convertible to true on success;
    /// call .error() to inspect the ErrorInfo on failure.
    ApiResult<void> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        ::note::detail::NcErrorCapture nc_err_;
        auto rv_ = execute_void_fn_(nc_, notecard_request, fn_, &build_, nc_err_, safety);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<void>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        return ApiResult<void>{};
    }
    private:
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
    public:
#else
    ApiResult<Response>(*execute_fn_)(void*, const CardMotionTrack&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {keys_::count, static_cast<uint16_t>(offsetof(CardMotionTrack, count)), ::note::ReqFieldType::Int},
            {keys_::file, static_cast<uint16_t>(offsetof(CardMotionTrack, file)), ::note::ReqFieldType::String},
            {keys_::minutes, static_cast<uint16_t>(offsetof(CardMotionTrack, minutes)), ::note::ReqFieldType::Int},
            {keys_::now, static_cast<uint16_t>(offsetof(CardMotionTrack, now)), ::note::ReqFieldType::Bool},
            {keys_::start, static_cast<uint16_t>(offsetof(CardMotionTrack, start)), ::note::ReqFieldType::Bool},
            {keys_::stop, static_cast<uint16_t>(offsetof(CardMotionTrack, stop)), ::note::ReqFieldType::Bool},
            {keys_::threshold, static_cast<uint16_t>(offsetof(CardMotionTrack, threshold)), ::note::ReqFieldType::Int},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
    private:
    void build(JsonBuilder& b) const {
        uint8_t n_; auto* descs_ = req_field_descs_ptr_(n_);
        ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
    }
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (count) {
            n += p.print(",\"count\":");
            n += note::detail::print_json_value(p, *count);
        }
        if (file) {
            n += p.print(",\"file\":");
            n += note::detail::print_json_value(p, *file);
        }
        if (minutes) {
            n += p.print(",\"minutes\":");
            n += note::detail::print_json_value(p, *minutes);
        }
        if (now) {
            n += p.print(",\"now\":");
            n += note::detail::print_json_value(p, *now);
        }
        if (start) {
            n += p.print(",\"start\":");
            n += note::detail::print_json_value(p, *start);
        }
        if (stop) {
            n += p.print(",\"stop\":");
            n += note::detail::print_json_value(p, *stop);
        }
        if (threshold) {
            n += p.print(",\"threshold\":");
            n += note::detail::print_json_value(p, *threshold);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline CardMotionTrack& CardMotionTrack::count_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, count));
}
inline CardMotionTrack& CardMotionTrack::file_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, file));
}
inline CardMotionTrack& CardMotionTrack::minutes_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, minutes));
}
inline CardMotionTrack& CardMotionTrack::now_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, now));
}
inline CardMotionTrack& CardMotionTrack::start_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, start));
}
inline CardMotionTrack& CardMotionTrack::stop_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, stop));
}
inline CardMotionTrack& CardMotionTrack::threshold_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<CardMotionTrack*>(
        reinterpret_cast<char*>(this) - offsetof(CardMotionTrack, threshold));
}
#pragma GCC diagnostic pop



} // namespace note::api
