// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

#ifndef NOTE_EXTRAS
#define NOTE_EXTRAS 1
#endif
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Retrieves the last known location of the Notecard and the time at which it
/// was acquired. Use card.location.mode to configure location settings.
///
/// This request will return the cell tower location or triangulated location of
/// the most recent session if a GPS/GNSS location is not available.
///
/// On Notecard LoRa this request can only return a location set through the
/// card.location.mode request's `"fixed"` mode.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct CardLocation {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "card.location";
        static constexpr char rsp_count[] NOTE_FLASH_ATTR = "count";
        static constexpr char rsp_dop[] NOTE_FLASH_ATTR = "dop";
        static constexpr char rsp_lat[] NOTE_FLASH_ATTR = "lat";
        static constexpr char rsp_lon[] NOTE_FLASH_ATTR = "lon";
        static constexpr char rsp_max[] NOTE_FLASH_ATTR = "max";
        static constexpr char rsp_mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char rsp_status[] NOTE_FLASH_ATTR = "status";
        static constexpr char rsp_time[] NOTE_FLASH_ATTR = "time";
    };

    static constexpr string_view notecard_request = "card.location";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;
    static constexpr Skus skus{};

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif



#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Successful response
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(32) +
            ::note::detail::arena_cost(80) +
            ::note::detail::arena_cost(64);  // error reserve

        /// The number of consecutive recorded GPS/GNSS failures.
        note::ResponseField<int32_t> count{};
        /// The "Dilution of Precision" value from the latest GPS/GNSS reading.
        /// The lower the value, the higher the confidence level of the reading.
        /// Values can be interpreted in this Wikipedia table#Interpretation).
        note::ResponseField<double> dop{};
        /// The latitude in degrees of the last known location.
        note::ResponseField<double> lat{};
        /// The longitude in degrees of the last known location.
        note::ResponseField<double> lon{};
        /// If a geofence is enabled by `card.location.mode`, meters from the
        /// geofence center.
        note::ResponseField<int32_t> max{};
        /// The GPS/GNSS connection mode. Will be `continuous`, `periodic`, or
        /// `off`.
        note::ResponseField<note::string_view> mode{};
        /// The current status of the Notecard GPS/GNSS connection.
        note::ResponseField<note::string_view> status{};
        /// The time of the location capture.
        note::ResponseField<int32_t> time{};

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.count = reader_->get_int("count");
            rsp.dop = reader_->get_double("dop");
            rsp.lat = reader_->get_double("lat");
            rsp.lon = reader_->get_double("lon");
            rsp.max = reader_->get_int("max");
            rsp.mode = reader_->get_string("mode");
            rsp.status = reader_->get_string("status");
            rsp.time = reader_->get_int("time");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            rsp.count = reader_.get_int("count");
            rsp.dop = reader_.get_double("dop");
            rsp.lat = reader_.get_double("lat");
            rsp.lon = reader_.get_double("lon");
            rsp.max = reader_.get_int("max");
            rsp.mode = reader_.get_string("mode");
            rsp.status = reader_.get_string("status");
            rsp.time = reader_.get_int("time");
            return rsp;
        }

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {}
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_mode) == k_) { rsp.mode = v_; return; }
                if (note::flash(keys_::rsp_status) == k_) { rsp.status = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                if (note::flash(keys_::rsp_count) == k_) { rsp.count = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_max) == k_) { rsp.max = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_dop) == k_) { rsp.dop = ::note::parse_double(raw_); return; }
                if (note::flash(keys_::rsp_lat) == k_) { rsp.lat = ::note::parse_double(raw_); return; }
                if (note::flash(keys_::rsp_lon) == k_) { rsp.lon = ::note::parse_double(raw_); return; }
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, int32_t v_) {
                if (note::flash(keys_::rsp_count) == k_) { rsp.count = v_; return; }
                if (note::flash(keys_::rsp_max) == k_) { rsp.max = v_; return; }
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                if (note::flash(keys_::rsp_dop) == k_) { rsp.dop = v_; return; }
                if (note::flash(keys_::rsp_lat) == k_) { rsp.lat = v_; return; }
                if (note::flash(keys_::rsp_lon) == k_) { rsp.lon = v_; return; }
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!mode.empty()) mode = pool.intern(mode);
            if (!status.empty()) status = pool.intern(status);
        }

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"count\":");
            n += note::detail::print_json_value(p, count.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"dop\":");
            n += note::detail::print_json_value(p, dop.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"lat\":");
            n += note::detail::print_json_value(p, lat.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"lon\":");
            n += note::detail::print_json_value(p, lon.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"max\":");
            n += note::detail::print_json_value(p, max.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"mode\":");
            n += note::detail::print_json_value(p, mode.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"status\":");
            n += note::detail::print_json_value(p, status.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"time\":");
            n += note::detail::print_json_value(p, time.value());
            n += p.print("}");
            return n;
        }
#endif

    private:
        std::unique_ptr<JsonReader> reader_;
    };
    static constexpr uint8_t field_count = 8;
    static const ::note::FieldDesc* field_descs_ptr() {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::FieldDesc table[] = {
            {"count", static_cast<uint16_t>(offsetof(Response, count)), ::note::FieldType::Int32},
            {"dop", static_cast<uint16_t>(offsetof(Response, dop)), ::note::FieldType::Double},
            {"lat", static_cast<uint16_t>(offsetof(Response, lat)), ::note::FieldType::Double},
            {"lon", static_cast<uint16_t>(offsetof(Response, lon)), ::note::FieldType::Double},
            {"max", static_cast<uint16_t>(offsetof(Response, max)), ::note::FieldType::Int32},
            {"mode", static_cast<uint16_t>(offsetof(Response, mode)), ::note::FieldType::String},
            {"status", static_cast<uint16_t>(offsetof(Response, status)), ::note::FieldType::String},
            {"time", static_cast<uint16_t>(offsetof(Response, time)), ::note::FieldType::Int32},
        };
#pragma GCC diagnostic pop
        return table;
    }

#if NOTE_SINGLETON
    /// Singleton: type-erased execute — one static fn ptr per type, set by Api.
    static inline ApiResult<Response>(*execute_fn_)(void*, const CardLocation&);
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
#else
    ApiResult<Response>(*execute_fn_)(void*, const CardLocation&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
#endif
    auto execute() const { return execute_fn_(nc_, *this); }
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    void build(JsonBuilder& b) const {
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
        (void)b;
    }


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        n += p.print("}");
        return n;
    }
#endif

};




} // namespace note::api
