// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

#include <note/body.hpp>
#include <note/struct_sink.hpp>
// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/response_release.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Gets and sets the background download status of MCU host or Notecard
/// firmware updates.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct DfuStatus {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "dfu.status";
        static constexpr char err[] NOTE_FLASH_ATTR = "err";
        static constexpr char name[] NOTE_FLASH_ATTR = "name";
        static constexpr char off[] NOTE_FLASH_ATTR = "off";
        static constexpr char on[] NOTE_FLASH_ATTR = "on";
        static constexpr char status[] NOTE_FLASH_ATTR = "status";
        static constexpr char stop[] NOTE_FLASH_ATTR = "stop";
        static constexpr char version[] NOTE_FLASH_ATTR = "version";
        static constexpr char vvalue[] NOTE_FLASH_ATTR = "vvalue";
        static constexpr char rsp_mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char rsp_status[] NOTE_FLASH_ATTR = "status";
        static constexpr char rsp_off[] NOTE_FLASH_ATTR = "off";
        static constexpr char rsp_on[] NOTE_FLASH_ATTR = "on";
        static constexpr char rsp_pending[] NOTE_FLASH_ATTR = "pending";
    };

    static constexpr string_view notecard_request = "dfu.status";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios = RadiosSupport::from(Radios::Cell, Radios::CellWifi, Radios::Skylo, Radios::WiFi);
    static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// If `err` text is provided along with `"stop":true`, this sets the host
    /// DFU to an error state with the specified string.
    struct err_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// If `err` text is provided along with `"stop":true`, this sets the
        /// host DFU to an error state with the specified string.
        DfuStatus& operator()(note::string_view v);
    } err{};
    /// Determines which type of firmware update status to view. The value can
    /// be `"user"` (default), which gets the status of MCU host firmware
    /// updates, or `"card"`, which gets the status of Notecard firmware
    /// updates.
    // name: user | card
    struct name_t : Field<note::string_view> {
#if __cplusplus >= 202002L && !defined(__clang__)
        constexpr name_t() = default;
        template<std::size_t N>
        consteval name_t(const char (&s)[N])
            : Field<note::string_view>(note::string_view(s, N - 1)) {
            note::string_view sv(s, N - 1);
            if (sv != "user" && sv != "card")
                throw "dfu.status: invalid value for 'name'";
        }
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, name_t>)
        constexpr name_t(U&& v) : Field<note::string_view>(note::string_view(std::forward<U>(v))) {}
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, name_t>)
        name_t& operator=(U&& v) {
            Field<note::string_view>::operator=(note::string_view(std::forward<U>(v)));
            return *this;
        }
        name_t& operator=(std::nullopt_t) { Field<note::string_view>::reset(); return *this; }
        name_t(const name_t&) = default;
        name_t& operator=(const name_t&) = default;
        name_t(name_t&&) = default;
        name_t& operator=(name_t&&) = default;
#else
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
#endif
        static constexpr note::string_view user{"user"};
        static constexpr note::string_view card{"card"};
        /// Determines which type of firmware update status to view. The value
        /// can be `"user"` (default), which gets the status of MCU host
        /// firmware updates, or `"card"`, which gets the status of Notecard
        /// firmware updates.
        DfuStatus& operator()(note::string_view v);
    } name{};
    /// `true` to disable firmware downloads from Notehub.
    struct off_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` to disable firmware downloads from Notehub.
        DfuStatus& operator()(bool v);
    } off{};
    /// `true` to allow firmware downloads from Notehub.
    struct on_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` to allow firmware downloads from Notehub.
        DfuStatus& operator()(bool v);
    } on{};
    /// When setting `stop` to `true`, an optional string synchronized to
    /// Notehub, which can be used for informational or diagnostic purposes.
    struct status_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// When setting `stop` to `true`, an optional string synchronized to
        /// Notehub, which can be used for informational or diagnostic purposes.
        DfuStatus& operator()(note::string_view v);
    } status{};
    /// `true` to clear DFU state and delete the local firmware image from the
    /// Notecard.
    struct stop_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` to clear DFU state and delete the local firmware image from
        /// the Notecard.
        DfuStatus& operator()(bool v);
    } stop{};
    /// Version information on the host firmware to pass to Notehub. You may
    /// pass a simple version number string (e.g. `"1.0.0.0"`), or an object
    /// with detailed information about the firmware image (recommended).
    ///
    /// If you provide an object it must take the following form.
    ///
    /// `{"org":"my-organization","product":"My Product","description":"A
    /// description of the image","version":"1.2.4","built":"Jan 01 2025
    /// 01:02:03","ver_major":1,"ver_minor":2,"ver_patch":4,"ver_build":
    /// 5,"builder":"The Builder"}`
    ///
    /// Code to help you generate a version with the correct formatting is
    /// available in Enabling Notecard Outboard Firmware Update.
    struct version_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// Version information on the host firmware to pass to Notehub. You may
        /// pass a simple version number string (e.g. `"1.0.0.0"`), or an object
        /// with detailed information about the firmware image (recommended).
        ///
        /// If you provide an object it must take the following form.
        ///
        /// `{"org":"my-organization","product":"My Product","description":"A
        /// description of the image","version":"1.2.4","built":"Jan 01 2025
        /// 01:02:03","ver_major":1,"ver_minor":2,"ver_patch":4,"ver_build":
        /// 5,"builder":"The Builder"}`
        ///
        /// Code to help you generate a version with the correct formatting is
        /// available in Enabling Notecard Outboard Firmware Update.
        DfuStatus& operator()(note::string_view v);
    } version{};
    /// A voltage-variable string that controls, by Notecard voltage, whether or
    /// not DFU is enabled. Use a boolean `1` (on) or `0` (off) for each
    /// source/voltage level:
    /// `usb:<1/0>;high:<1/0>;normal:<1/0>;low:<1/0>;dead:0`.
    struct vvalue_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// A voltage-variable string that controls, by Notecard voltage,
        /// whether or not DFU is enabled. Use a boolean `1` (on) or `0` (off)
        /// for each source/voltage level:
        /// `usb:<1/0>;high:<1/0>;normal:<1/0>;low:<1/0>;dead:0`.
        DfuStatus& operator()(note::string_view v);
    } vvalue{};

    // Valid values for 'name':
    //   "user" — Gets the status of MCU host firmware updates (default).
    //   "card" — Gets the status of Notecard firmware updates.
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedName(const char* v) {
        note::string_view sv{v};
        if (sv != "user" && sv != "card")
            throw "dfu.status: invalid value for 'name'";
        return sv;
    }
#endif

    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
    auto& allow() { on = true; return *this; }
    auto& deny() { off = true; return *this; }
    auto& allowDownloads(bool v_) { if (v_) on = true; else off = true; return *this; }
    auto& clearDfu() { stop = true; return *this; }
    auto& clearDfu(bool v_) { stop = v_; return *this; }
#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "err") return note::dyn_field_for(err);
        if (k_ == "name") return note::dyn_field_for(name);
        if (k_ == "off") return note::dyn_field_for(off);
        if (k_ == "on") return note::dyn_field_for(on);
        if (k_ == "status") return note::dyn_field_for(status);
        if (k_ == "stop") return note::dyn_field_for(stop);
        if (k_ == "version") return note::dyn_field_for(version);
        if (k_ == "vvalue") return note::dyn_field_for(vvalue);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    // Type-erased body handler factory for streaming body parse.
    // Set by .into(T&) — execute paths use this to create a StructSink.
    void* body_ptr_ = nullptr;
    using BodyHandlerFactory_ = ::note::BodyHandler(*)(void* body, ::note::StringPool& pool, void* storage);
    BodyHandlerFactory_ body_handler_factory_ = nullptr;

    /// Wire body parsing to the given struct.
    /// The struct must use NOTE_FIELDS() or be a C++20 aggregate.
    /// SFINAE excludes JsonSink-derived types so the JsonSink& overload
    /// below wins for those.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& into(BodyT_& out) {
        body_ptr_ = &out;
        body_handler_factory_ = [](void* b, ::note::StringPool& pool, void* storage) -> ::note::BodyHandler {
#if !NOTE_RESPONSE_BODY
            uint8_t n_;
            auto* descs_ = BodyT_::template _note_field_descs<BodyT_>(n_);
            auto* sink = new (storage) ::note::GenericBodySink{b, descs_, n_, &pool};
            return ::note::make_generic_body_handler(*sink);
#else
            auto* sink = new (storage) ::note::StructSink<BodyT_>(*static_cast<BodyT_*>(b), pool);
            return ::note::make_body_handler(*sink);
#endif
        };
        return *this;
    }
    /// Return a copy with body parsing wired to the given struct (const overload).
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto into(BodyT_& out) const {
        auto copy = *this;
        copy.into(out);
        return copy;
    }

    /// Forward body SAX events to the given JsonSink.
    /// The sink must outlive execute(). Works in both streaming and
    /// JSON tree-mode transports.
    auto& into(::note::JsonSink& sink_) {
        body_ptr_ = &sink_;
        body_handler_factory_ = &::note::jsonsink_body_factory;
        return *this;
    }
    /// Return a copy with body events wired to the given JsonSink (const overload).
    auto into(::note::JsonSink& sink_) const {
        auto copy = *this;
        copy.into(sink_);
        return copy;
    }
    /// Alias for into(): wire body parsing to the given struct.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& body(BodyT_& out) { return into(out); }
    /// Const alias for into() — returns a copy with body parsing wired up.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto body(BodyT_& out) const { return into(out); }
    /// Alias for into(): wire body parsing to the given struct.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& from(BodyT_& out) { return into(out); }
    /// Const alias for into() — returns a copy with body parsing wired up.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto from(BodyT_& out) const { return into(out); }

    /// Response containing the current DFU mode and status information for
    /// firmware downloads.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(33) +
            ::note::detail::arena_cost(81) +
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

        /// The current DFU mode. Will be one of:
        note::ResponseField<note::string_view> mode{};
        /// The current status of the firmware download.
        note::ResponseField<note::string_view> status{};
        /// `true` when firmware downloads are disabled.
        note::ResponseField<bool> off{};
        /// `true` when firmware downloads are enabled.
        note::ResponseField<bool> on{};
        /// `true` when Notecard DFU is currently in-progress.
        note::ResponseField<bool> pending{};

#if !NOTE_NO_RESPONSE_RAII
        /// Allocator that minted this Response's interned string fields,
        /// attached by Notecard execute paths when the Response is parsed.
        /// Empty == no cleanup needed (default-constructed Response, or a
        /// tree-mode parse with no `set_allocator` configured).
        ::note::AllocatorRef alloc_;

        ~Response() {
            if (!alloc_) return;
#if NOTE_RESPONSE_RELEASE_LOOP
            ::note::detail::release_string_fields(*alloc_,
                &mode,
                2);
#else
            ::note::detail::deallocate_if_present(*alloc_, mode.value());
            ::note::detail::deallocate_if_present(*alloc_, status.value());
#endif
        }

        // Move-only: copying a Response would alias the interned-string
        // ownership and double-free on the second destruction. AllocatorRef
        // nulls the source's pointer so only the live owner runs cleanup.
        Response() = default;
        Response(Response&&) noexcept = default;
        Response& operator=(Response&& o) noexcept {
            if (this != &o) {
                this->~Response();
                ::new (this) Response(::std::move(o));
            }
            return *this;
        }
        Response(const Response&) = delete;
        Response& operator=(const Response&) = delete;
#endif // !NOTE_NO_RESPONSE_RAII

#if !NOTE_NO_JSON_TREE
        /// Access the body as a JsonReader (JSON tree-mode path only).
        /// Returns `nullptr` when the response had no body field, OR
        /// when the Notecard ran in streaming mode (no JSON tree was
        /// built). The two cases look identical to the caller — prefer
        /// `body_or_error()` for explicit handling of the streaming case.
        [[nodiscard]] const JsonReader* body() const { return body_.get(); }

        /// Safe variant of `body()`: returns an explicit error when the
        /// Notecard ran in streaming mode (body tree unavailable by
        /// design), otherwise returns the body pointer (which may still
        /// be `nullptr` if the response carried no body field).
        ::note::Result<const JsonReader*> body_or_error() const {
            if (streaming_parse_used_)
                return ::note::make_error(::note::Error::NotReady, NOTE_ERR(
                    "body() unavailable: Notecard parsed response in streaming mode. "
                    "Use .into(JsonSink&) or .into(MyStruct&) for streaming body access."));
            return body_.get();
        }

        /// True when this response was produced by the streaming SAX
        /// parser path (no JSON tree built). When true, `body()` is
        /// unavailable and `body_or_error()` returns an explicit error.
        bool was_streaming_parse() const { return streaming_parse_used_; }
#endif

#if !NOTE_NO_JSON_TREE
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            if (reader_->has("mode")) rsp.mode = reader_->get_string("mode");
            if (reader_->has("status")) rsp.status = reader_->get_string("status");
            if (reader_->has("off")) rsp.off = reader_->get_bool("off");
            if (reader_->has("on")) rsp.on = reader_->get_bool("on");
            if (reader_->has("pending")) rsp.pending = reader_->get_bool("pending");
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            if (reader_.has("mode")) rsp.mode = reader_.get_string("mode");
            if (reader_.has("status")) rsp.status = reader_.get_string("status");
            if (reader_.has("off")) rsp.off = reader_.get_bool("off");
            if (reader_.has("on")) rsp.on = reader_.get_bool("on");
            if (reader_.has("pending")) rsp.pending = reader_.get_bool("pending");
            rsp.body_ = reader_.get_object("body");
            return rsp;
        }
#endif // !NOTE_NO_JSON_TREE

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            ::note::BodyHandler body_handler_{};
            int body_depth_ = 0;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
#if !NOTE_NO_JSON_TREE
                // Mark the Response as streaming-parsed at construction
                // time, before any SAX events fire. Successful first
                // attempts never call reset(), so the flag has to be set
                // here for body_or_error()/was_streaming_parse() to be
                // accurate on the happy path.
                rsp.streaming_parse_used_ = true;
#endif
            }
            void set_body_handler(::note::BodyHandler bh) { body_handler_ = bh; }
            NOTE_SINK_NOINLINE void on_array_begin(::note::string_view k_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_array_begin(k_));
            }
            NOTE_SINK_NOINLINE void on_array_end(::note::string_view k_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_array_end(k_));
            }
            NOTE_SINK_NOINLINE void on_object_begin(::note::string_view k_) {
                if (body_depth_ > 0) {
                    ++body_depth_;
                    if (body_handler_) body_handler_.send(::note::BodyEvent::make_object_begin(k_));
                    return;
                }
                if (k_ == "body") { body_depth_ = 1; return; }
            }
            NOTE_SINK_NOINLINE void on_object_end(::note::string_view k_) {
                if (body_depth_ > 0) {
                    --body_depth_;
                    if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_object_end(k_));
                    return;
                }
            }
            NOTE_SINK_NOINLINE void on_null(::note::string_view k_) { (void)k_; }
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                if (body_depth_ > 0) { if (body_handler_) body_handler_.send(::note::BodyEvent::make_string(k_, v_)); return; }
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_mode) == k_) { rsp.mode = v_; return; }
                if (note::flash(keys_::rsp_status) == k_) { rsp.status = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                if (body_depth_ > 0) { if (body_handler_) body_handler_.send(::note::BodyEvent::make_bool(k_, v_)); return; }
                if (note::flash(keys_::rsp_off) == k_) { rsp.off = v_; return; }
                if (note::flash(keys_::rsp_on) == k_) { rsp.on = v_; return; }
                if (note::flash(keys_::rsp_pending) == k_) { rsp.pending = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_number(k_, raw_));
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, ::note::json_int_t v_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_int(k_, v_));
            }
            NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_float(k_, v_));
            }
            NOTE_SINK_NOINLINE void reset() {
                body_depth_ = 0;
                if (body_handler_) body_handler_.send(::note::BodyEvent::make_reset());
                rsp = Response{};
#if !NOTE_NO_JSON_TREE
                rsp.streaming_parse_used_ = true;
#endif
            }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!mode.empty()) mode = pool.intern(mode);
            if (!status.empty()) status = pool.intern(status);
        }

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"mode\":");
            n += note::detail::print_json_value(p, mode.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"status\":");
            n += note::detail::print_json_value(p, status.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"off\":");
            n += note::detail::print_json_value(p, off.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"on\":");
            n += note::detail::print_json_value(p, on.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"pending\":");
            n += note::detail::print_json_value(p, pending.value());
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_JSON_TREE
    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;
        /// Set by the streaming Sink (typed path) or by the enclosing op's
        /// generated SINGLETON `execute()` (GenericResponseSink path) when
        /// this Response is populated via SAX parsing (no JSON tree).
        /// `body_or_error()` reads this to surface an explicit error
        /// instead of a silent nullptr.
        bool streaming_parse_used_ = false;
        friend struct Sink;
        friend struct DfuStatus;
#endif
    };

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<Response> — boolean-convertible to true on success;
    /// dereference (or use member-of-pointer ->) to read response fields,
    /// or call .error() to inspect the ErrorInfo on failure.
    ApiResult<Response> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const DfuStatus&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (err) {
            n += p.print(",\"err\":");
            n += note::detail::print_json_value(p, *err);
        }
        if (name) {
            n += p.print(",\"name\":");
            n += note::detail::print_json_value(p, *name);
        }
        if (off) {
            n += p.print(",\"off\":");
            n += note::detail::print_json_value(p, *off);
        }
        if (on) {
            n += p.print(",\"on\":");
            n += note::detail::print_json_value(p, *on);
        }
        if (status) {
            n += p.print(",\"status\":");
            n += note::detail::print_json_value(p, *status);
        }
        if (stop) {
            n += p.print(",\"stop\":");
            n += note::detail::print_json_value(p, *stop);
        }
        if (version) {
            n += p.print(",\"version\":");
            n += note::detail::print_json_value(p, *version);
        }
        if (vvalue) {
            n += p.print(",\"vvalue\":");
            n += note::detail::print_json_value(p, *vvalue);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename, typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    friend struct ::note::test::JsonbWireProbe;
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline DfuStatus& DfuStatus::err_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, err));
}
inline DfuStatus& DfuStatus::name_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, name));
}
inline DfuStatus& DfuStatus::off_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, off));
}
inline DfuStatus& DfuStatus::on_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, on));
}
inline DfuStatus& DfuStatus::status_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, status));
}
inline DfuStatus& DfuStatus::stop_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, stop));
}
inline DfuStatus& DfuStatus::version_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, version));
}
inline DfuStatus& DfuStatus::vvalue_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<DfuStatus*>(
        reinterpret_cast<char*>(this) - offsetof(DfuStatus, vvalue));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::DfuStatus> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::DfuStatus::keys_::rsp_mode, static_cast<uint16_t>(offsetof(::note::api::DfuStatus::Response, mode)), ::note::FieldType::String},
        {::note::api::DfuStatus::keys_::rsp_status, static_cast<uint16_t>(offsetof(::note::api::DfuStatus::Response, status)), ::note::FieldType::String},
        {::note::api::DfuStatus::keys_::rsp_off, static_cast<uint16_t>(offsetof(::note::api::DfuStatus::Response, off)), ::note::FieldType::Bool},
        {::note::api::DfuStatus::keys_::rsp_on, static_cast<uint16_t>(offsetof(::note::api::DfuStatus::Response, on)), ::note::FieldType::Bool},
        {::note::api::DfuStatus::keys_::rsp_pending, static_cast<uint16_t>(offsetof(::note::api::DfuStatus::Response, pending)), ::note::FieldType::Bool},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::DfuStatus::keys_::err, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, err)), ::note::ReqFieldType::String},
            {::note::api::DfuStatus::keys_::name, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, name)), ::note::ReqFieldType::String},
            {::note::api::DfuStatus::keys_::off, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, off)), ::note::ReqFieldType::Bool},
            {::note::api::DfuStatus::keys_::on, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, on)), ::note::ReqFieldType::Bool},
            {::note::api::DfuStatus::keys_::status, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, status)), ::note::ReqFieldType::String},
            {::note::api::DfuStatus::keys_::stop, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, stop)), ::note::ReqFieldType::Bool},
            {::note::api::DfuStatus::keys_::version, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, version)), ::note::ReqFieldType::String},
            {::note::api::DfuStatus::keys_::vvalue, static_cast<uint16_t>(offsetof(::note::api::DfuStatus, vvalue)), ::note::ReqFieldType::String},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void DfuStatus::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<DfuStatus>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename DfuStatus::Response> DfuStatus::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<DfuStatus>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, body_ptr_, body_handler_factory_, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
#if !NOTE_NO_RESPONSE_RAII
    // The type-erased thunk couldn't reach `attach_allocator`. Mark the
    // Response as owning its interned strings so its dtor frees them on
    // the SINGLETON path (parity with the Notecard::execute template path,
    // which attaches via `detail::attach_allocator`). The dtor still gates
    // the actual free on `g_singleton_allocator_present`, so marking when
    // no allocator is configured stays safe.
    rsp_.alloc_.reset(::note::detail::g_singleton_allocator);
#endif
#if !NOTE_NO_JSON_TREE
    // The typed Sink would set this in its ctor; the SINGLETON path uses
    // GenericResponseSink instead, which doesn't touch the flag. Set it
    // here to keep `body_or_error()` / `was_streaming_parse()` accurate
    // when the streaming path runs (i.e. when an allocator is configured;
    // execute_generic_with_body picks the buffered fallback otherwise).
    if (::note::detail::g_singleton_allocator_present)
        rsp_.streaming_parse_used_ = true;
#endif
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> DfuStatus::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<DfuStatus>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
