// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Sets a local environment variable on the Notecard. Local environment
/// variables cannot be overridden by a Notehub variable of any scope.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct EnvSet {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "env.set";
        static constexpr char name[] NOTE_FLASH_ATTR = "name";
        static constexpr char text[] NOTE_FLASH_ATTR = "text";
        static constexpr char rsp_time[] NOTE_FLASH_ATTR = "time";
    };

    static constexpr string_view notecard_request = "env.set";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios = RadiosSupport::from(Radios::Cell, Radios::CellWifi, Radios::Skylo, Radios::WiFi);
    static constexpr Firmware min_firmware{};

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif


    /// The name of the environment variable (case-insensitive).
    note::string_view name{};
    /// The value of the variable. Pass `""` or omit from the request to delete
    /// it.
    struct text_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        EnvSet& operator()(note::string_view v);
    } text{};


#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "name") return note::dyn_field_for(name);
        if (k_ == "text") return note::dyn_field_for(text);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response containing the timestamp of the environment variable change.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        /// The logged time of the variable change.
        ///
        /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
        [[deprecated("requires firmware >= 3.4.1")]]
#endif
        note::ResponseField<note::json_int_t> time{};
#endif

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if !NOTE_NO_BUFFERED
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (reader_->has("time")) rsp.time = reader_->get_int("time");
#endif
            rsp.reader_ = std::move(reader_);
            return rsp;
        }
#pragma GCC diagnostic pop

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        static Response parse(const JsonReader& reader_) {
            Response rsp;
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (reader_.has("time")) rsp.time = reader_.get_int("time");
#endif
            return rsp;
        }
#pragma GCC diagnostic pop
#endif // !NOTE_NO_BUFFERED

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {}
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = ::note::parse_int(raw_); return; }
#endif
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, ::note::json_int_t v_) {
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = v_; return; }
#endif
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };
#pragma GCC diagnostic pop

        void intern_strings(::note::StringPool&) {}

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"time\":");
            n += note::detail::print_json_value(p, time.value());
#endif
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_BUFFERED
    private:
        std::unique_ptr<JsonReader> reader_;
#endif
    };
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        {keys_::rsp_time, static_cast<uint16_t>(offsetof(Response, time)), ::note::FieldType::Int},
#endif
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }

#if NOTE_SINGLETON
    /// Singleton generic execute — shared thunk with body factory params.
    static inline Result<void>(*execute_generic_fn_)(void*, ::note::string_view, BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety);
    ApiResult<Response> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        Response rsp_{};
        ::note::detail::NcErrorCapture nc_err_;
        bool exhausted_ = false;
        auto rv_ = execute_generic_fn_(nc_, notecard_request, fn_, &build_, &rsp_, field_descs_ptr(), field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
        return ApiResult<Response>(std::move(rsp_));
    }
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
#else
    ApiResult<Response>(*execute_fn_)(void*, const EnvSet&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {keys_::text, static_cast<uint16_t>(offsetof(EnvSet, text)), ::note::ReqFieldType::String},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
    void build(JsonBuilder& b) const {
        note::add_flash(b, note::flash(keys_::name), name);
        uint8_t n_; auto* descs_ = req_field_descs_ptr_(n_);
        ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
    }


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        n += p.print(",\"name\":");
        n += note::detail::print_json_value(p, name);
        if (text) {
            n += p.print(",\"text\":");
            n += note::detail::print_json_value(p, *text);
        }
        n += p.print("}");
        return n;
    }
#endif

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline EnvSet& EnvSet::text_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<EnvSet*>(
        reinterpret_cast<char*>(this) - offsetof(EnvSet, text));
}
#pragma GCC diagnostic pop



} // namespace note::api
