// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

#include <note/body.hpp>
#include <note/struct_sink.hpp>
// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/array_field.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Returns a single environment variable, or all variables according to
/// precedence rules.
///
/// When called without a `name` (or `names`), `env.get` returns the full
/// environment-variable set known to the Notecard. The response size scales
/// with the Notehub project and may exceed the default response buffer,
/// surfacing as `Error::Overflow`. For this shape, prefer the streaming
/// `.into(JsonSink&)` overload — body events stream off the wire and the env
/// set can be arbitrarily large. As an alternative,
/// `Notecard::set_response_buffer()` can enlarge the staging buffer if a
/// bounded response is acceptable.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct EnvGet {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "env.get";
        static constexpr char name[] NOTE_FLASH_ATTR = "name";
        static constexpr char names[] NOTE_FLASH_ATTR = "names";
        static constexpr char time[] NOTE_FLASH_ATTR = "time";
        static constexpr char rsp_text[] NOTE_FLASH_ATTR = "text";
        static constexpr char rsp_time[] NOTE_FLASH_ATTR = "time";
    };

    static constexpr string_view notecard_request = "env.get";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;
    static constexpr RadiosSupport radios{};
    static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// The name of the environment variable (case-insensitive). Omit to return
    /// all environment variables known to the Notecard.
    struct name_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// The name of the environment variable (case-insensitive). Omit to
        /// return all environment variables known to the Notecard.
        EnvGet& operator()(note::string_view v);
    } name{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
    /// A list of one or more variables to retrieve, by name (case-insensitive).
    ///
    /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
    [[deprecated("requires firmware >= 3.4.1")]]
#endif
    /// A list of one or more variables to retrieve, by name (case-insensitive).
    ///
    /// @since{3.4.1}
    note::ArrayField<note::string_view, 8> names{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
    /// Request a modified environment variable or variables from the Notecard,
    /// but only if modified after the time provided.
    ///
    /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
    [[deprecated("requires firmware >= 3.4.1")]]
#endif
    struct time_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// Request a modified environment variable or variables from the
        /// Notecard, but only if modified after the time provided.
        ///
        /// @since{3.4.1}
        EnvGet& operator()(note::json_int_t v);
    } time{};
#endif


#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "name") return note::dyn_field_for(name);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "time") return note::dyn_field_for(time);
#endif
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    // Type-erased body handler factory for streaming body parse.
    // Set by .into(T&) — execute paths use this to create a StructSink.
    void* body_ptr_ = nullptr;
    using BodyHandlerFactory_ = ::note::BodyHandler(*)(void* body, ::note::StringPool& pool, void* storage);
    BodyHandlerFactory_ body_handler_factory_ = nullptr;

    /// Wire body parsing to the given struct.
    /// The struct must use NOTE_FIELDS() or be a C++20 aggregate.
    /// SFINAE excludes JsonSink-derived types so the JsonSink& overload
    /// below wins for those.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& into(BodyT_& out) {
        body_ptr_ = &out;
        body_handler_factory_ = [](void* b, ::note::StringPool& pool, void* storage) -> ::note::BodyHandler {
#if !NOTE_RESPONSE_BODY
            uint8_t n_;
            auto* descs_ = BodyT_::template _note_field_descs<BodyT_>(n_);
            auto* sink = new (storage) ::note::GenericBodySink{b, descs_, n_, &pool};
            return ::note::make_generic_body_handler(*sink);
#else
            auto* sink = new (storage) ::note::StructSink<BodyT_>(*static_cast<BodyT_*>(b), pool);
            return ::note::make_body_handler(*sink);
#endif
        };
        return *this;
    }
    /// Return a copy with body parsing wired to the given struct (const overload).
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto into(BodyT_& out) const {
        auto copy = *this;
        copy.into(out);
        return copy;
    }

    /// Forward body SAX events to the given JsonSink.
    /// The sink must outlive execute(). Works in both streaming and
    /// JSON tree-mode transports.
    auto& into(::note::JsonSink& sink_) {
        body_ptr_ = &sink_;
        body_handler_factory_ = &::note::jsonsink_body_factory;
        return *this;
    }
    /// Return a copy with body events wired to the given JsonSink (const overload).
    auto into(::note::JsonSink& sink_) const {
        auto copy = *this;
        copy.into(sink_);
        return copy;
    }
    /// Alias for into(): wire body parsing to the given struct.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& body(BodyT_& out) { return into(out); }
    /// Const alias for into() — returns a copy with body parsing wired up.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto body(BodyT_& out) const { return into(out); }
    /// Alias for into(): wire body parsing to the given struct.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto& from(BodyT_& out) { return into(out); }
    /// Const alias for into() — returns a copy with body parsing wired up.
    template<typename BodyT_,
             typename = ::std::enable_if_t<!::std::is_base_of_v<::note::JsonSink, BodyT_>>>
    auto from(BodyT_& out) const { return into(out); }

    /// Response containing environment variable values and metadata based on
    /// the request parameters.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(129) +
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

        /// If a `name` was specified, the value of the environment variable.
        note::ResponseField<note::string_view> text{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        /// The time of the Notecard variable or variables change.
        ///
        /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
        [[deprecated("requires firmware >= 3.4.1")]]
#endif
        note::ResponseField<note::json_int_t> time{};
#endif

#if !NOTE_NO_JSON_TREE
        /// Access the body as a JsonReader (JSON tree-mode path only).
        /// Returns `nullptr` when the response had no body field, OR
        /// when the Notecard ran in streaming mode (no JSON tree was
        /// built). The two cases look identical to the caller — prefer
        /// `body_or_error()` for explicit handling of the streaming case.
        [[nodiscard]] const JsonReader* body() const { return body_.get(); }

        /// Safe variant of `body()`: returns an explicit error when the
        /// Notecard ran in streaming mode (body tree unavailable by
        /// design), otherwise returns the body pointer (which may still
        /// be `nullptr` if the response carried no body field).
        ::note::Result<const JsonReader*> body_or_error() const {
            if (streaming_parse_used_)
                return ::note::make_error(::note::Error::NotReady, NOTE_ERR(
                    "body() unavailable: Notecard parsed response in streaming mode. "
                    "Use .into(JsonSink&) or .into(MyStruct&) for streaming body access."));
            return body_.get();
        }

        /// True when this response was produced by the streaming SAX
        /// parser path (no JSON tree built). When true, `body()` is
        /// unavailable and `body_or_error()` returns an explicit error.
        bool was_streaming_parse() const { return streaming_parse_used_; }
#endif

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if !NOTE_NO_JSON_TREE
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            if (reader_->has("text")) rsp.text = reader_->get_string("text");
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (reader_->has("time")) rsp.time = reader_->get_int("time");
#endif
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }
#pragma GCC diagnostic pop

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            if (reader_.has("text")) rsp.text = reader_.get_string("text");
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (reader_.has("time")) rsp.time = reader_.get_int("time");
#endif
            rsp.body_ = reader_.get_object("body");
            return rsp;
        }
#pragma GCC diagnostic pop
#endif // !NOTE_NO_JSON_TREE

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            ::note::BodyHandler body_handler_{};
            int body_depth_ = 0;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
#if !NOTE_NO_JSON_TREE
                // Mark the Response as streaming-parsed at construction
                // time, before any SAX events fire. Successful first
                // attempts never call reset(), so the flag has to be set
                // here for body_or_error()/was_streaming_parse() to be
                // accurate on the happy path.
                rsp.streaming_parse_used_ = true;
#endif
            }
            void set_body_handler(::note::BodyHandler bh) { body_handler_ = bh; }
            NOTE_SINK_NOINLINE void on_array_begin(::note::string_view k_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_array_begin(k_));
            }
            NOTE_SINK_NOINLINE void on_array_end(::note::string_view k_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_array_end(k_));
            }
            NOTE_SINK_NOINLINE void on_object_begin(::note::string_view k_) {
                if (body_depth_ > 0) {
                    ++body_depth_;
                    if (body_handler_) body_handler_.send(::note::BodyEvent::make_object_begin(k_));
                    return;
                }
                if (k_ == "body") { body_depth_ = 1; return; }
            }
            NOTE_SINK_NOINLINE void on_object_end(::note::string_view k_) {
                if (body_depth_ > 0) {
                    --body_depth_;
                    if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_object_end(k_));
                    return;
                }
            }
            NOTE_SINK_NOINLINE void on_null(::note::string_view k_) { (void)k_; }
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                if (body_depth_ > 0) { if (body_handler_) body_handler_.send(::note::BodyEvent::make_string(k_, v_)); return; }
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_text) == k_) { rsp.text = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_bool(k_, v_));
            }
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                if (body_depth_ > 0) { if (body_handler_) body_handler_.send(::note::BodyEvent::make_number(k_, raw_)); return; }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = ::note::parse_int(raw_); return; }
#endif
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, ::note::json_int_t v_) {
                if (body_depth_ > 0) { if (body_handler_) body_handler_.send(::note::BodyEvent::make_int(k_, v_)); return; }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = v_; return; }
#endif
            }
            NOTE_SINK_NOINLINE void on_float(::note::string_view k_, double v_) {
                if (body_depth_ > 0 && body_handler_) body_handler_.send(::note::BodyEvent::make_float(k_, v_));
            }
            NOTE_SINK_NOINLINE void reset() {
                body_depth_ = 0;
                if (body_handler_) body_handler_.send(::note::BodyEvent::make_reset());
                rsp = Response{};
#if !NOTE_NO_JSON_TREE
                rsp.streaming_parse_used_ = true;
#endif
            }
        };
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        void intern_strings(::note::StringPool& pool) {
            if (!text.empty()) text = pool.intern(text);
        }
#pragma GCC diagnostic pop

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"text\":");
            n += note::detail::print_json_value(p, text.value());
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"time\":");
            n += note::detail::print_json_value(p, time.value());
#endif
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_JSON_TREE
    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;
        /// Set by the streaming Sink when this Response is populated via
        /// SAX parsing (no JSON tree). `body_or_error()` reads this
        /// to surface an explicit error instead of a silent nullptr.
        bool streaming_parse_used_ = false;
        friend struct Sink;
#endif
    };

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<Response> — boolean-convertible to true on success;
    /// dereference (or use member-of-pointer ->) to read response fields,
    /// or call .error() to inspect the ErrorInfo on failure.
    ApiResult<Response> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const EnvGet&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (name) {
            n += p.print(",\"name\":");
            n += note::detail::print_json_value(p, *name);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (time) {
            n += p.print(",\"time\":");
            n += note::detail::print_json_value(p, *time);
        }
#endif
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline EnvGet& EnvGet::name_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<EnvGet*>(
        reinterpret_cast<char*>(this) - offsetof(EnvGet, name));
}
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
inline EnvGet& EnvGet::time_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<EnvGet*>(
        reinterpret_cast<char*>(this) - offsetof(EnvGet, time));
}
#endif
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::EnvGet> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::EnvGet::keys_::rsp_text, static_cast<uint16_t>(offsetof(::note::api::EnvGet::Response, text)), ::note::FieldType::String},
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        {::note::api::EnvGet::keys_::rsp_time, static_cast<uint16_t>(offsetof(::note::api::EnvGet::Response, time)), ::note::FieldType::Int},
#endif
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::EnvGet::keys_::name, static_cast<uint16_t>(offsetof(::note::api::EnvGet, name)), ::note::ReqFieldType::String},
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            {::note::api::EnvGet::keys_::names, static_cast<uint16_t>(offsetof(::note::api::EnvGet, names)), ::note::ReqFieldType::Array},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            {::note::api::EnvGet::keys_::time, static_cast<uint16_t>(offsetof(::note::api::EnvGet, time)), ::note::ReqFieldType::Int},
#endif
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline void EnvGet::build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
#endif
    using meta_ = ::note::detail::request_traits<EnvGet>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}
#pragma GCC diagnostic pop

#if NOTE_SINGLETON
inline ApiResult<typename EnvGet::Response> EnvGet::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<EnvGet>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, body_ptr_, body_handler_factory_, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> EnvGet::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<EnvGet>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
