// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#ifndef NOTE_EXTRAS
#define NOTE_EXTRAS 1
#endif
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {








/// Used to clear the contents of a specified outbound (`.qo`/`.qos`) Notefile,
/// deleting all pending Notes.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct FileClear {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "file.clear";
        static constexpr char file[] NOTE_FLASH_ATTR = "file";
    };

    static constexpr string_view notecard_request = "file.clear";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Destructive;
    static constexpr Skus skus = Skus::from(Product::Cell, Product::CellWifi, Product::Skylo, Product::WiFi);

    void* nc_ = nullptr;


    /// The name of the Notefile whose Notes you wish to delete.
    struct file_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        FileClear& operator()(note::string_view v);
    } file{};


#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "file") return note::dyn_field_for(file);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

    ApiResult<Response>(*execute_fn_)(void*, const FileClear&) = nullptr;
    auto execute() const { return execute_fn_(nc_, *this); }
    Result<void>(*command_fn_)(void*, const FileClear&) = nullptr;
    Result<void> command() const { return command_fn_(nc_, *this); }

    void build(JsonBuilder& b) const {
        if (file) note::add_flash(b, note::flash(keys_::file), *file);
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
    }


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (file) {
            n += p.print(",\"file\":");
            n += note::detail::print_json_value(p, *file);
        }
        n += p.print("}");
        return n;
    }
#endif

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline FileClear& FileClear::file_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<FileClear*>(
        reinterpret_cast<char*>(this) - offsetof(FileClear, file));
}
#pragma GCC diagnostic pop


} // namespace note::api
