// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

#ifndef NOTE_EXTRAS
#define NOTE_EXTRAS 1
#endif
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Used to clear the contents of a specified outbound (`.qo`/`.qos`) Notefile,
/// deleting all pending Notes.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct FileClear {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "file.clear";
        static constexpr char file[] NOTE_FLASH_ATTR = "file";
    };

    static constexpr string_view notecard_request = "file.clear";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Destructive;
    static constexpr Skus skus = Skus::from(Product::Cell, Product::CellWifi, Product::Skylo, Product::WiFi);

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif


    /// The name of the Notefile whose Notes you wish to delete.
    struct file_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        FileClear& operator()(note::string_view v);
    } file{};


#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "file") return note::dyn_field_for(file);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

#if NOTE_SINGLETON
    /// Singleton void execute — shared thunk, no per-type instantiation.
    static inline Result<void>(*execute_void_fn_)(void*, ::note::string_view, BuildFn, void*, ::note::detail::NcErrorCapture&);
    ApiResult<void> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        ::note::detail::NcErrorCapture nc_err_;
        auto rv_ = execute_void_fn_(nc_, notecard_request, fn_, &build_, nc_err_);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<void>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        return ApiResult<void>{};
    }
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
#else
    ApiResult<Response>(*execute_fn_)(void*, const FileClear&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {keys_::file, static_cast<uint16_t>(offsetof(FileClear, file)), ::note::ReqFieldType::String},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
    void build(JsonBuilder& b) const {
        uint8_t n_; auto* descs_ = req_field_descs_ptr_(n_);
        ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
    }


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (file) {
            n += p.print(",\"file\":");
            n += note::detail::print_json_value(p, *file);
        }
        n += p.print("}");
        return n;
    }
#endif

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline FileClear& FileClear::file_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<FileClear*>(
        reinterpret_cast<char*>(this) - offsetof(FileClear, file));
}
#pragma GCC diagnostic pop



} // namespace note::api
