// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Check on the status of a recently triggered or previous sync.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct HubSyncStatus {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "hub.sync.status";
        static constexpr char sync[] NOTE_FLASH_ATTR = "sync";
        static constexpr char rsp_alert[] NOTE_FLASH_ATTR = "alert";
        static constexpr char rsp_completed[] NOTE_FLASH_ATTR = "completed";
        static constexpr char rsp_mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char rsp_requested[] NOTE_FLASH_ATTR = "requested";
        static constexpr char rsp_scan[] NOTE_FLASH_ATTR = "scan";
        static constexpr char rsp_seconds[] NOTE_FLASH_ATTR = "seconds";
        static constexpr char rsp_status[] NOTE_FLASH_ATTR = "status";
        static constexpr char rsp_sync[] NOTE_FLASH_ATTR = "sync";
        static constexpr char rsp_time[] NOTE_FLASH_ATTR = "time";
    };

    static constexpr string_view notecard_request = "hub.sync.status";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;
    static constexpr RadiosSupport radios{};
    static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// `true` if this request should auto-initiate a sync pending outbound
    /// data.
    struct sync_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// `true` if this request should auto-initiate a sync pending outbound
        /// data.
        HubSyncStatus& operator()(bool v);
    } sync{};


#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "sync") return note::dyn_field_for(sync);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response containing the status of a recently triggered or previous sync.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(33) +
            ::note::detail::arena_cost(81) +
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

        /// `true` if an error occurred during the most recent sync.
        note::ResponseField<bool> alert{};
        /// Number of seconds since the last sync completion.
        note::ResponseField<note::json_int_t> completed{};
        /// The current state of the wireless connectivity module in use.
        note::ResponseField<note::string_view> mode{};
        /// Number of seconds since the last explicit sync request.
        note::ResponseField<note::json_int_t> requested{};
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
        /// Returns `true` if triangulation data was sent to Notehub in the most
        /// recent sync.
        ///
        /// @since{6.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(6, 1, 1)
        [[deprecated("requires firmware >= 6.1.1")]]
#endif
        note::ResponseField<bool> scan{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        /// If the Notecard is in a Penalty Box, the number of seconds until the
        /// penalty condition ends.
        ///
        /// @since{4.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
        [[deprecated("requires firmware >= 4.1.1")]]
#endif
        note::ResponseField<note::json_int_t> seconds{};
#endif
        /// The status of the current or previous sync. Refer to this listing
        /// for the meaning of the various status codes returned (e.g. `{sync-
        /// end}`).
        note::ResponseField<note::string_view> status{};
        /// `true` if the notecard has unsynchronized notes, or requires a sync
        /// to set its internal clock.
        note::ResponseField<bool> sync{};
        /// Time of the last sync completion. Will only populate if the Notecard
        /// has completed a sync to Notehub to obtain the time.
        note::ResponseField<note::json_int_t> time{};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#if !NOTE_NO_JSON_TREE
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            if (reader_->has("alert")) rsp.alert = reader_->get_bool("alert");
            if (reader_->has("completed")) rsp.completed = reader_->get_int("completed");
            if (reader_->has("mode")) rsp.mode = reader_->get_string("mode");
            if (reader_->has("requested")) rsp.requested = reader_->get_int("requested");
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
            if (reader_->has("scan")) rsp.scan = reader_->get_bool("scan");
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            if (reader_->has("seconds")) rsp.seconds = reader_->get_int("seconds");
#endif
            if (reader_->has("status")) rsp.status = reader_->get_string("status");
            if (reader_->has("sync")) rsp.sync = reader_->get_bool("sync");
            if (reader_->has("time")) rsp.time = reader_->get_int("time");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }
#pragma GCC diagnostic pop

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            if (reader_.has("alert")) rsp.alert = reader_.get_bool("alert");
            if (reader_.has("completed")) rsp.completed = reader_.get_int("completed");
            if (reader_.has("mode")) rsp.mode = reader_.get_string("mode");
            if (reader_.has("requested")) rsp.requested = reader_.get_int("requested");
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
            if (reader_.has("scan")) rsp.scan = reader_.get_bool("scan");
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            if (reader_.has("seconds")) rsp.seconds = reader_.get_int("seconds");
#endif
            if (reader_.has("status")) rsp.status = reader_.get_string("status");
            if (reader_.has("sync")) rsp.sync = reader_.get_bool("sync");
            if (reader_.has("time")) rsp.time = reader_.get_int("time");
            return rsp;
        }
#pragma GCC diagnostic pop
#endif // !NOTE_NO_JSON_TREE

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {}
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_mode) == k_) { rsp.mode = v_; return; }
                if (note::flash(keys_::rsp_status) == k_) { rsp.status = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                if (note::flash(keys_::rsp_alert) == k_) { rsp.alert = v_; return; }
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_scan) == k_) { rsp.scan = v_; return; }
#endif
                if (note::flash(keys_::rsp_sync) == k_) { rsp.sync = v_; return; }
            }
            NOTE_SINK_NOINLINE void on_number(::note::string_view k_, ::note::string_view raw_) {
                if (note::flash(keys_::rsp_completed) == k_) { rsp.completed = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_requested) == k_) { rsp.requested = ::note::parse_int(raw_); return; }
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_seconds) == k_) { rsp.seconds = ::note::parse_int(raw_); return; }
#endif
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = ::note::parse_int(raw_); return; }
            }
            NOTE_SINK_NOINLINE void on_int(::note::string_view k_, ::note::json_int_t v_) {
                if (note::flash(keys_::rsp_completed) == k_) { rsp.completed = v_; return; }
                if (note::flash(keys_::rsp_requested) == k_) { rsp.requested = v_; return; }
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
                if (note::flash(keys_::rsp_seconds) == k_) { rsp.seconds = v_; return; }
#endif
                if (note::flash(keys_::rsp_time) == k_) { rsp.time = v_; return; }
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };
#pragma GCC diagnostic pop

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
        void intern_strings(::note::StringPool& pool) {
            if (!mode.empty()) mode = pool.intern(mode);
            if (!status.empty()) status = pool.intern(status);
        }
#pragma GCC diagnostic pop

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"alert\":");
            n += note::detail::print_json_value(p, alert.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"completed\":");
            n += note::detail::print_json_value(p, completed.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"mode\":");
            n += note::detail::print_json_value(p, mode.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"requested\":");
            n += note::detail::print_json_value(p, requested.value());
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"scan\":");
            n += note::detail::print_json_value(p, scan.value());
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"seconds\":");
            n += note::detail::print_json_value(p, seconds.value());
#endif
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"status\":");
            n += note::detail::print_json_value(p, status.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"sync\":");
            n += note::detail::print_json_value(p, sync.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"time\":");
            n += note::detail::print_json_value(p, time.value());
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_JSON_TREE
    private:
        std::unique_ptr<JsonReader> reader_;
#endif
    };

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<Response> — boolean-convertible to true on success;
    /// dereference (or use member-of-pointer ->) to read response fields,
    /// or call .error() to inspect the ErrorInfo on failure.
    ApiResult<Response> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const HubSyncStatus&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (sync) {
            n += p.print(",\"sync\":");
            n += note::detail::print_json_value(p, *sync);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline HubSyncStatus& HubSyncStatus::sync_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSyncStatus*>(
        reinterpret_cast<char*>(this) - offsetof(HubSyncStatus, sync));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::HubSyncStatus> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::HubSyncStatus::keys_::rsp_alert, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, alert)), ::note::FieldType::Bool},
        {::note::api::HubSyncStatus::keys_::rsp_completed, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, completed)), ::note::FieldType::Int},
        {::note::api::HubSyncStatus::keys_::rsp_mode, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, mode)), ::note::FieldType::String},
        {::note::api::HubSyncStatus::keys_::rsp_requested, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, requested)), ::note::FieldType::Int},
#if NOTE_API_VERSION >= NOTE_VERSION(6, 1, 1) || !defined(NOTE_API_STRICT)
        {::note::api::HubSyncStatus::keys_::rsp_scan, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, scan)), ::note::FieldType::Bool},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        {::note::api::HubSyncStatus::keys_::rsp_seconds, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, seconds)), ::note::FieldType::Int},
#endif
        {::note::api::HubSyncStatus::keys_::rsp_status, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, status)), ::note::FieldType::String},
        {::note::api::HubSyncStatus::keys_::rsp_sync, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, sync)), ::note::FieldType::Bool},
        {::note::api::HubSyncStatus::keys_::rsp_time, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus::Response, time)), ::note::FieldType::Int},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::HubSyncStatus::keys_::sync, static_cast<uint16_t>(offsetof(::note::api::HubSyncStatus, sync)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void HubSyncStatus::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<HubSyncStatus>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename HubSyncStatus::Response> HubSyncStatus::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<HubSyncStatus>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> HubSyncStatus::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<HubSyncStatus>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
