// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Manually initiates a sync with Notehub.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct HubSync {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "hub.sync";
        static constexpr char allow[] NOTE_FLASH_ATTR = "allow";
        static constexpr char in[] NOTE_FLASH_ATTR = "in";
        static constexpr char out[] NOTE_FLASH_ATTR = "out";
    };

    static constexpr string_view notecard_request = "hub.sync";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::NonIdempotent;
    static constexpr RadiosSupport radios{};
    static constexpr Firmware min_firmware{};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// Set to `true` to remove the Notecard from certain types of penalty boxes
    /// (the default is `false`).
    struct allow_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to remove the Notecard from certain types of penalty
        /// boxes (the default is `false`).
        HubSync& operator()(bool v);
    } allow{};
    /// Set to `true` to only sync pending inbound Notefiles. Required when
    /// using NTN mode with Starnote to check for inbound Notefiles.
    struct in_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to only sync pending inbound Notefiles. Required when
        /// using NTN mode with Starnote to check for inbound Notefiles.
        HubSync& operator()(bool v);
    } in{};
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
    /// Set to `true` to only sync pending outbound Notefiles.
    ///
    /// @since{7.2.1}
#if NOTE_API_VERSION < NOTE_VERSION(7, 2, 1)
    [[deprecated("requires firmware >= 7.2.1")]]
#endif
    struct out_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to only sync pending outbound Notefiles.
        ///
        /// @since{7.2.1}
        HubSync& operator()(bool v);
    } out{};
#endif


#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "allow") return note::dyn_field_for(allow);
        if (k_ == "in") return note::dyn_field_for(in);
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "out") return note::dyn_field_for(out);
#endif
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<void> — boolean-convertible to true on success;
    /// call .error() to inspect the ErrorInfo on failure.
    ApiResult<void> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const HubSync&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (allow) {
            n += p.print(",\"allow\":");
            n += note::detail::print_json_value(p, *allow);
        }
        if (in) {
            n += p.print(",\"in\":");
            n += note::detail::print_json_value(p, *in);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
        if (out) {
            n += p.print(",\"out\":");
            n += note::detail::print_json_value(p, *out);
        }
#endif
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline HubSync& HubSync::allow_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSync*>(
        reinterpret_cast<char*>(this) - offsetof(HubSync, allow));
}
inline HubSync& HubSync::in_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSync*>(
        reinterpret_cast<char*>(this) - offsetof(HubSync, in));
}
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
inline HubSync& HubSync::out_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSync*>(
        reinterpret_cast<char*>(this) - offsetof(HubSync, out));
}
#endif
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::HubSync> {
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::HubSync::keys_::allow, static_cast<uint16_t>(offsetof(::note::api::HubSync, allow)), ::note::ReqFieldType::Bool},
            {::note::api::HubSync::keys_::in, static_cast<uint16_t>(offsetof(::note::api::HubSync, in)), ::note::ReqFieldType::Bool},
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSync::keys_::out, static_cast<uint16_t>(offsetof(::note::api::HubSync, out)), ::note::ReqFieldType::Bool},
#endif
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_void_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, ::note::detail::NcErrorCapture&, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline void HubSync::build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(7, 2, 1) || !defined(NOTE_API_STRICT)
#endif
    using meta_ = ::note::detail::request_traits<HubSync>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}
#pragma GCC diagnostic pop

#if NOTE_SINGLETON
inline ApiResult<void> HubSync::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    ::note::detail::NcErrorCapture nc_err_;
    using meta_ = ::note::detail::request_traits<HubSync>;
    auto rv_ = meta_::execute_void_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, nc_err_, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<void>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    return ApiResult<void>{};
}
inline Result<void> HubSync::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<HubSync>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
