// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/voltage_variable.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// The hub.set request is the primary method for controlling the Notecard's
/// Notehub connection and sync behavior.
///
/// @skus{CELL,CELL+WIFI,LORA,SKYLO,WIFI}
struct HubSet {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "hub.set";
        static constexpr char align[] NOTE_FLASH_ATTR = "align";
        static constexpr char details[] NOTE_FLASH_ATTR = "details";
        static constexpr char duration[] NOTE_FLASH_ATTR = "duration";
        static constexpr char host[] NOTE_FLASH_ATTR = "host";
        static constexpr char inbound[] NOTE_FLASH_ATTR = "inbound";
        static constexpr char mode[] NOTE_FLASH_ATTR = "mode";
        static constexpr char off[] NOTE_FLASH_ATTR = "off";
        static constexpr char on[] NOTE_FLASH_ATTR = "on";
        static constexpr char outbound[] NOTE_FLASH_ATTR = "outbound";
        static constexpr char product[] NOTE_FLASH_ATTR = "product";
        static constexpr char seconds[] NOTE_FLASH_ATTR = "seconds";
        static constexpr char sn[] NOTE_FLASH_ATTR = "sn";
        static constexpr char sync[] NOTE_FLASH_ATTR = "sync";
        static constexpr char umin[] NOTE_FLASH_ATTR = "umin";
        static constexpr char uoff[] NOTE_FLASH_ATTR = "uoff";
        static constexpr char uperiodic[] NOTE_FLASH_ATTR = "uperiodic";
        static constexpr char version[] NOTE_FLASH_ATTR = "version";
        static constexpr char vinbound[] NOTE_FLASH_ATTR = "vinbound";
        static constexpr char voutbound[] NOTE_FLASH_ATTR = "voutbound";
    };

    static constexpr string_view notecard_request = "hub.set";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios{};
    static constexpr Firmware min_firmware{};

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif


    /// Use `true` to align syncs on a regular time-periodic cycle.
    struct align_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Use `true` to align syncs on a regular time-periodic cycle.
        HubSet& operator()(bool v);
    } align{};
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
    /// When using Notecard LoRa you can use this argument to provide
    /// information about an alternative LoRaWAN server or service you would
    /// like the Notecard to use. The argument you provide must be a JSON object
    /// with three keys, "deveui", "appeui", and "appkey", all of which are
    /// hexadecimal strings with no leading 0x. For example:
    ///
    /// `{"deveui":"0080E11500088B37","appeui":"6E6F746563617264","appkey":"0008
    /// 8B37"}`
    ///
    /// The LoRaWAN details you send to a Notecard become part of its permanent
    /// configuration, and survive factory resets. You can reset a Notecard's
    /// LoRaWAN details to its default values by providing a `"-"` for the
    /// details argument.
    ///
    /// @since{6.2.3}
#if NOTE_API_VERSION < NOTE_VERSION(6, 2, 3)
    [[deprecated("requires firmware >= 6.2.3")]]
#endif
    struct details_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// When using Notecard LoRa you can use this argument to provide
        /// information about an alternative LoRaWAN server or service you would
        /// like the Notecard to use. The argument you provide must be a JSON
        /// object with three keys, "deveui", "appeui", and "appkey", all of
        /// which are hexadecimal strings with no leading 0x. For example:
        ///
        /// `{"deveui":"0080E11500088B37","appeui":"6E6F746563617264","appkey":"
        /// 00088B37"}`
        ///
        /// The LoRaWAN details you send to a Notecard become part of its
        /// permanent configuration, and survive factory resets. You can reset a
        /// Notecard's LoRaWAN details to its default values by providing a
        /// `"-"` for the details argument.
        ///
        /// @since{6.2.3}
        HubSet& operator()(note::string_view v);
    } details{};
#endif
    /// When in `continuous` mode, the amount of time, in minutes, of each
    /// session (the minimum allowed value is `15`). When this time elapses, the
    /// Notecard gracefully ends the current session and starts a new one in
    /// order to sync session-specific data to Notehub.
    struct duration_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// When in `continuous` mode, the amount of time, in minutes, of each
        /// session (the minimum allowed value is `15`). When this time elapses,
        /// the Notecard gracefully ends the current session and starts a new
        /// one in order to sync session-specific data to Notehub.
        HubSet& operator()(note::json_int_t v);
    } duration{};
    /// The URL of the Notehub service. Use `"-"` to reset to the default value.
    struct host_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// The URL of the Notehub service. Use `"-"` to reset to the default
        /// value.
        HubSet& operator()(note::string_view v);
    } host{};
    /// The max wait time, in minutes, to sync inbound data from Notehub.
    /// Explicit syncs (e.g. using `hub.sync`) do not affect this cadence.
    ///
    /// When in `periodic` or `continuous` mode this argument is required,
    /// otherwise the Notecard will function as if it is in `minimum` mode as it
    /// pertains to syncing behavior.
    ///
    /// Use `-1` to reset the value back to its default of `0`.
    ///
    /// A value of `0` means that the Notecard will never sync inbound data
    /// unless explicitly told to do so (e.g. using `hub.sync`).
    struct inbound_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// The max wait time, in minutes, to sync inbound data from Notehub.
        /// Explicit syncs (e.g. using `hub.sync`) do not affect this cadence.
        ///
        /// When in `periodic` or `continuous` mode this argument is required,
        /// otherwise the Notecard will function as if it is in `minimum` mode
        /// as it pertains to syncing behavior.
        ///
        /// Use `-1` to reset the value back to its default of `0`.
        ///
        /// A value of `0` means that the Notecard will never sync inbound data
        /// unless explicitly told to do so (e.g. using `hub.sync`).
        HubSet& operator()(note::json_int_t v);
    } inbound{};
    /// The Notecard's synchronization mode.
    ///
    /// NOTE: The Notecard must be in `periodic` or `continuous` mode to use the
    /// onboard GPS module.
    // mode: periodic | continuous | minimum | off | dfu | -
    struct mode_t : Field<note::string_view> {
#if __cplusplus >= 202002L && !defined(__clang__)
        constexpr mode_t() = default;
        template<std::size_t N>
        consteval mode_t(const char (&s)[N])
            : Field<note::string_view>(note::string_view(s, N - 1)) {
            note::string_view sv(s, N - 1);
            if (sv != "periodic" && sv != "continuous" && sv != "minimum" && sv != "off" && sv != "dfu" && sv != "-")
                throw "hub.set: invalid value for 'mode'";
        }
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, mode_t>)
        constexpr mode_t(U&& v) : Field<note::string_view>(note::string_view(std::forward<U>(v))) {}
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, mode_t>)
        mode_t& operator=(U&& v) {
            Field<note::string_view>::operator=(note::string_view(std::forward<U>(v)));
            return *this;
        }
        mode_t& operator=(std::nullopt_t) { Field<note::string_view>::reset(); return *this; }
        mode_t(const mode_t&) = default;
        mode_t& operator=(const mode_t&) = default;
        mode_t(mode_t&&) = default;
        mode_t& operator=(mode_t&&) = default;
#else
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
#endif
        static constexpr note::string_view periodic{"periodic"};
        static constexpr note::string_view continuous{"continuous"};
        static constexpr note::string_view minimum{"minimum"};
        static constexpr note::string_view off{"off"};
        static constexpr note::string_view dfu{"dfu"};
        static constexpr note::string_view _{"-"};
        /// The Notecard's synchronization mode.
        ///
        /// NOTE: The Notecard must be in `periodic` or `continuous` mode to use
        /// the onboard GPS module.
        HubSet& operator()(note::string_view v);
    } mode{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
    /// Set to `true` to manually instruct the Notecard to resume periodic mode
    /// after a web transaction has completed.
    ///
    /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
    [[deprecated("requires firmware >= 3.4.1")]]
#endif
    struct off_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to manually instruct the Notecard to resume periodic
        /// mode after a web transaction has completed.
        ///
        /// @since{3.4.1}
        HubSet& operator()(bool v);
    } off{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
    /// If in `periodic` mode, used to temporarily switch the Notecard to
    /// `continuous` mode to perform a web transaction.
    ///
    /// Ignored if the Notecard is already in `continuous` mode or if the
    /// Notecard is NOT performing a web transaction.
    ///
    /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
    [[deprecated("requires firmware >= 3.4.1")]]
#endif
    struct on_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// If in `periodic` mode, used to temporarily switch the Notecard to
        /// `continuous` mode to perform a web transaction.
        ///
        /// Ignored if the Notecard is already in `continuous` mode or if the
        /// Notecard is NOT performing a web transaction.
        ///
        /// @since{3.4.1}
        HubSet& operator()(bool v);
    } on{};
#endif
    /// The max wait time, in minutes, to sync outbound data from the Notecard.
    /// Explicit syncs (e.g. using `hub.sync`) do not affect this cadence.
    ///
    /// When in `periodic` or `continuous` mode this argument is required,
    /// otherwise the Notecard will function as if it is in `minimum` mode as it
    /// pertains to syncing behavior.
    ///
    /// Use `-1` to reset the value back to its default of `0`.
    ///
    /// A value of `0` means that the Notecard will never sync outbound data
    /// unless explicitly told to do so (e.g. using `hub.sync`).
    struct outbound_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// The max wait time, in minutes, to sync outbound data from the
        /// Notecard. Explicit syncs (e.g. using `hub.sync`) do not affect this
        /// cadence.
        ///
        /// When in `periodic` or `continuous` mode this argument is required,
        /// otherwise the Notecard will function as if it is in `minimum` mode
        /// as it pertains to syncing behavior.
        ///
        /// Use `-1` to reset the value back to its default of `0`.
        ///
        /// A value of `0` means that the Notecard will never sync outbound data
        /// unless explicitly told to do so (e.g. using `hub.sync`).
        HubSet& operator()(note::json_int_t v);
    } outbound{};
    /// A Notehub-managed unique identifier that is used to match Devices with
    /// Projects. This string is used during a device's auto-provisioning to
    /// find the Notehub Project that, once provisioned, will securely manage
    /// the device and its data.
    struct product_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// A Notehub-managed unique identifier that is used to match Devices
        /// with Projects. This string is used during a device's auto-
        /// provisioning to find the Notehub Project that, once provisioned,
        /// will securely manage the device and its data.
        HubSet& operator()(note::string_view v);
    } product{};
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
    /// If in `periodic` mode and using `on` above, the number of seconds to run
    /// in continuous mode before switching back to periodic mode. If not set, a
    /// default of 300 seconds is used. Ignored if the Notecard is already in
    /// continuous mode.
    ///
    /// @since{3.4.1}
#if NOTE_API_VERSION < NOTE_VERSION(3, 4, 1)
    [[deprecated("requires firmware >= 3.4.1")]]
#endif
    struct seconds_t : Field<note::json_int_t> {
        using Field<note::json_int_t>::Field;
        using Field<note::json_int_t>::operator=;
        /// If in `periodic` mode and using `on` above, the number of seconds to
        /// run in continuous mode before switching back to periodic mode. If
        /// not set, a default of 300 seconds is used. Ignored if the Notecard
        /// is already in continuous mode.
        ///
        /// @since{3.4.1}
        HubSet& operator()(note::json_int_t v);
    } seconds{};
#endif
    /// The end product's serial number.
    struct sn_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// The end product's serial number.
        HubSet& operator()(note::string_view v);
    } sn{};
    /// If in `continuous` mode, automatically and immediately sync each time an
    /// inbound Notefile change is detected on Notehub.
    ///
    /// NOTE: The `sync` argument is not supported when a Notecard is in NTN
    /// mode.
    struct sync_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// If in `continuous` mode, automatically and immediately sync each
        /// time an inbound Notefile change is detected on Notehub.
        ///
        /// NOTE: The `sync` argument is not supported when a Notecard is in NTN
        /// mode.
        HubSet& operator()(bool v);
    } sync{};
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
    /// Set to `true` to use USB/line power variable sync behavior, enabling the
    /// Notecard to stay in `continuous` mode when connected to USB/line power
    /// and fallback to `minimum` mode when disconnected.
    ///
    /// @since{4.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
    [[deprecated("requires firmware >= 4.1.1")]]
#endif
    struct umin_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to use USB/line power variable sync behavior, enabling
        /// the Notecard to stay in `continuous` mode when connected to USB/line
        /// power and fallback to `minimum` mode when disconnected.
        ///
        /// @since{4.1.1}
        HubSet& operator()(bool v);
    } umin{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
    /// Set to `true` to use USB/line power variable sync behavior, enabling the
    /// Notecard to stay in `continuous` mode when connected to USB/line power
    /// and fallback to `off` mode when disconnected.
    ///
    /// @since{4.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
    [[deprecated("requires firmware >= 4.1.1")]]
#endif
    struct uoff_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to use USB/line power variable sync behavior, enabling
        /// the Notecard to stay in `continuous` mode when connected to USB/line
        /// power and fallback to `off` mode when disconnected.
        ///
        /// @since{4.1.1}
        HubSet& operator()(bool v);
    } uoff{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
    /// Set to `true` to use USB/line power variable sync behavior, enabling the
    /// Notecard to stay in `continuous` mode when connected to USB/line power
    /// and fallback to `periodic` mode when disconnected.
    ///
    /// @since{4.1.1}
#if NOTE_API_VERSION < NOTE_VERSION(4, 1, 1)
    [[deprecated("requires firmware >= 4.1.1")]]
#endif
    struct uperiodic_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// Set to `true` to use USB/line power variable sync behavior, enabling
        /// the Notecard to stay in `continuous` mode when connected to USB/line
        /// power and fallback to `periodic` mode when disconnected.
        ///
        /// @since{4.1.1}
        HubSet& operator()(bool v);
    } uperiodic{};
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
    /// The version of your host firmware. The value provided will appear on
    /// your device in Notehub under the "Host Firmware" tab.
    ///
    /// You may pass a simple version number string (e.g. "1.0.0.0"), or an
    /// object with detailed information about the firmware image. If you
    /// provide an object it must take the following form.
    ///
    /// `{"org":"my-organization","product":"My Product","description":"A
    /// description of the image","version":"1.2.4","built":"Jan 01 2025
    /// 01:02:03","vermajor":1,"verminor":2,"verpatch":4,"verbuild":
    /// 5,"builder":"The Builder"}`
    ///
    /// If your project uses Notecard Outboard Firmware Update, you can
    /// alternatively use the `dfu.status` request to set your host firmware
    /// version.
    ///
    /// @since{7.3.1}
#if NOTE_API_VERSION < NOTE_VERSION(7, 3, 1)
    [[deprecated("requires firmware >= 7.3.1")]]
#endif
    struct version_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// The version of your host firmware. The value provided will appear on
        /// your device in Notehub under the "Host Firmware" tab.
        ///
        /// You may pass a simple version number string (e.g. "1.0.0.0"), or an
        /// object with detailed information about the firmware image. If you
        /// provide an object it must take the following form.
        ///
        /// `{"org":"my-organization","product":"My Product","description":"A
        /// description of the image","version":"1.2.4","built":"Jan 01 2025
        /// 01:02:03","vermajor":1,"verminor":2,"verpatch":4,"verbuild":
        /// 5,"builder":"The Builder"}`
        ///
        /// If your project uses Notecard Outboard Firmware Update, you can
        /// alternatively use the `dfu.status` request to set your host firmware
        /// version.
        ///
        /// @since{7.3.1}
        HubSet& operator()(note::string_view v);
    } version{};
#endif
    /// Overrides `inbound` with a voltage-variable value. Use `"-"` to clear
    /// this value.
    ///
    /// NOTE: Setting voltage-variable values is not supported on Notecard XP.
    struct vinbound_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// Overrides `inbound` with a voltage-variable value. Use `"-"` to
        /// clear this value.
        ///
        /// NOTE: Setting voltage-variable values is not supported on Notecard
        /// XP.
        HubSet& operator()(note::string_view v);
        /// Overrides `inbound` with a voltage-variable value. Use `"-"` to
        /// clear this value.
        ///
        /// NOTE: Setting voltage-variable values is not supported on Notecard
        /// XP.
        HubSet& operator()(const note::VoltageVariable& v);
        vinbound_t& usb(int32_t minutes);
        vinbound_t& high(int32_t minutes);
        vinbound_t& normal(int32_t minutes);
        vinbound_t& low(int32_t minutes);
        vinbound_t& dead(int32_t minutes);
        note::VoltageVariable vv_{};
    } vinbound{};
    /// Overrides `outbound` with a voltage-variable value. Use `"-"` to clear
    /// this value.
    ///
    /// NOTE: Setting voltage-variable values is not supported on Notecard XP.
    struct voutbound_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        /// Overrides `outbound` with a voltage-variable value. Use `"-"` to
        /// clear this value.
        ///
        /// NOTE: Setting voltage-variable values is not supported on Notecard
        /// XP.
        HubSet& operator()(note::string_view v);
        /// Overrides `outbound` with a voltage-variable value. Use `"-"` to
        /// clear this value.
        ///
        /// NOTE: Setting voltage-variable values is not supported on Notecard
        /// XP.
        HubSet& operator()(const note::VoltageVariable& v);
        voutbound_t& usb(int32_t minutes);
        voutbound_t& high(int32_t minutes);
        voutbound_t& normal(int32_t minutes);
        voutbound_t& low(int32_t minutes);
        voutbound_t& dead(int32_t minutes);
        note::VoltageVariable vv_{};
    } voutbound{};

    // Valid values for 'mode':
    //   "periodic" — Periodically connect to the Notehub. This is the default value set on...
    //   "continuous" — Enables an always-on network connection, for high power devices. Outb...
    //   "minimum" — Disables periodic connection. The Notecard will not sync until it rec...
    //   "off" — Disables automatic and manual syncs. `hub.sync` requests will be igno...
    //   "dfu" — Puts the Notecard in DFU mode for IAP host MCU firmware updates. This...
    //   "-" — Resets the mode to the default value (`periodic`).
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMode(const char* v) {
        note::string_view sv{v};
        if (sv != "periodic" && sv != "continuous" && sv != "minimum" && sv != "off" && sv != "dfu" && sv != "-")
            throw "hub.set: invalid value for 'mode'";
        return sv;
    }
#endif

    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
    auto& allowContinuous() { on = true; return *this; }
    auto& resumePeriodic() { off = true; return *this; }
    auto& allowContinuous(bool v_) { if (v_) on = true; else off = true; return *this; }
#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "align") return note::dyn_field_for(align);
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
        if (k_ == "details") return note::dyn_field_for(details);
#endif
        if (k_ == "duration") return note::dyn_field_for(duration);
        if (k_ == "host") return note::dyn_field_for(host);
        if (k_ == "inbound") return note::dyn_field_for(inbound);
        if (k_ == "mode") return note::dyn_field_for(mode);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "off") return note::dyn_field_for(off);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "on") return note::dyn_field_for(on);
#endif
        if (k_ == "outbound") return note::dyn_field_for(outbound);
        if (k_ == "product") return note::dyn_field_for(product);
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "seconds") return note::dyn_field_for(seconds);
#endif
        if (k_ == "sn") return note::dyn_field_for(sn);
        if (k_ == "sync") return note::dyn_field_for(sync);
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "umin") return note::dyn_field_for(umin);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "uoff") return note::dyn_field_for(uoff);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "uperiodic") return note::dyn_field_for(uperiodic);
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
        if (k_ == "version") return note::dyn_field_for(version);
#endif
        if (k_ == "vinbound") return note::dyn_field_for(vinbound);
        if (k_ == "voutbound") return note::dyn_field_for(voutbound);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    using Response = void;

#if NOTE_SINGLETON
    private:
    /// Singleton void execute — shared thunk, no per-type instantiation.
    static inline Result<void>(*execute_void_fn_)(void*, ::note::string_view, BuildFn, void*, ::note::detail::NcErrorCapture&, ::note::Safety);
    public:
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<void> — boolean-convertible to true on success;
    /// call .error() to inspect the ErrorInfo on failure.
    ApiResult<void> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        ::note::detail::NcErrorCapture nc_err_;
        auto rv_ = execute_void_fn_(nc_, notecard_request, fn_, &build_, nc_err_, safety);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<void>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        return ApiResult<void>{};
    }
    private:
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
    public:
#else
    ApiResult<Response>(*execute_fn_)(void*, const HubSet&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (align) {
            n += p.print(",\"align\":");
            n += note::detail::print_json_value(p, *align);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
        if (details) {
            n += p.print(",\"details\":");
            n += note::detail::print_json_value(p, *details);
        }
#endif
        if (duration) {
            n += p.print(",\"duration\":");
            n += note::detail::print_json_value(p, *duration);
        }
        if (host) {
            n += p.print(",\"host\":");
            n += note::detail::print_json_value(p, *host);
        }
        if (inbound) {
            n += p.print(",\"inbound\":");
            n += note::detail::print_json_value(p, *inbound);
        }
        if (mode) {
            n += p.print(",\"mode\":");
            n += note::detail::print_json_value(p, *mode);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (off) {
            n += p.print(",\"off\":");
            n += note::detail::print_json_value(p, *off);
        }
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (on) {
            n += p.print(",\"on\":");
            n += note::detail::print_json_value(p, *on);
        }
#endif
        if (outbound) {
            n += p.print(",\"outbound\":");
            n += note::detail::print_json_value(p, *outbound);
        }
        if (product) {
            n += p.print(",\"product\":");
            n += note::detail::print_json_value(p, *product);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
        if (seconds) {
            n += p.print(",\"seconds\":");
            n += note::detail::print_json_value(p, *seconds);
        }
#endif
        if (sn) {
            n += p.print(",\"sn\":");
            n += note::detail::print_json_value(p, *sn);
        }
        if (sync) {
            n += p.print(",\"sync\":");
            n += note::detail::print_json_value(p, *sync);
        }
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (umin) {
            n += p.print(",\"umin\":");
            n += note::detail::print_json_value(p, *umin);
        }
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (uoff) {
            n += p.print(",\"uoff\":");
            n += note::detail::print_json_value(p, *uoff);
        }
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
        if (uperiodic) {
            n += p.print(",\"uperiodic\":");
            n += note::detail::print_json_value(p, *uperiodic);
        }
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
        if (version) {
            n += p.print(",\"version\":");
            n += note::detail::print_json_value(p, *version);
        }
#endif
        if (vinbound) {
            n += p.print(",\"vinbound\":");
            n += note::detail::print_json_value(p, *vinbound);
        }
        if (voutbound) {
            n += p.print(",\"voutbound\":");
            n += note::detail::print_json_value(p, *voutbound);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline HubSet& HubSet::align_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, align));
}
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::details_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, details));
}
#endif
inline HubSet& HubSet::duration_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, duration));
}
inline HubSet& HubSet::host_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, host));
}
inline HubSet& HubSet::inbound_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, inbound));
}
inline HubSet& HubSet::mode_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, mode));
}
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::off_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, off));
}
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::on_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, on));
}
#endif
inline HubSet& HubSet::outbound_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, outbound));
}
inline HubSet& HubSet::product_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, product));
}
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::seconds_t::operator()(note::json_int_t v) {
    Field<note::json_int_t>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, seconds));
}
#endif
inline HubSet& HubSet::sn_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, sn));
}
inline HubSet& HubSet::sync_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, sync));
}
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::umin_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, umin));
}
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::uoff_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, uoff));
}
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::uperiodic_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, uperiodic));
}
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
inline HubSet& HubSet::version_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, version));
}
#endif
inline HubSet& HubSet::vinbound_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, vinbound));
}
inline HubSet& HubSet::vinbound_t::operator()(const note::VoltageVariable& v) {
    vv_ = v;
    Field<note::string_view>::operator=(vv_.str());
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, vinbound));
}
inline HubSet::vinbound_t& HubSet::vinbound_t::usb(int32_t minutes) {
    vv_.usb(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::vinbound_t& HubSet::vinbound_t::high(int32_t minutes) {
    vv_.high(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::vinbound_t& HubSet::vinbound_t::normal(int32_t minutes) {
    vv_.normal(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::vinbound_t& HubSet::vinbound_t::low(int32_t minutes) {
    vv_.low(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::vinbound_t& HubSet::vinbound_t::dead(int32_t minutes) {
    vv_.dead(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet& HubSet::voutbound_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, voutbound));
}
inline HubSet& HubSet::voutbound_t::operator()(const note::VoltageVariable& v) {
    vv_ = v;
    Field<note::string_view>::operator=(vv_.str());
    return *reinterpret_cast<HubSet*>(
        reinterpret_cast<char*>(this) - offsetof(HubSet, voutbound));
}
inline HubSet::voutbound_t& HubSet::voutbound_t::usb(int32_t minutes) {
    vv_.usb(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::voutbound_t& HubSet::voutbound_t::high(int32_t minutes) {
    vv_.high(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::voutbound_t& HubSet::voutbound_t::normal(int32_t minutes) {
    vv_.normal(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::voutbound_t& HubSet::voutbound_t::low(int32_t minutes) {
    vv_.low(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
inline HubSet::voutbound_t& HubSet::voutbound_t::dead(int32_t minutes) {
    vv_.dead(minutes);
    Field<note::string_view>::operator=(vv_.str());
    return *this;
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::HubSet> {
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::HubSet::keys_::align, static_cast<uint16_t>(offsetof(::note::api::HubSet, align)), ::note::ReqFieldType::Bool},
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::details, static_cast<uint16_t>(offsetof(::note::api::HubSet, details)), ::note::ReqFieldType::String},
#endif
            {::note::api::HubSet::keys_::duration, static_cast<uint16_t>(offsetof(::note::api::HubSet, duration)), ::note::ReqFieldType::Int},
            {::note::api::HubSet::keys_::host, static_cast<uint16_t>(offsetof(::note::api::HubSet, host)), ::note::ReqFieldType::String},
            {::note::api::HubSet::keys_::inbound, static_cast<uint16_t>(offsetof(::note::api::HubSet, inbound)), ::note::ReqFieldType::Int},
            {::note::api::HubSet::keys_::mode, static_cast<uint16_t>(offsetof(::note::api::HubSet, mode)), ::note::ReqFieldType::String},
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::off, static_cast<uint16_t>(offsetof(::note::api::HubSet, off)), ::note::ReqFieldType::Bool},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::on, static_cast<uint16_t>(offsetof(::note::api::HubSet, on)), ::note::ReqFieldType::Bool},
#endif
            {::note::api::HubSet::keys_::outbound, static_cast<uint16_t>(offsetof(::note::api::HubSet, outbound)), ::note::ReqFieldType::Int},
            {::note::api::HubSet::keys_::product, static_cast<uint16_t>(offsetof(::note::api::HubSet, product)), ::note::ReqFieldType::String},
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::seconds, static_cast<uint16_t>(offsetof(::note::api::HubSet, seconds)), ::note::ReqFieldType::Int},
#endif
            {::note::api::HubSet::keys_::sn, static_cast<uint16_t>(offsetof(::note::api::HubSet, sn)), ::note::ReqFieldType::String},
            {::note::api::HubSet::keys_::sync, static_cast<uint16_t>(offsetof(::note::api::HubSet, sync)), ::note::ReqFieldType::Bool},
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::umin, static_cast<uint16_t>(offsetof(::note::api::HubSet, umin)), ::note::ReqFieldType::Bool},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::uoff, static_cast<uint16_t>(offsetof(::note::api::HubSet, uoff)), ::note::ReqFieldType::Bool},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::uperiodic, static_cast<uint16_t>(offsetof(::note::api::HubSet, uperiodic)), ::note::ReqFieldType::Bool},
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
            {::note::api::HubSet::keys_::version, static_cast<uint16_t>(offsetof(::note::api::HubSet, version)), ::note::ReqFieldType::String},
#endif
            {::note::api::HubSet::keys_::vinbound, static_cast<uint16_t>(offsetof(::note::api::HubSet, vinbound)), ::note::ReqFieldType::String},
            {::note::api::HubSet::keys_::voutbound, static_cast<uint16_t>(offsetof(::note::api::HubSet, voutbound)), ::note::ReqFieldType::String},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
};
} // namespace note::detail
namespace note::api {

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
inline void HubSet::build(JsonBuilder& b) const {
#if NOTE_API_VERSION >= NOTE_VERSION(6, 2, 3) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(3, 4, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(4, 1, 1) || !defined(NOTE_API_STRICT)
#endif
#if NOTE_API_VERSION >= NOTE_VERSION(7, 3, 1) || !defined(NOTE_API_STRICT)
#endif
    using meta_ = ::note::detail::request_traits<HubSet>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}
#pragma GCC diagnostic pop



} // namespace note::api
