// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

#ifndef NOTE_EXTRAS
#define NOTE_EXTRAS 1
#endif
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Displays the current status of a Notecard's connection to a paired Starnote.
///
/// @skus{CELL,CELL+WIFI,WIFI}
struct NtnStatus {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "ntn.status";
        static constexpr char rsp_err[] NOTE_FLASH_ATTR = "err";
        static constexpr char rsp_status[] NOTE_FLASH_ATTR = "status";
    };

    static constexpr string_view notecard_request = "ntn.status";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::ReadOnly;
    static constexpr Skus skus = Skus::from(Product::Cell, Product::CellWifi, Product::WiFi);

#if NOTE_SINGLETON
    static inline void* nc_;
#else
    void* nc_ = nullptr;
#endif



#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response showing current status of Notecard's connection to paired
    /// Starnote.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(48) +
            ::note::detail::arena_cost(80) +
            ::note::detail::arena_cost(64);  // error reserve

        /// This member is present if any errors have occurred while connecting
        /// to a paired Starnote, for example: `{"err":"no NTN module is
        /// connected {no-ntn-module}"}`
        note::ResponseField<note::string_view> err{};
        /// Details about a Notecard's connection to a paired Starnote, for
        /// example: `{"status":"{ntn-idle}{ntn-unknown-location}"}`
        note::ResponseField<note::string_view> status{};

#ifndef NOTE_NO_BUFFERED
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.err = reader_->get_string("err");
            rsp.status = reader_->get_string("status");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            rsp.err = reader_.get_string("err");
            rsp.status = reader_.get_string("status");
            return rsp;
        }
#endif // !NOTE_NO_BUFFERED

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {}
            NOTE_SINK_NOINLINE void on_string(::note::string_view k_, ::note::string_view v_) {
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_err) == k_) { rsp.err = v_; return; }
                if (note::flash(keys_::rsp_status) == k_) { rsp.status = v_; return; }
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!err.empty()) err = pool.intern(err);
            if (!status.empty()) status = pool.intern(status);
        }

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"err\":");
            n += note::detail::print_json_value(p, err.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"status\":");
            n += note::detail::print_json_value(p, status.value());
            n += p.print("}");
            return n;
        }
#endif

#ifndef NOTE_NO_BUFFERED
    private:
        std::unique_ptr<JsonReader> reader_;
#endif
    };
    static constexpr uint8_t field_count = 2;
    static const ::note::FieldDesc* field_descs_ptr() {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::FieldDesc table[] NOTE_FLASH_ATTR = {
            {keys_::rsp_err, static_cast<uint16_t>(offsetof(Response, err)), ::note::FieldType::String},
            {keys_::rsp_status, static_cast<uint16_t>(offsetof(Response, status)), ::note::FieldType::String},
        };
#pragma GCC diagnostic pop
        return table;
    }

#if NOTE_SINGLETON
    /// Singleton generic execute — shared thunk with body factory params.
    static inline Result<void>(*execute_generic_fn_)(void*, ::note::string_view, BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory);
    ApiResult<Response> execute() const {
        auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
        Response rsp_{};
        ::note::detail::NcErrorCapture nc_err_;
        bool exhausted_ = false;
        auto rv_ = execute_generic_fn_(nc_, notecard_request, fn_, &build_, &rsp_, field_descs_ptr(), field_count, nc_err_, exhausted_, nullptr, nullptr);
        if (!rv_) return ::note::Unexpected(rv_.error());
        if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
        if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
        return ApiResult<Response>(std::move(rsp_));
    }
    static inline Result<void>(*send_fn_)(void*, BuildFn, void*);
#else
    ApiResult<Response>(*execute_fn_)(void*, const NtnStatus&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    auto execute() const { return execute_fn_(nc_, *this); }
#endif
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }

    void build(JsonBuilder& b) const {
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
        (void)b;
    }


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        n += p.print("}");
        return n;
    }
#endif

};




} // namespace note::api
