// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once
#include <note/note_config.hpp>

// NOTE_EXTRAS default is set in note_config.hpp.
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/generic_builder.hpp>
#include <note/generic_sink.hpp>
#include <note/notecard.hpp>
#include <note/arena.hpp>
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {









/// Determines whether a Notecard should override a paired Starnote's GPS/GNSS
/// location with its own GPS/GNSS location. The paired Starnote uses its own
/// GPS/GNSS location by default.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct NtnGps {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "ntn.gps";
        static constexpr char off[] NOTE_FLASH_ATTR = "off";
        static constexpr char on[] NOTE_FLASH_ATTR = "on";
        static constexpr char rsp_off[] NOTE_FLASH_ATTR = "off";
        static constexpr char rsp_on[] NOTE_FLASH_ATTR = "on";
    };

    static constexpr string_view notecard_request = "ntn.gps";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::Idempotent;
    static constexpr RadiosSupport radios = RadiosSupport::from(Radios::Cell, Radios::CellWifi, Radios::Skylo, Radios::WiFi);
    static constexpr Firmware min_firmware = Firmware{6, 2, 3};

#if !NOTE_SINGLETON
    void* nc_ = nullptr;
#endif


    /// When `true`, a paired Starnote will use its own GPS/GNSS location. This
    /// is the default configuration.
    struct off_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// When `true`, a paired Starnote will use its own GPS/GNSS location.
        /// This is the default configuration.
        NtnGps& operator()(bool v);
    } off{};
    /// When `true`, a Starnote will use the GPS/GNSS location from its paired
    /// Notecard, instead of its own GPS/GNSS location.
    struct on_t : Field<bool> {
        using Field<bool>::Field;
        using Field<bool>::operator=;
        /// When `true`, a Starnote will use the GPS/GNSS location from its
        /// paired Notecard, instead of its own GPS/GNSS location.
        NtnGps& operator()(bool v);
    } on{};


    // Semantic convenience methods — generated from x-toggle / x-action metadata
    // (method names that match a field accessor are skipped to avoid redefinition)
    auto& useStarnoteGps() { off = true; return *this; }
    auto& useNotecardGps() { on = true; return *this; }
#if NOTE_EXTRAS
    /// Add an arbitrary key/value pair to the request, beyond the typed fields
    /// declared above. Useful for fields the schema doesn't yet model.
    /// Capacity is bounded by NOTE_EXTRAS_MAX; excess pairs are silently dropped.
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    /// String-literal overload of extra().
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    /// Index-style access to fields by wire name. Returns a DynField proxy
    /// usable for assignment; unknown keys are added as extras (subject to
    /// NOTE_EXTRAS_MAX). Prefer the typed setters above when possible.
    note::DynField operator[](note::string_view k_) {
        if (k_ == "off") return note::dyn_field_for(off);
        if (k_ == "on") return note::dyn_field_for(on);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response indicating current Starnote GPS/GNSS location configuration.
    struct Response {
        /// Compile-time arena budget for this response type.
        static constexpr size_t max_arena_size =
            ::note::detail::arena_cost(65);  // error reserve (+1 for null terminator)

        /// Returned and `true` if a paired Starnote will use its own GPS/GNSS
        /// location.
        note::ResponseField<bool> off{};
        /// Returned and `true` if a Starnote will use the GPS/GNSS location
        /// from its paired Notecard.
        note::ResponseField<bool> on{};

#if !NOTE_NO_JSON_TREE
        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            if (reader_->has("off")) rsp.off = reader_->get_bool("off");
            if (reader_->has("on")) rsp.on = reader_->get_bool("on");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            if (reader_.has("off")) rsp.off = reader_.get_bool("off");
            if (reader_.has("on")) rsp.on = reader_.get_bool("on");
            return rsp;
        }
#endif // !NOTE_NO_JSON_TREE

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::DefaultSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {
            }
            NOTE_SINK_NOINLINE void on_bool(::note::string_view k_, bool v_) {
                if (note::flash(keys_::rsp_off) == k_) { rsp.off = v_; return; }
                if (note::flash(keys_::rsp_on) == k_) { rsp.on = v_; return; }
            }
            NOTE_SINK_NOINLINE void reset() {
                rsp = Response{};
            }
        };

        void intern_strings(::note::StringPool&) {}

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"off\":");
            n += note::detail::print_json_value(p, off.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"on\":");
            n += note::detail::print_json_value(p, on.value());
            n += p.print("}");
            return n;
        }
#endif

#if !NOTE_NO_JSON_TREE
    private:
        std::unique_ptr<JsonReader> reader_;
#endif
    };

#if NOTE_SINGLETON
    /// Send this request to the Notecard and wait for a response.
    /// Returns an ApiResult<Response> — boolean-convertible to true on success;
    /// dereference (or use member-of-pointer ->) to read response fields,
    /// or call .error() to inspect the ErrorInfo on failure.
    ApiResult<Response> execute() const;
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const;
#else
    ApiResult<Response>(*execute_fn_)(void*, const NtnGps&) = nullptr;
    Result<void>(*send_fn_)(void*, BuildFn, void*) = nullptr;
    /// Send this request to the Notecard and wait for a response.
    auto execute() const { return execute_fn_(nc_, *this); }
    /// Send this request as a fire-and-forget command (cmd) — the Notecard
    /// processes it without sending a response. Lower power and bandwidth
    /// than execute() when you don't need the result.
    Result<void> command() const {
        auto build_ = [&](JsonBuilder& b_) {
            b_.add("cmd", notecard_request);
            this->build(b_);
        };
        BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
            (*static_cast<decltype(build_)*>(p_))(b_);
        };
        return send_fn_(nc_, fn_, &build_);
    }
#endif

    private:
    void build(JsonBuilder& b) const;
    public:


#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (off) {
            n += p.print(",\"off\":");
            n += note::detail::print_json_value(p, *off);
        }
        if (on) {
            n += p.print(",\"on\":");
            n += note::detail::print_json_value(p, *on);
        }
        n += p.print("}");
        return n;
    }
#endif

    private:
    friend class ::note::Notecard;
    template<typename> friend class ::note::StaticNotecard;
#if NOTE_NO_POLYMORPHIC || __cplusplus < 202002L
    template<typename> friend class ::note::Api;
#else
    template<typename, typename> friend class ::note::Api;
#endif
    public:

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline NtnGps& NtnGps::off_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<NtnGps*>(
        reinterpret_cast<char*>(this) - offsetof(NtnGps, off));
}
inline NtnGps& NtnGps::on_t::operator()(bool v) {
    Field<bool>::operator=(v);
    return *reinterpret_cast<NtnGps*>(
        reinterpret_cast<char*>(this) - offsetof(NtnGps, on));
}
#pragma GCC diagnostic pop

} // namespace note::api
namespace note::detail {
template<>
struct request_traits<::note::api::NtnGps> {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
    static constexpr ::note::FieldDesc field_descs_table_[] NOTE_FLASH_ATTR = {
        {::note::api::NtnGps::keys_::rsp_off, static_cast<uint16_t>(offsetof(::note::api::NtnGps::Response, off)), ::note::FieldType::Bool},
        {::note::api::NtnGps::keys_::rsp_on, static_cast<uint16_t>(offsetof(::note::api::NtnGps::Response, on)), ::note::FieldType::Bool},
    };
#pragma GCC diagnostic pop
    static constexpr uint8_t field_count = sizeof(field_descs_table_) / sizeof(field_descs_table_[0]);
    static const ::note::FieldDesc* field_descs_ptr() { return field_descs_table_; }
    static const ::note::ReqFieldDesc* req_field_descs_ptr_(uint8_t& n_out) {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
        static constexpr ::note::ReqFieldDesc table_[] NOTE_FLASH_ATTR = {
            {::note::api::NtnGps::keys_::off, static_cast<uint16_t>(offsetof(::note::api::NtnGps, off)), ::note::ReqFieldType::Bool},
            {::note::api::NtnGps::keys_::on, static_cast<uint16_t>(offsetof(::note::api::NtnGps, on)), ::note::ReqFieldType::Bool},
        };
#pragma GCC diagnostic pop
        n_out = sizeof(table_) / sizeof(table_[0]);
        return table_;
    }
#if NOTE_SINGLETON
    static inline ::note::Result<void>(*execute_generic_fn_)(void*, ::note::string_view, ::note::BuildFn, void*, void*, const ::note::FieldDesc*, uint8_t, ::note::detail::NcErrorCapture&, bool&, void*, ::note::BodyHandlerFactory, ::note::Safety) = nullptr;
    static inline ::note::Result<void>(*send_fn_)(void*, ::note::BuildFn, void*) = nullptr;
#endif
};
} // namespace note::detail
namespace note::api {

inline void NtnGps::build(JsonBuilder& b) const {
    using meta_ = ::note::detail::request_traits<NtnGps>;
    uint8_t n_; auto* descs_ = meta_::req_field_descs_ptr_(n_);
    ::note::generic_build(b, this, descs_, n_);
#if NOTE_EXTRAS
    for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
        std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                   extras_[i_].value);
#endif
}

#if NOTE_SINGLETON
inline ApiResult<typename NtnGps::Response> NtnGps::execute() const {
    auto build_ = [&](JsonBuilder& b_) { this->build(b_); };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) { (*static_cast<decltype(build_)*>(p_))(b_); };
    Response rsp_{};
    ::note::detail::NcErrorCapture nc_err_;
    bool exhausted_ = false;
    using meta_ = ::note::detail::request_traits<NtnGps>;
    auto rv_ = meta_::execute_generic_fn_(::note::detail::api_nc_singleton_, notecard_request, fn_, &build_, &rsp_, meta_::field_descs_ptr(), meta_::field_count, nc_err_, exhausted_, nullptr, nullptr, safety);
    if (!rv_) return ::note::Unexpected(rv_.error());
    if (!nc_err_.empty()) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Notecard, ::note::Cause::Unspecified, nc_err_.view()});
    if (exhausted_) return ApiResult<Response>(::note::ErrorInfo{::note::Error::Overflow, ::note::Cause::Unspecified, NOTE_ERR("arena exhausted")});
    return ApiResult<Response>(std::move(rsp_));
}
inline Result<void> NtnGps::command() const {
    auto build_ = [&](JsonBuilder& b_) {
        b_.add("cmd", notecard_request);
        this->build(b_);
    };
    BuildFn fn_ = [](JsonBuilder& b_, void* p_) {
        (*static_cast<decltype(build_)*>(p_))(b_);
    };
    using meta_ = ::note::detail::request_traits<NtnGps>;
    return meta_::send_fn_(::note::detail::api_nc_singleton_, fn_, &build_);
}
#endif


} // namespace note::api
