// AUTO-GENERATED by tools/codegen/generate.py -- DO NOT EDIT
#pragma once

#include <note/body.hpp>
#ifndef NOTE_EXTRAS
#define NOTE_EXTRAS 1
#endif
#if NOTE_EXTRAS
#include <note/dyn_field.hpp>
#endif
#include <note/field.hpp>
#include <note/json.hpp>
#include <note/json_sax.hpp>
#include <note/binary_request.hpp>
#include <note/notecard.hpp>
#include <note/print.hpp>
#include <note/safety.hpp>
#include <note/string_pool.hpp>
#include <note/types.hpp>
#include <note/progmem.hpp>
#include <note/target.hpp>

namespace note::api {








/// Performs an HTTP or HTTPS request against an external endpoint, with the
/// ability to specify any valid HTTP method.
///
/// @skus{CELL,CELL+WIFI,SKYLO,WIFI}
struct Web {
    struct keys_ {
        static constexpr char req[] NOTE_FLASH_ATTR = "web";
        static constexpr char content[] NOTE_FLASH_ATTR = "content";
        static constexpr char method[] NOTE_FLASH_ATTR = "method";
        static constexpr char name[] NOTE_FLASH_ATTR = "name";
        static constexpr char route[] NOTE_FLASH_ATTR = "route";
        static constexpr char rsp_cobs[] NOTE_FLASH_ATTR = "cobs";
        static constexpr char rsp_length[] NOTE_FLASH_ATTR = "length";
        static constexpr char rsp_payload[] NOTE_FLASH_ATTR = "payload";
        static constexpr char rsp_result[] NOTE_FLASH_ATTR = "result";
    };

    static constexpr string_view notecard_request = "web";
    static constexpr bool supports_cmd = true;
    static constexpr Safety safety = Safety::NonIdempotent;
    static constexpr Skus skus = Skus::from(Product::Cell, Product::CellWifi, Product::Skylo, Product::WiFi);

    Notecard* nc_ = nullptr;

    /// The MIME type of the body or payload of the response. Default is
    /// `application/json`.
    struct content_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        Web& operator()(note::string_view v);
    } content{};
    /// The HTTP method of the request. Must be one of GET, PUT, POST, DELETE,
    /// PATCH, HEAD, OPTIONS, TRACE, or CONNECT.
    // method: CONNECT | DELETE | GET | HEAD | OPTIONS | PATCH | POST | PUT | TRACE
    struct method_t : Field<note::string_view> {
#if __cplusplus >= 202002L && !defined(__clang__)
        constexpr method_t() = default;
        template<std::size_t N>
        consteval method_t(const char (&s)[N])
            : Field<note::string_view>(note::string_view(s, N - 1)) {
            note::string_view sv(s, N - 1);
            if (sv != "CONNECT" && sv != "DELETE" && sv != "GET" && sv != "HEAD" && sv != "OPTIONS" && sv != "PATCH" && sv != "POST" && sv != "PUT" && sv != "TRACE")
                throw "web: invalid value for 'method'";
        }
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, method_t>)
        constexpr method_t(U&& v) : Field<note::string_view>(note::string_view(std::forward<U>(v))) {}
        template<typename U>
            requires std::is_convertible_v<U, note::string_view>
                  && (!std::is_array_v<std::remove_reference_t<U>>)
                  && (!std::is_same_v<std::decay_t<U>, method_t>)
        method_t& operator=(U&& v) {
            Field<note::string_view>::operator=(note::string_view(std::forward<U>(v)));
            return *this;
        }
        method_t& operator=(std::nullopt_t) { Field<note::string_view>::reset(); return *this; }
        method_t(const method_t&) = default;
        method_t& operator=(const method_t&) = default;
        method_t(method_t&&) = default;
        method_t& operator=(method_t&&) = default;
#else
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
#endif
        static constexpr note::string_view CONNECT{"CONNECT"};
        static constexpr note::string_view DELETE{"DELETE"};
        static constexpr note::string_view GET{"GET"};
        static constexpr note::string_view HEAD{"HEAD"};
        static constexpr note::string_view OPTIONS{"OPTIONS"};
        static constexpr note::string_view PATCH{"PATCH"};
        static constexpr note::string_view POST{"POST"};
        static constexpr note::string_view PUT{"PUT"};
        static constexpr note::string_view TRACE{"TRACE"};
        Web& operator()(note::string_view v);
    } method{};
    /// A web URL endpoint relative to the host configured in the Proxy Route.
    /// URL parameters may be added to this argument as well (e.g.
    /// `/getLatest?id=1`).
    struct name_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        Web& operator()(note::string_view v);
    } name{};
    /// Alias for a Proxy Route in Notehub.
    struct route_t : Field<note::string_view> {
        using Field<note::string_view>::Field;
        using Field<note::string_view>::operator=;
        Web& operator()(note::string_view v);
    } route{};

    // Valid values for 'method':
    //   "CONNECT" — Establishes a tunnel to the server identified by the target resource.
    //   "DELETE" — Performs a simple HTTP or HTTPS `DELETE` request against an external ...
    //   "GET" — Performs a simple HTTP or HTTPS `GET` request against an external end...
    //   "HEAD" — Requests the headers that would be returned if the URL was requested ...
    //   "OPTIONS" — Requests the communication options available for the target resource.
    //   "PATCH" — Applies partial modifications to a resource at the target endpoint.
    //   "POST" — Performs a simple HTTP or HTTPS `POST` request against an external en...
    //   "PUT" — Performs a simple HTTP or HTTPS `PUT` request against an external end...
    //   "TRACE" — Performs a message loop-back test along the path to the target resource.
    // consteval: only callable at compile time (C++20)
#if __cplusplus >= 202002L
    static consteval note::string_view validatedMethod(const char* v) {
        note::string_view sv{v};
        if (sv != "CONNECT" && sv != "DELETE" && sv != "GET" && sv != "HEAD" && sv != "OPTIONS" && sv != "PATCH" && sv != "POST" && sv != "PUT" && sv != "TRACE")
            throw "web: invalid value for 'method'";
        return sv;
    }
#endif

#if NOTE_EXTRAS
    template<typename T>
    auto& extra(note::string_view k_, T v_) {
        if (extras_count_ < NOTE_EXTRAS_MAX)
            extras_[extras_count_++] = {k_, note::DynValue{v_}};
        return *this;
    }
    auto& extra(note::string_view k_, const char* v_) {
        return extra(k_, note::string_view{v_});
    }

    note::DynField operator[](note::string_view k_) {
        if (k_ == "content") return note::dyn_field_for(content);
        if (k_ == "method") return note::dyn_field_for(method);
        if (k_ == "name") return note::dyn_field_for(name);
        if (k_ == "route") return note::dyn_field_for(route);
        if (extras_count_ < NOTE_EXTRAS_MAX) {
            auto& slot = extras_[extras_count_++];
            slot.key = k_;
            return note::dyn_field_for(slot.value);
        }
        return {};
    }

    std::array<note::detail::ExtraSlot, NOTE_EXTRAS_MAX> extras_{};
    uint8_t extras_count_ = 0;
#endif // NOTE_EXTRAS

    /// Response containing the result of an HTTP or HTTPS request to an
    /// external endpoint.
    struct Response {
        /// The size of the COBS-encoded data (in bytes).
        note::ResponseField<int32_t> cobs{};
        /// The length of the returned binary payload (in bytes).
        note::ResponseField<int32_t> length{};
        /// A base64-encoded binary payload from the external service, if any.
        /// The maximum response size from the service is 8192 bytes.
        note::ResponseField<note::string_view> payload{};
        /// The HTTP Status Code
        note::ResponseField<int32_t> result{};

        const JsonReader* body() const { return body_.get(); }

        template<typename T>
        T bodyAs() const {
            if (body_) return parse_body_<T>(*body_);
            return T{};
        }

        static Response parse(std::unique_ptr<JsonReader> reader_) {
            Response rsp;
            rsp.cobs = reader_->get_int("cobs");
            rsp.length = reader_->get_int("length");
            rsp.payload = reader_->get_string("payload");
            rsp.result = reader_->get_int("result");
            rsp.body_ = reader_->get_object("body");
            rsp.reader_ = std::move(reader_);
            return rsp;
        }

        // Non-owning parse: string_views point into the reader's data.
        // The reader (and its underlying JSON buffer) must outlive the Response,
        // or the caller must consume all string fields before the reader is reused.
        static Response parse(const JsonReader& reader_) {
            Response rsp;
            rsp.cobs = reader_.get_int("cobs");
            rsp.length = reader_.get_int("length");
            rsp.payload = reader_.get_string("payload");
            rsp.result = reader_.get_int("result");
            rsp.body_ = reader_.get_object("body");
            return rsp;
        }

        // SAX sink — zero-allocation streaming parse into Response fields.
        // String fields are interned into the StringPool immediately, so
        // string_views survive after the parser's scratch buffer is reused.
        struct Sink : ::note::JsonSink {
            Response& rsp;
            ::note::StringPool& pool_;
            Sink(Response& r, ::note::StringPool& pool) : rsp(r), pool_(pool) {}
            void on_string(::note::string_view k_, ::note::string_view v_) override {
                v_ = pool_.intern(v_);
                if (note::flash(keys_::rsp_payload) == k_) { rsp.payload = v_; return; }
            }
            void on_number(::note::string_view k_, ::note::string_view raw_) override {
                if (note::flash(keys_::rsp_cobs) == k_) { rsp.cobs = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_length) == k_) { rsp.length = ::note::parse_int(raw_); return; }
                if (note::flash(keys_::rsp_result) == k_) { rsp.result = ::note::parse_int(raw_); return; }
            }
            void reset() override { rsp = Response{}; }
        };

        void intern_strings(::note::StringPool& pool) {
            if (!payload.empty()) payload = pool.intern(payload);
        }

#ifdef ARDUINO
        /// Arduino Printable: prints response fields to Serial or any Print stream.
        size_t printTo(Print& p) const {
            size_t n = p.print("{");
            bool first_ = true;
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"cobs\":");
            n += note::detail::print_json_value(p, cobs.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"length\":");
            n += note::detail::print_json_value(p, length.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"payload\":");
            n += note::detail::print_json_value(p, payload.value());
            if (!first_) n += p.print(",");
            first_ = false;
            n += p.print("\"result\":");
            n += note::detail::print_json_value(p, result.value());
            n += p.print("}");
            return n;
        }
#endif

    private:
        std::unique_ptr<JsonReader> reader_;
        std::unique_ptr<JsonReader> body_;

        template<typename T>
        static T parse_body_(const JsonReader& r) {
            if constexpr (detail::has_note_fields_trait<T>::value) {
                return ::note::parse<T>(r);
            }
#if __cplusplus >= 202002L
            else if constexpr (detail::ReflectableAggregate<T>) {
                return ::note::parse<T>(r);
            }
#endif
            else {
                (void)r;
                return T{};
            }
        }
    };

    void build(JsonBuilder& b) const {
        if (content) note::add_flash(b, note::flash(keys_::content), *content);
        if (method) note::add_flash(b, note::flash(keys_::method), *method);
        if (name) note::add_flash(b, note::flash(keys_::name), *name);
        if (route) note::add_flash(b, note::flash(keys_::route), *route);
#if NOTE_EXTRAS
        for (uint8_t i_ = 0; i_ < extras_count_; ++i_)
            std::visit([&](auto&& v_) { b.add(extras_[i_].key, v_); },
                       extras_[i_].value);
#endif
    }

    auto execute() const { return nc_->execute(*this); }
    auto execute(Notecard& nc) const { return nc.execute(*this); }
    Result<void> command() const { return nc_->command_typed(*this); }
    Result<void> command(Notecard& nc) const { return nc.command_typed(*this); }

#ifdef ARDUINO
    /// Arduino Printable: prints the JSON request to Serial or any Print stream.
    size_t printTo(Print& p) const {
        size_t n = p.print("{\"req\":\"");
        n += p.print(notecard_request.data());
        n += p.print("\"");
        if (content) {
            n += p.print(",\"content\":");
            n += note::detail::print_json_value(p, *content);
        }
        if (method) {
            n += p.print(",\"method\":");
            n += note::detail::print_json_value(p, *method);
        }
        if (name) {
            n += p.print(",\"name\":");
            n += note::detail::print_json_value(p, *name);
        }
        if (route) {
            n += p.print(",\"route\":");
            n += note::detail::print_json_value(p, *route);
        }
        n += p.print("}");
        return n;
    }
#endif

};

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"
inline Web& Web::content_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<Web*>(
        reinterpret_cast<char*>(this) - offsetof(Web, content));
}
inline Web& Web::method_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<Web*>(
        reinterpret_cast<char*>(this) - offsetof(Web, method));
}
inline Web& Web::name_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<Web*>(
        reinterpret_cast<char*>(this) - offsetof(Web, name));
}
inline Web& Web::route_t::operator()(note::string_view v) {
    Field<note::string_view>::operator=(v);
    return *reinterpret_cast<Web*>(
        reinterpret_cast<char*>(this) - offsetof(Web, route));
}
#pragma GCC diagnostic pop


} // namespace note::api
